### ISSUE TITLE
Serialize publishers as authors

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#100]
In our source data, this example standard specifies a single contributor who is a publisher (has neither “author” nor “editor” role):

- https://github.com/ietf-ribose/relaton-data-ieee/blob/main/data/IEEE_181.2003.yaml#L26-L36

RFC 7991 only supports information about authors (and/or editors) under `<author>`: https://datatracker.ietf.org/doc/html/rfc7991#section-2.7

I am not able to find any element representing a publisher in the RFC.

Do we omit publisher from generated XML (and in the case of above document, have no `<author>` element at all), or include publishers as authors? What about contributors with other non-author roles, e.g. “translator” and so on?

**Comment by strogonoff** [comment]
Should probably serialize publishers as authors, to match xml2rfc output.

**Comment by TonyLHansen** [comment]
Perhaps the reference field can be extended in the future to have another attribute, ala editor, that indicates that the entry is for a publisher name, or another attribute other than author can be introduced. But in the current reference definition, author is all we have.

**Comment by ronaldtse** [comment]
Thanks @TonyLHansen and I agree with the solution: to represent the standards body as an `<author><organization>`.

I would however like to confirm with @rjsparks on the desired behavior.

This is technically a workaround to the limitation of the current BibXML model that it cannot handle a publisher. In ISO 690 for example, authors, editors and publishers are distinct contribution roles.

In the legacy dataset, the behavior mentioned by @TonyLHansen is used:
http://xml2rfc.tools.ietf.org/public/rfc/bibxml-3gpp/reference.3GPP.01.01.xml
```xml
<reference anchor="3GPP.01.01">
<front>
<title>
Technical Specifications and Technical Reports for a GERAN-based 3GPP system
</title>
<author>
<organization>3GPP</organization>
</author>
<date day="26" month="September" year="2003"/>
</front>
<seriesInfo name="3GPP TS" value="01.01 3.1.0"/>
<format type="HTML" target="http://www.3gpp.org/ftp/Specs/html-info/0101.htm"/>
</reference>
```

**Comment by rjsparks** [comment]
Ugly, but lets move forward. I'll call the CMT's attention to this.

**Comment by rjsparks** [comment]
This is fine, and we can close this.

**Comment by reschke** [comment]
Looks good to me.
