### ISSUE TITLE
Are non-XML files read by xml2rfc integrations?

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#104]
Does the service need to keep maintaining same responses as xml2rfc web server to these three paths?

- http://xml2rfc.tools.ietf.org/public/rfc/bibxml/rfc2629-other.ent
- http://xml2rfc.tools.ietf.org/public/rfc/bibxml/rfc2629-xhtml.ent
- http://xml2rfc.tools.ietf.org/public/rfc/bibxml/rfc2629.dtd

They seem to exist in other directories, not just `bibxml`.

Some of the other directories may contain other files and subdirectories, including RDF.

**Comment by ronaldtse** [comment]
I don't think we need to handle them, they are technically not part of the BibXML service.

However let's see what @rjsparks thinks.

**Comment by rjsparks** [comment]
Do not provide those files. Ignore them please.

**Comment by ronaldtse** [comment]
Thank you @rjsparks @strogonoff ! Closing.
