### ISSUE TITLE
Deliverable handoff to IETF

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#109]
These are remaining tasks we need to complete for proper handoff to IETF.

* [ ] #63
* [x] #31 
  * Ensuring we don't return a wrong standard while trying to find up-to-date equivalent for legacy xml2rfc path

**Comment by strogonoff** [comment]
RFP requirement coverage overview is at https://dev.bibxml.org/static/docs/rfp-requirements.html.

**Comment by strogonoff** [comment]
I believe #31 and relevant aspects of #63 (concerning xml2rfc paths) were implemented, so closing.
