### ISSUE TITLE
Legacy mappings don't handle the variant without the 'draft-' prefix.

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#110]
This is related to #62

The existing production service for bibxml-ids recognizes 'foo-bar-baz' as an alias for 'draft-foo-bar-baz'. The current dev service does not.

See these (which return the same thing):

http://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.I-D.draft-sparks-sipcore-multiple-reasons-00.xml
http://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.I-D.sparks-sipcore-multiple-reasons-00.xml

At dev.bibxml.org, the analogous link for the first URL above succeeds. The second fails.

**Comment by rjsparks** [comment]
The datatracker also recognizes these variants - see https://datatracker.ietf.org/doc/bibxml3/reference.I-D.sparks-sipcore-multiple-reasons.xml

**Comment by strogonoff** [comment]
This is related to #63 (in progress).

**Comment by strogonoff** [comment]
It doesn’t seem like `reference.I-D.sparks-sipcore-multiple-reasons-00.xml` exists here: https://github.com/ietf-ribose/bibxml-data-archive/tree/main/bibxml3/reference.I-D.sparks-sipcore-multiple-reasons-00.xml

So this is why fallback isn’t working.

I believe it _should_ be helped when #63 is implemented, but I wonder why we don’t have that file🤔

**Comment by rjsparks** [comment]
It is in the sync point I provided (are you using it)?, and available from the datatracker...
```
% rsync rsync.ietf.org::bibxml-ids/reference.I-D.draft-sparks-sipcore-multiple-reasons-00.xml
-rw-r--r--         904 2022/01/14 11:02:47 reference.I-D.draft-sparks-sipcore-multiple-reasons-00.xml

% curl -s https://datatracker.ietf.org/doc/bibxml3/draft-sparks-sipcore-multiple-reasons-00.xml | grep title
      <title>Multiple SIP Reason Header Field Values</title>
```

**Comment by rjsparks** [comment]
Ahah - no. Note that the `draft-<foobar>` variant is present, but not the `foobar` variant. That is something you should just look for if the string after .I-D. doesn't start with `draft-`.

**Comment by rjsparks** [comment]
Specifically, I don't think #63 will help you here unless you adjust the scope of #63.

**Comment by strogonoff** [comment]
Well, the 63 might work in a way where we ask Datatracker any time we can't find a document, which would catch cases like these, although ideally it should only be used for new drafts and we should resolve the already existing ones without an extra request.

**Comment by strogonoff** [comment]
This is fixed now with [new resolution logic](https://github.com/ietf-ribose/bibxml-service/blob/0c2e18d8c43aea011c1e601124fdf4530be84977/xml2rfc_compat/fetchers.py#L52-L78). Both variants with and without the `draft-` prefix should work.

(However, it could be a problem that our bibxml data archive repository does not contain these path variants, I wonder if I should file a separate issue about xml2rfc path resolution tool having to support these aliases even if they aren’t listed separately in the archive.)

**Comment by rjsparks** [comment]
The ship sailed already - there are many references of that form in the draft archive.
For now, we have to.
In the long run, I expect we will deprecate the 'draft-'less versions altogether, but that will require community guidance.

**Comment by TonyLHansen** [comment]
The draft-less and number-less names have always been used to reference the series

The names with draft- prefix and -## suffix have always been used to reference the exact draft

Those are the only versions that were ever advertised as valid -- nothing else.

**Comment by TonyLHansen** [comment]
I did  confirm that the redirect did not do sufficient error checking for invalid names.

**Comment by rjsparks** [comment]
That's not particularly relevant to the reality of them being _used_. They are, and that's the clench-end of this decision.

**Comment by TonyLHansen** [comment]
no, I checked:

These are the only files that I see:

```
-rw-rw-r-- 2 henrik staff 1044 Aug  9  2018 reference.I-D.farmer-6man-exceptions-64.xml
-rw-rw-r-- 2 henrik staff 1133 Jan  6  2019 reference.I-D.farmer-6man-routing-64.xml
-rw-rw-r-- 2 henrik staff 1564 Sep 16  2009 reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml
-rw-rw-r-- 2 henrik staff 1218 Dec 18  2017 reference.I-D.ietf-tsvwg-ieee-802-11.xml
-rw-rw-r-- 2 henrik staff 1116 Mar  7  2007 reference.I-D.mahy-sipping-16.xml
-rw-rw-r-- 2 henrik staff 1017 Feb  7  2006 reference.I-D.songlee-aes-cmac-96.xml
-rw-rw-r-- 2 henrik staff 1138 Nov 29  2012 reference.I-D.srinivasan-fr-over-mpls-with-frf-16.xml
-rw-rw-r-- 2 henrik staff 1461 Jun 24  2016 reference.I-D.szigeti-tsvwg-ieee-802-11.xml
-rw-rw-r-- 2 henrik staff 1404 May 15  2019 reference.I-D.zhang-mif-api-extension-802-21.xml
```

and all of those -## are NOT the version numbers. For example, 

```
$ ls *farmer-6man-exceptions*
reference.I-D.draft-farmer-6man-exceptions-64-00.xml  reference.I-D.draft-farmer-6man-exceptions-64-02.xml  reference.I-D.draft-farmer-6man-exceptions-64-05.xml  reference.I-D.draft-farmer-6man-exceptions-64-09.xml
reference.I-D.draft-farmer-6man-exceptions-64-01.xml  reference.I-D.draft-farmer-6man-exceptions-64-03.xml  reference.I-D.draft-farmer-6man-exceptions-64-06.xml  reference.I-D.farmer-6man-exceptions-64.xml
```

```
$ ls *ietf-16ng-ip-over-ethernet-over-802-dot-16*
reference.I-D.draft-ietf-16ng-ip-over-ethernet-over-802-dot-16-07.xml  reference.I-D.draft-ietf-16ng-ip-over-ethernet-over-802-dot-16-10.xml  reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml
reference.I-D.draft-ietf-16ng-ip-over-ethernet-over-802-dot-16-08.xml  reference.I-D.draft-ietf-16ng-ip-over-ethernet-over-802-dot-16-11.xml
reference.I-D.draft-ietf-16ng-ip-over-ethernet-over-802-dot-16-09.xml  reference.I-D.draft-ietf-16ng-ip-over-ethernet-over-802-dot-16-12.xml
```

**Comment by rjsparks** [comment]
From the draft archive:
```
rjsparks@undex draft % ls -1t | egrep 'xml$' | xargs -n1 grep -H 'reference.I-D.' | grep -v 'reference.I-D.draft-' | egrep "\-[0-9][0-9].xml[^:]"
draft-spaghetti-idr-deprecate-8-9-10-00.xml:            <?rfc include="reference.I-D.ietf-idr-bgp-open-policy-18.xml"?>
draft-ietf-sidrops-rpki-rsc-05.xml:        <reference anchor="I-D.ymbk-sidrops-rpki-has-no-identity" xml:base="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.ymbk-sidrops-rpki-has-no-identity-00.xml">
draft-abhishek-coin-xr-edge-cloud-00.xml:<!ENTITY I-D.draft-defoy-coms-subnet-interconnection-04 SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.defoy-coms-subnet-interconnection-00.xml">
draft-ietf-tsvwg-transport-encrypt-21.xml:<!ENTITY I-D.ietf-6man-ipv6-alt-mark SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.ietf-6man-ipv6-alt-mark-00.xml">
draft-farmer-6man-routing-64-02.xml:<!ENTITY I-D.farmer-6man-exceptions-64 SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.farmer-6man-exceptions-64.xml">
draft-farmer-6man-routing-64-01.xml:<!ENTITY I-D.farmer-6man-exceptions-64 SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.farmer-6man-exceptions-64.xml">
draft-farmer-6man-routing-64-00.xml:<!ENTITY I-D.farmer-6man-exceptions-64 SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.farmer-6man-exceptions-64.xml">
draft-jjmb-httpbis-trusted-traffic-00.xml:<!ENTITY IDSRH SYSTEM "http://xml.resource.org/public/rfc/bibxml/reference.I-D.ietf-6man-segment-routing-header-07.xml">
draft-ietf-bfd-seamless-use-case-02.xml:<!ENTITY I-D.geib-spring-oam-usecase SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.geib-spring-oam-usecase-04.xml">
draft-yourtchenko-colitti-nd-reduce-multicast-00.xml:<!ENTITY I-D.vyncke-6man-mcast-not-efficient-01 SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.vyncke-6man-mcast-not-efficient-01.xml">
draft-ietf-v6ops-v4v6tran-framework-02.xml:<!ENTITY DRAFT-wimax SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml">
draft-ietf-v6ops-v4v6tran-framework-01.xml:<!ENTITY DRAFT-wimax SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml">
draft-ietf-v6ops-v4v6tran-framework-00.xml:<!ENTITY DRAFT-wimax SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml">
draft-carpenter-v4v6tran-framework-00.xml:<!ENTITY DRAFT-wimax SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml">
draft-moskowitz-hip-rfc5201-bis-02.xml:<!ENTITY fundamental-ecc SYSTEM "http://medon.htt-consult.com/~rgm/hip/reference.I-D.fundamental-ecc-03.xml" >
draft-ietf-v6ops-isp-scenarios-00.xml:<!ENTITY DRAFT-wimax SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml">
draft-carpenter-v6ops-isp-scenarios-02.xml:<!ENTITY DRAFT-wimax SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml">
draft-perkins-behave-dpinat-00.xml:    "http://www.psg.com/~charliep/txt/sourceIP/reference.I-D.source_IP-NAT.txt-00.xml">
draft-fajardo-dime-misc-app-test-suite-01.xml:'http://xml.resource.org/public/rfc/bibxml3/reference.I-D.fajardo-dime-base-test-00.xml'>
draft-ietf-16ng-ipv4-over-802-dot-16-ipcs-06.xml:<!ENTITY ETHCS PUBLIC '' "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml" >
draft-ietf-16ng-ipv4-over-802-dot-16-ipcs-05.xml:<!ENTITY ETHCS PUBLIC '' "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.ietf-16ng-ip-over-ethernet-over-802-dot-16.xml" >
rjsparks@undex draft % ls -1t | egrep 'xml$' | xargs -n1 grep -H 'reference.I-D.' | grep -v 'reference.I-D.draft-' | egrep "\-[0-9][0-9].xml[^:]" | grep -v 'dot
-16'
draft-spaghetti-idr-deprecate-8-9-10-00.xml:            <?rfc include="reference.I-D.ietf-idr-bgp-open-policy-18.xml"?>
draft-ietf-sidrops-rpki-rsc-05.xml:        <reference anchor="I-D.ymbk-sidrops-rpki-has-no-identity" xml:base="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.ymbk-sidrops-rpki-has-no-identity-00.xml">
draft-abhishek-coin-xr-edge-cloud-00.xml:<!ENTITY I-D.draft-defoy-coms-subnet-interconnection-04 SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.defoy-coms-subnet-interconnection-00.xml">
draft-ietf-tsvwg-transport-encrypt-21.xml:<!ENTITY I-D.ietf-6man-ipv6-alt-mark SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.ietf-6man-ipv6-alt-mark-00.xml">
draft-farmer-6man-routing-64-02.xml:<!ENTITY I-D.farmer-6man-exceptions-64 SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.farmer-6man-exceptions-64.xml">
draft-farmer-6man-routing-64-01.xml:<!ENTITY I-D.farmer-6man-exceptions-64 SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.farmer-6man-exceptions-64.xml">
draft-farmer-6man-routing-64-00.xml:<!ENTITY I-D.farmer-6man-exceptions-64 SYSTEM "http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.farmer-6man-exceptions-64.xml">
draft-jjmb-httpbis-trusted-traffic-00.xml:<!ENTITY IDSRH SYSTEM "http://xml.resource.org/public/rfc/bibxml/reference.I-D.ietf-6man-segment-routing-header-07.xml">
draft-ietf-bfd-seamless-use-case-02.xml:<!ENTITY I-D.geib-spring-oam-usecase SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.geib-spring-oam-usecase-04.xml">
draft-yourtchenko-colitti-nd-reduce-multicast-00.xml:<!ENTITY I-D.vyncke-6man-mcast-not-efficient-01 SYSTEM "http://xml.resource.org/public/rfc/bibxml3/reference.I-D.vyncke-6man-mcast-not-efficient-01.xml">
draft-moskowitz-hip-rfc5201-bis-02.xml:<!ENTITY fundamental-ecc SYSTEM "http://medon.htt-consult.com/~rgm/hip/reference.I-D.fundamental-ecc-03.xml" >
draft-perkins-behave-dpinat-00.xml:    "http://www.psg.com/~charliep/txt/sourceIP/reference.I-D.source_IP-NAT.txt-00.xml">
draft-fajardo-dime-misc-app-test-suite-01.xml:'http://xml.resource.org/public/rfc/bibxml3/reference.I-D.fajardo-dime-base-test-00.xml'>
```

**Comment by rjsparks** [comment]
sorry - editing the above to trim to the last run.

**Comment by TonyLHansen** [comment]
$ ls -l reference.I-D.ymbk-sidrops-rpki-has-no-identity-00.xml
ls: cannot access reference.I-D.ymbk-sidrops-rpki-has-no-identity-00.xml: No such file or directory

the references may exist, but they are not pointing at anything

**Comment by TonyLHansen** [comment]
nor have they ever resolved to real files

**Comment by TonyLHansen** [comment]
sigh

**Comment by TonyLHansen** [comment]
allowing them introduces an ambiguity in the naming scheme :(

**Comment by TonyLHansen** [comment]
I'd really prefer fixing the redirector to not handle those anymore and tell the 10 authors to fix their drafts

**Comment by rjsparks** [comment]
I see no more ambiguity than we already had.

**Comment by TonyLHansen** [comment]
before, you knew that if the prefix "draft-" was not present, any trailing -## HAD to be part of the name and not a generation number

**Comment by TonyLHansen** [comment]
and if draft- WAS present, a trailing -## HAD to be a generation number

**Comment by rjsparks** [comment]
Please reopen this. Despite Tony's misgivings, the following are both expected to work

https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.ietf-stir-certificates.xml
https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.draft-ietf-stir-certificates.xml

Currently only one does.

**Comment by ronaldtse** [comment]
As per @TonyLHansen :

> I'd really prefer fixing the redirector to not handle those anymore and tell the 10 authors to fix their drafts

Is this perception no longer the case? If there are only a limited of people doing this, it might work better to ask them to switch instead of having to maintain a new pattern...

**Comment by rjsparks** [comment]
Yes, I meant it.

The goal will definitely be to support both patterns, as the datatracker already does so. Are you saying this is going to be exceptionally difficult for the bibxml service? (The intent was it would serve what the datatracker serves).

More globally, the naming pattern without "draft-"  introduced another bit of "magic knowledge" that authors would need to know to be able to function to avoid a difficulty we inflicted on ourselves with allowing things that looked like version numbers in names.

Yes, it's extra code to deal, but it's nicer for the authors in the long run to not have to know about the magic tricks.

**Comment by ronaldtse** [comment]
The problem is with the I-Ds that have names that already end in 2 digits as @TonyLHansen provided examples above in
https://github.com/ietf-tools/bibxml-service/issues/110#issuecomment-1043823506

Given the existence of these identifiers, the service cannot distinguish whether `I-D.ietf-tsvwg-ieee-802-11`  is  "draft 11" or the name of the unversioned identifier.

This means the service would not be 100% consistent in resolution and will be extremely confusing to the authors.

**Comment by rjsparks** [comment]
yes, I recognize that and pointed it out myself earlier. It means checking heuristics to see if prefixes of things that end in -nn are existing drafts.

The pain of confusion then shifts to an edge case that we do not have in the draft namespace right now, and that we aren't going to allow to happen. The damage expresses only if we allow names to come into existence where we have both 'draft-whatever' and 'draft-whatever-11' as actual draft names. Again, we don't have this in the dataset right now, so the heuristics always succeed and authors are not confused.

The datatracker handles this in the following places:

The primary logic is at https://github.com/ietf-tools/datatracker/blob/main/ietf/doc/views_doc.py#L1013

To understand it in context, you need to be aware of
https://github.com/ietf-tools/datatracker/blob/main/ietf/doc/views_doc.py#L999
and
https://github.com/ietf-tools/datatracker/blob/main/ietf/doc/urls.py#L103 (and 104).
