### ISSUE TITLE
The main bibxml web service doesn't return bibxml

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#111]
Searching for a draft using the bibxml gui returns a page with the entry data in a web format, but doesn't make it so that the user can actually retrieve the bibxml as far as I can find so far.

**Comment by strogonoff** [comment]
@rjsparks  The relevant API endpoints (https://dev.bibxml.org/api/v1/ as well as xml2rfc-style paths) still work and support `bibxml` format.

The reason GUI links are not shown at the time is these two requirements:

1. GUI should work equivalently for authenticated and anonymous users
2. API must only work for users who supply a valid Datatracker developer’s token

The links that used to be shown in the GUI relied on API endpoints. However, per requirement (2), those endpoints no longer can be accessed by clicking a link, as they now require a Datatracker development token.

If those links are useful (I was not made aware of a use case that requires them), we could introduce equivalent functionality using some other way that doesn’t require making APIs available to anonymous callers (e.g., through Datatracker OAuth2 integration).

**Comment by rjsparks** [comment]
I don't want links into the API necessarily. I want the user to be able to get the bibxml. It is not ok to produce a UI that will not allow them to do so.

@kesara  ran into a similar impedance while working on author-tools and may have something to say.

It's an implementation detail to work out how to gather and serve the bibxml using the api as a backend without giving key s to the user.

@ronaldtse  - I am quite tempted at this point to ask that you defer oidc integration and we'll deal with it later. We aren't going to use it at the UI for now - it was a future-proofing requirement, and the slowdown coming from conversations like this one are not worth having it in at the beginning. If taking that requirement out at this point would not cause a different kind of slowdown, please make it happen. Otherwise, let me know.

**Comment by strogonoff** [comment]
Tracking GUI download links in https://github.com/ietf-ribose/bibxml-service/issues/113.
