### ISSUE TITLE
Computation of "place" is suspect

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#112]
at https://dev.bibxml.org/get-one/by-docid/?doctype=IETF&docid=I-D%20sparks-sipcore-multiple-reasons&query=draft-sparks-sipcore-multiple-reasons&query_format=docid_regex&page=1

the data contains "places" pointing to Fremont, CA.

That is utterly wrong.

I'm guessing there's some attempt to map the knowledge that I work for AMS and AMS headquarters are in Fremont as having anything at all to do with this draft. It does not. Including this information is misleading at best.

If I've guessed correctly at the algorithm that added this, please remove that algorithm. If there's no explicit place declared in the document, do not try to derive one.

**Comment by ronaldtse** [comment]
@rjsparks The "Fremont, CA" entry applies to the publisher's address, and it came from the assumption that the IETF is the publisher and based where AMS is based. 

What is the correct "publisher place" for IETF? Should the "publisher place" be omitted?

Ping @andrew2net the issue refers to this line:
https://github.com/ietf-ribose/relaton-data-ids/blob/main/data/draft-sparks-sipcore-multiple-reasons-00.yaml

**Comment by rjsparks** [comment]
Yes, that line should be omitted (that semantic was _very_ surprising to me).

**Comment by strogonoff** [comment]
Relaton spec allows contacts to be specified as contributor property, that seems more appropriate… Filed https://github.com/ietf-ribose/relaton-data-ids/issues/12, since this looks like an issue with source data.

**Comment by ronaldtse** [comment]
@strogonoff in accordance with the other ticket let's remove "publisher place" for IETF. Thanks.

**Comment by strogonoff** [comment]
> @strogonoff in accordance with the other ticket let's remove "publisher place" for IETF. Thanks.

Are we hiding Relaton’s “place” property for all bibliographic items shown by BibXML service, but leaving the place in source YAML?

**Comment by ronaldtse** [comment]
For RFC and I-D bibliographic items, we should omit “place” entirely (this is a data source issue). 

For other bibliographic items such as for 3GPP or IEEE, the “place” should still be used.

**Comment by strogonoff** [comment]
Then this looks like a data source change (cc @andrew2net). Should something be filed in `relaton-data-*` repositories?

I will not modify the codebase and this could be closed when data sources are reindexed.

**Comment by andrew2net** [comment]
> For other bibliographic items such as for 3GPP or IEEE, the “place” should still be used.

@ronaldtse what places should be added for 3GPP, IEEE and others?

**Comment by strogonoff** [comment]
@andrew2net I believe Ronald means any existing place should be kept for others, but for Internet-Drafts the top-level the place should be removed (and probably for RFCs and rfcsubseries too).

**Comment by ronaldtse** [comment]
> I believe Ronald means any existing place should be kept for others (no change), but for Internet-Drafts the top-level the place should be removed (and probably for RFCs and rfcsubseries too).

Indeed. Let's remove "Place" for RFCs, RFC subseries, and Internet-Draft:
* https://github.com/relaton/relaton-ietf/issues/64

We probably should "add" Places for 3GPP and IEEE but those are separate tickets:
* https://github.com/relaton/relaton-3gpp/issues/8
* https://github.com/relaton/relaton-ieee/issues/15

**Comment by andrew2net** [comment]
@strogonoff @ronaldtse there weren't other places, all the documents fetched by `relaton-ietf` were with pace "Fremont, CA". I removed it for now.

**Comment by strogonoff** [comment]
After reindexing the place should be gone, but indexing async task is stuck so I’ll wait for that to be resolved (filed in https://github.com/ietf-ribose/bibxml-infrastructure/issues/17).

**Comment by opoudjis** [comment]
Just letting you know that OGC expects to see a place of publication for standards, and will now not have one.

**Comment by ronaldtse** [comment]
@opoudjis OGC will just need to deal with the lack of place for RFC/RFC subseries/Internet-Drafts. In any case, the lack of publication place is supported by ISO 690.

**Comment by strogonoff** [comment]
The place is no longer shown, since sources were reindexed: https://dev.bibxml.org/get-one/by-docid/?doctype=IETF&docid=I-D%20ietf-lamps-cmp-algorithms
