### ISSUE TITLE
Make link entries clickable, if they are valid URLs

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#114]

**Comment by ronaldtse** [comment]
@strogonoff is this still valid? Thanks.

**Comment by strogonoff** [comment]
@ronaldtse the intent in this issue was to make links here clickable:

<img width="882" alt="Screenshot 2022-03-25 at 4 59 07 PM" src="https://user-images.githubusercontent.com/292959/160099116-526b5ad5-c5b6-4ed6-b826-86005d02a9ea.png">

However, there was no actual request to make _those_ links clickable (I filed this issue due to misunderstanding). It may or may not have merit though.

Would you say those links should be clickable? Are they expected to always resolve and are users expected to want to navigate to them? If not, can be closed as is, otherwise I’ll address it.

**Comment by ronaldtse** [comment]
@strogonoff ah! Well as a user, I would want that to be clickable. Good find!

**Comment by strogonoff** [comment]
OK, working on it.
