### ISSUE TITLE
Shape of user data returned from Datatracker’s OIDC endpoint

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#116]
After login, the service fetches user information from via the `userinfo_endpoint` (https://datatracker.ietf.org/api/openid/userinfo).

Currently, the service attempts to display a “username” property from that data, but it doesn’t seem to exist.

It’s unclear what structure is returned as integration is not easily testable in local development environment.

**Comment by strogonoff** [comment]
User info data seems to contain the sole property “sub”, JSON structure as follows:

    { "sub": "<number>" }

I can’t make anything out of it and am unable to find a way to query more user data from API in https://datatracker.ietf.org/api/v1/. The question still stands.

**Comment by ronaldtse** [comment]
@rjsparks @kesara could you please help here? Thanks.

**Comment by rjsparks** [comment]
You should be able to get all you need from the oidc claims and not have to go back into /api/v1 for this.
What claims have you configured your client to ask for?

You can see what will be provided for the userinfo claim at:
https://github.com/ietf-tools/datatracker/blob/main/ietf/ietfauth/utils.py#L220

**Comment by rjsparks** [comment]
If you need, we can add a redirect url to your local machine for debugging purposes to the client configuration.

fwiw, using a test client against the sandbox, the userinfo returned for me looks like
```
    "UserInfo": {
        "email": "rjsparks@nostrum.com",
        "family_name": "Sparks",
        "given_name": "Robert",
        "name": "Robert Sparks",
        "nickname": "-",
        "picture": "https://www.ietf.org/cdn-cgi/image/fit=scale-down,width=80,height=80/media/photo/rjs2018-2x3.jpg",
        "sub": "420"
    },
```

**Comment by rjsparks** [comment]
looking into the code - it looks like you're trying to implement an oidc client yourself directly on top of oauth2? Did you consider using an existing oidc client implementation?

**Comment by rjsparks** [comment]
at https://github.com/ietf-ribose/bibxml-service/blob/b4a9415284d66c20369771983abf292fa66c5621/datatracker/oauth.py#L333 you want to get a token that has both openid and profile in scope. I think the library you're using wants `scope=['openid', 'profile']`

**Comment by strogonoff** [comment]
> looking into the code - it looks like you're trying to implement an oidc client yourself directly on top of oauth2? Did you consider using an existing oidc client implementation?

Since the goal was a bare minimum working implementation I opted for an already known library to save time vetting other libraries. This may have been a misjudgement on my part.

> I think the library you're using wants scope=['openid', 'profile']

Thank you for the pointer.

> If you need, we can add a redirect url to your local machine for debugging purposes to the client configuration.

If it’s not a problem, I would not mind having credentials that could redirect to `http://localhost:8000/datatracker-auth/callback/` for testing purposes. I don’t expect I’ll need them by Tuesday anymore. For the time being, I work around this by requesting logs from dev.bibxml.org (it’s just that iterating takes a bit longer).

**Comment by strogonoff** [comment]
Thank you! Will close this issue when credentials are no longer needed and #147 is done.
