### ISSUE TITLE
Implement legacy path pattern: IETF RFCs (`bibxml`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#12]
IETF RFCs (`bibxml`)
* (previous location) http://xml2rfc.tools.ietf.org/public/rfc/bibxml/
* Pattern: http://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.{NNNN}.xml

Legacy pattern(s) to implement:
* `https://{hostname}/public/rfc/bibxml/reference.RFC.{NNNN}.xml`

We need to parse `NNNN` and return the appropriate RFC NNNN in BibXML format.

**Comment by strogonoff** [comment]
These paths now work: https://dev.bibxml.org/public/rfc/bibxml/reference.RFC.7741.xml
