### ISSUE TITLE
The preexisting xml2rfc web server path resolution logic

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#126]
It is a fact that [the xml2rfc tools snapshot](https://github.com/ietf-ribose/bibxml-data-archive) [obtained via rsync endpoint](https://github.com/ietf-ribose/bibxml-data-archive-sync/blob/8d0da7eea1d65429dcbb1d30daf655c997666b60/.github/workflows/import.yml#L33-L43) does not contain all the paths that can be accessed via `/public/rfc/…/` URLs.

- One aspect of that was known to me before: some top-level directories have aliases (e.g., `bibxml2` -> `bibxml-misc`). BibXML service accommodates that, and I thought that was the extent of it.
- However, while working on #110, we have discovered that file-level aliases also exist. In particular, under `bibxml3` some paths can resolve with and without the `draft-` prefix. (Now the service accommodates that as well, although it does not yet list those paths under xml2rfc path resolution checker tool.)

My question is, what exactly are _all_ possible aliasing scenarios implemented by the preexisting xml2rfc tools web server? Does the above cover all of them at this point?

I think @rjsparks (or someone in charge of rsync endpoint/old xml2rfc web server) may be able to clarify this.

**Comment by strogonoff** [comment]
Does that mean `draft-`-prefixed variants _should_ return 404 if requested?

**Comment by rjsparks** [comment]
@strogonoff     - I will go look through the services again, but you should move ahead expecting that there are no others such things. I do not expect to find any.

**Comment by TonyLHansen** [comment]
The draft-less and number-less names have always been used to reference the series

The names with draft- prefix and -## suffix have always been used to reference the exact draft

Those are the only versions that were ever advertised as valid -- nothing else.

**Comment by strogonoff** [comment]
Am continuing under the assumption that there is no other aliasing/redirection in preexisting xml2rfc paths.
