### ISSUE TITLE
URGENT: XML/JSON download links should be shown to ALL users even without Datatracker authentication

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#127]
https://github.com/ietf-ribose/bibxml-service/issues/113#issuecomment-1036142854_ wrote:
> XML & JSON download links are now shown to users who are authenticated via Datatracker.

The requirement of the BibXML service RFP is to make the API service available to the public, whether authenticated or not.

We need to fix this.

**Comment by strogonoff** [comment]
This is an oxymoron. We cannot prevent unauthorized API access if we output JSON and XML to unauthenticated users, so one requirement or the other has to go.

**Comment by TonyLHansen** [comment]
Accessing the bibxml data must work unauthenticated. It's a public service.

**Comment by strogonoff** [comment]
Based on the above comment, I assume that API should not require a Datatracker token. I was told there is, so there might have been a miscommunication. Filed #138.

**Comment by JayDaley** [comment]
From the RFP:
> The APIs will require the use of Datatracker-generated API tokens. Individuals will use personal API tokens generated from their accounts page. The Datatracker will provide an interface for validating tokens. Systems using the private APIs will use administratively provisioned tokens. The web service will allow anonymous access and will allow the user to log in using Datatracker credentials via OIDC. At this time, there is no expected difference in behavior for the website if the user is logged in or anonymous.

**Comment by strogonoff** [comment]
Yes, there are these behaviors in the RFP requirements section:

A. APIs should require Datatracker token.
B. GUI should support Datatracker OIDC.
C. GUI should work the same for both logged-in and anonymous users.

And this behavior in the RFP deliverables section:

D. GUI should allow anyone to download bibliographic item XML.

Compliance with the above was thought to be achieved through the following behavior (effective at this time): API requires Datatracker token, and GUI allows to download XML and JSON _if_ user is authenticated through Datatracker OIDC login (assuming anyone can create a Datatracker account, (D) is satisfied).

If I am wrong, this behavior can be adjusted to treat (D) as “allow unauthenticated XML download” (no need for OIDC login). But note that this would be in slight conflict with requirement (A), as the service would have to have an XML access endpoint (a de-facto API endpoint) that does not require authentication. (Some measures could be introduced to make this endpoint difficult to use, e.g. by not documenting it in API, checking a cookie set upon web page access, etc., _but any such measure would still be possible to work around_ if someone wanted to access XML programmatically.)

“API” above does not apply to xml2rfc-style path API, which does not require authentication to make sure existing scripts work, but this API is considered legacy/compatibility and intended to be phased out eventually.

**Comment by ronaldtse** [comment]
Thanks all, sorry for having this side discussion. 

I now see that there can be some confusion with what exactly is expected here with regards to requirements stated in the RFP.

There are technically three interfaces to the BibXML service: 
1. the website
2. the API
3. the legacy API

From @strogonoff 's understanding, the RFP stated that the "website" supports unauthenticated requests, but the API is not the website. The API is stated to be able to work with the datatracker token. The legacy API already supports unauthenticated requests for legacy tools. 

My personal feeling (from the perspective of an IETF community member), not judging from the RFP statement, is that the API, the legacy API and the website should all be able to work with unauthenticated requests, until the Tools team decides to enforce authentication to the API. 

I know this is not "stated" by the RFP explicitly but it is my interpretation of the intent in my conversations with @rjsparks . 

However, just to clarify that I have not discussed this particular point with @rjsparks .

Would @rjsparks or @kesara be able to clarify here? Thanks!

**Comment by TonyLHansen** [comment]
This is what I posted over in #138:

Most importantly, are the replacements for the current bibxml GET APIs requiring auth?

My full expectation was that we would be able to either

- replace the current GET calls to [http://xml2rfc.ietf.org/public/rfc/bibxml/](https://xml2rfc.tools.ietf.org/public/rfc/bibxml#/whatever](http://xml2rfc.ietf.org/public/rfc/bibxml/%5D(https://xml2rfc.tools.ietf.org/public/rfc/bibxml#/whatever) with a GET call to the new service, or
- possibly even redirect xml2rfc.ietf.org at some point to the new service.

Perhaps we mean two different things by the term "API"? Are there two sets of APIs, some that require auth and some that do not? As long as the GET API replacements do not, then we're cool.

If not, then there is a major fail IMO.

=======

Based on what @ronaldtse says above, it does sound like there are multiple sets of APIs, some of which should not require auth, and some of which may require auth.

**Comment by rjsparks** [comment]
@Tony - no the legacy api (which is what this thread is calling the ability to GET bibxml using a path like `/public/rfc/bibxmlwhatever`will not (and MUST NOT) require authentication.

It was our intent that the new API require a datatracker personal API key from the beginning. This anticipates the need to be able to say no to automatons that abuse the new API. If it is causing implementation difficulty, it is acceptable to not require this authentication at this time, but we would still prefer to have it.

It was our intent that the webservice (what you currently see in HTML at dev.bibxml.org) allow, but not require oidc login with datatracker credentials, but otherwise provide no change in functionality whether logged in or not. This anticipates having a need to require login in the future.

**Comment by ronaldtse** [comment]
@rjsparks Thanks for the clarification. In this case, I stand corrected -- @strogonoff was right and that the current behavior of dev.bibxml.org is indeed correct.

Specifically:
* legacy API does not require authentication
* new API requires authentication
* the GUI displays information of bibliographic items without authentication
* the GUI does not display/provide the new API links unless the user is authenticated to the Datatracker

If this is the case please close this issue. Appreciate it!

**Comment by ronaldtse** [comment]
That said, can we display a message to the user that the user needs to login before seeing the API XML and JSON links? New issue probably.

**Comment by strogonoff** [comment]
Sure, will add the message shortly.

A related issue that the user is redirected to landing once they complete Datatracker authentication (so they have to find the item again or use the back button and reload) will also be addressed, already clear how to fix.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !
