### ISSUE TITLE
Mapping for NIST references in `misc` dataset to NIST dataset

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#131]
Need mapping for:

```
reference.FIPS.1-1.1980.xml
reference.FIPS.4.1968.xml
reference.FIPS.5-2.1987.xml
reference.FIPS.6-4.1990.xml
reference.FIPS.35.1975.xml
reference.FIPS.46-1.1988.xml
reference.FIPS.46-2.1993.xml
reference.FIPS.46.1977.xml
reference.FIPS.55-2.1987.xml
reference.FIPS.58.1979.xml
reference.FIPS.59.1979.xml
reference.FIPS.74.1981.xml
reference.FIPS.81.1980.xml
reference.FIPS.95-1.1993.xml
reference.FIPS.98.1983.xml
reference.FIPS.113.1985.xml
reference.FIPS.146-1.1989.xml
reference.FIPS.146-1.1991.xml
reference.FIPS.146.1988.xml
reference.FIPS.146.1990.xml
reference.FIPS.161-1.1993.xml
reference.FIPS.180-1.1994.xml
reference.FIPS.180-1.1995.xml
reference.FIPS.180-2.2002.xml
reference.FIPS.180.1993.xml
reference.FIPS.186-1.1998.xml
reference.FIPS.186.1994.xml
reference.FIPS.197.2001.xml
reference.FIPS.500-20.1977.xml
reference.FIPS.500-61.1980.xml
reference.FIPS.500-166.1989.xml
reference.NIST.500-61.1980.xml
reference.NIST.500-162.1990.xml
reference.NIST.500-166.1989.xml
reference.NIST.500-214.1993.xml
reference.NIST.SP.800-185.xml
```

**Comment by ronaldtse** [comment]
The "missing from dataset" ones have been reported to NIST Library: https://github.com/usnistgov/NIST-Tech-Pubs/issues/17

**Comment by strogonoff** [comment]
> ## Can map
> ```yaml
> ---
> reference.FIPS.1-1.1980.xml: NBS FIPS 1
> reference.FIPS.5-2.1987.xml: NBS FIPS 5-2
> reference.FIPS.6-4.1990.xml: NIST FIPS 6-4
> reference.FIPS.35.1975.xml: NBS FIPS 35
> reference.FIPS.46-1.1988.xml: NIST FIPS 46-1
> reference.FIPS.46-2.1993.xml: NIST FIPS 46-2
> reference.FIPS.58.1979.xml: NBS FIPS 58
> reference.FIPS.59.1979.xml: NBS FIPS 59
> reference.FIPS.74.1981.xml: NBS FIPS 74
> reference.FIPS.81.1980.xml: NBS FIPS 81
> reference.FIPS.95-1.1993.xml: NBS FIPS 95-1
> reference.FIPS.98.1983.xml: NBS FIPS 98
> reference.FIPS.113.1985.xml: NBS FIPS 113
> reference.FIPS.146-1.1991.xml: NIST FIPS 146-1
> reference.FIPS.180-1.1995.xml: NIST FIPS 180-1
> reference.FIPS.180.1993.xml: NIST FIPS 180
> reference.FIPS.186.1994.xml: NIST FIPS 186
> reference.FIPS.197.2001.xml: NIST FIPS 197
> reference.FIPS.500-61.1980.xml: NBS SP 500-61
> reference.FIPS.500-166.1989.xml: NIST SP 500-166
> reference.NIST.500-61.1980.xml: NBS SP 500-61
> reference.NIST.500-162.1990.xml: NIST SP 500-162
> reference.NIST.500-166.1989.xml: NIST SP 500-166
> ```
> 
> ## Unable to find in data source
> ```yaml
> ---
> reference.FIPS.4.1968.xml: NBS FIPS 4 (MISSING FROM DATASET)
> reference.FIPS.46.1977.xml: NBS FIPS 46 (MISSING FROM DATASET)
> reference.FIPS.55-2.1987.xml: FIPS PUB 55-2 (MISSING FROM DATASET)
> reference.FIPS.146-1.1989.xml: NIST FIPS 146-1 (1988 version MISSING FROM DATASET)
> reference.FIPS.146.1988.xml: FIPS 146 (MISSING FROM DATASET)
> reference.FIPS.146.1990.xml: FIPS 146 (MISSING FROM DATASET)
> reference.FIPS.161-1.1993.xml: (MISSING FROM DATASET)
> reference.FIPS.180-1.1994.xml: (MISSING FROM DATASET)
> reference.FIPS.180-2.2002.xml: (MISSING FROM DATASET)
> reference.FIPS.186-1.1998.xml: (MISSING FROM DATASET)
> reference.FIPS.500-20.1977.xml: (MISSING FROM DATASET)
> reference.NIST.500-214.1993.xml: (MISSING FROM DATASET)
> ```

Unable to find “NIST FIPS 46-1”. The rest seem OK.
