### ISSUE TITLE
Mapping for IANA references in `misc` dataset to IANA dataset

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#132]
Need mapping for:

```
reference.IANA.application.samlassertion-xml.xml
reference.IANA.application.samlassertion.xml
reference.IANA.application.samlmetadata-xml.xml
reference.IANA.application.samlmetadata.xml
```

**Comment by ronaldtse** [comment]
@rjsparks @TonyLHansen  these references are not IANA registries -- these are IANA media type registrations.

e.g. http://xml2rfc.tools.ietf.org/public/rfc/bibxml2/reference.IANA.application.samlassertion-xml.xml

Do we want to make all IANA media type registrations citable? I'd rather we do a generic implementation instead of keeping these orphans around.

**Comment by ronaldtse** [comment]
@rjsparks I've done some investigation and it should be possible to cite the `<range>` and `<record>` which are entries in a register. It might be a good enhancement for the future, but at the current point perhaps we should just keep these entries in the `misc` dataset to languish?

**Comment by rjsparks** [comment]
Yes

**Comment by ajeanmahoney** [comment]
The RPC has the following guidance for creating references to IANA registries:
https://www.rfc-editor.org/styleguide/part2/#ref_iana_reg

Notes:

- The URL is shortened even if it redirects to an xhtml file. 
- Only top-level registries are cited.
- Dates are not included. 

It is constructed in the XML like this:

    <reference anchor="NAME" target="URL">
      <front>
        <title>Registry Name</title>
        <author>
          <organization>IANA</organization>
        </author>
      </front>
    </reference>

**Comment by ronaldtse** [comment]
Thank you @ajeanmahoney , I've created ticket #237 for the provided guidance. Regarding this current ticket, we are not going to allow citation of IANA registry "items", which was the original question. There were a few instances that RFCs cited register items, and @rjsparks pointed out that it is not supported behavior (at least for now) for the BibXML service.

**Comment by ronaldtse** [comment]
Closing for now.
