### ISSUE TITLE
Internet Drafts are not standards

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#137]
![image](https://user-images.githubusercontent.com/10996692/154749987-954d14c2-4c52-4656-b688-0a6f12529815.png)

The word "Standard" on that page is incorrect. Internet-Drafts are not standards.

**Comment by ronaldtse** [comment]
Thanks @rjsparks for spotting this!

**Comment by strogonoff** [comment]
@ronaldtse Am I correct that this is handled on data source layer? E.g., by @andrew2net

**Comment by ronaldtse** [comment]
The task has been created here: https://github.com/relaton/relaton-ietf/issues/73

**Comment by ronaldtse** [comment]
@rjsparks : we will remove the "standard" nomenclature from this page.

This "standard" keyword originates from ISO 690 -- ISO 690 considers Internet-Drafts of the "Standard" type (ISO 690, 8.13). In any case, the `standard` keyword only exists in the YAML data (not in BibXML data). In BibTeX it is likely that Internet-Drafts in the `tech-report` category.

If keeping the internal type of `standard` is unacceptable, we could potentially change Internet-Drafts to the ISO 690 "Report" category. Would that work?

**Comment by larseggert** [comment]
@ronaldtse do you have a copy of that ISO spec? It should not consider I-Ds as standards.

**Comment by ronaldtse** [comment]
I just realised that you've answered it here before: https://github.com/ietf-ribose/relaton-data-ids/issues/8 . Thanks!

**Comment by strogonoff** [comment]
The interface no longer shows `type` by default. It attempts to use `doctype`, falling back to `type` if there’s no `doctype`. Changing the `type` is covered by issue in `relaton-data-ids` repository. I’m closing this issue.
