### ISSUE TITLE
Do not require authentication in API

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#138]
Current authentication behavior is to require an API token.

**Comment by TonyLHansen** [comment]
Most importantly, are the replacements for the current bibxml GET APIs requiring auth?

My full expectation was that we would be able to either 

1. replace the current GET calls to http://xml2rfc.ietf.org/public/rfc/bibxml/](https://xml2rfc.tools.ietf.org/public/rfc/bibxml#/whatever with a GET call to the new service, or
2. possibly even redirect xml2rfc.ietf.org at some point to the new service.

Perhaps we mean two different things by the term "API"? Are there two sets of APIs, some that require auth and some that do not? As long as the GET API replacements do not, then we're cool.

If not, then there is a major fail IMO.

**Comment by ronaldtse** [comment]
@TonyLHansen we currently have two APIs:

* legacy API that works just like today that returns BibXML. This endpoint does not require authentication. e.g. https://dev.bibxml.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0048.xml
* new API that is supposed to be extensible to other formats. This endpoint currently requires Datatracker authentication: https://dev.bibxml.org/api/v1/by-docid/?doctype=IETF&docid=BCP%2048&format=bibxml

**Comment by TonyLHansen** [comment]
Excellent. Then we're good. From the earlier descriptions, it had sounded like all access had been changed to require auth. Thank you.

**Comment by ronaldtse** [comment]
Closing now. Thanks @TonyLHansen @strogonoff !
