### ISSUE TITLE
Logged-in to datatracker but shown as "Logged in as N/A" on BibXML

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#139]
I'm logged in to the Datatracker but shown as "N/A". My email and full name are set on Datatracker.

<img width="840" alt="Screenshot 2022-02-21 at 2 25 05 PM" src="https://user-images.githubusercontent.com/11865/154900419-6bebaec8-9e34-4051-9a23-676e8324ab17.png">

**Comment by strogonoff** [comment]
See also https://github.com/ietf-ribose/bibxml-service/issues/116.

**Comment by strogonoff** [comment]
Fixed in https://github.com/ietf-ribose/bibxml-service/commit/9399544fc4dc1c7c0e1aecb9291f8784e790e9c2 and https://github.com/ietf-ribose/bibxml-service/commit/f047b0e547a4976a1363128a8e683f141f30efed
