### ISSUE TITLE
Implement legacy path pattern: IETF BCP, FYI, STD (`bibxml9`, `bibxml-rfcsubseries`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#14]
IETF BCP, FYI, STD (`bibxml9`, `bibxml-rfcsubseries`)
* (previous location) http://xml2rfc.tools.ietf.org/public/rfc/bibxml9/
* Pattern 1: http://xml2rfc.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0099.xml
* Pattern 2: http://xml2rfc.ietf.org/public/rfc/bibxml-rfcsubseries/reference.FYI.0099.xml
* Pattern 3: http://xml2rfc.ietf.org/public/rfc/bibxml-rfcsubseries/reference.STD.0099.xml

Legacy pattern(s) to implement:
* Pattern 1: http://{hostname}/public/rfc/bibxml-rfcsubseries/reference.BCP.{NNNN}.xml
* Pattern 2: http://{hostname}/public/rfc/bibxml-rfcsubseries/reference.FYI.{NNNN}.xml
* Pattern 3: http://{hostname}/public/rfc/bibxml-rfcsubseries/reference.STD.{NNNN}.xml

We need to parse the pattern to return the appropriate BibXML content.

**Comment by ronaldtse** [comment]
https://dev.bibxml.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0048.xml
is working:

```xml
<referencegroup anchor="BCP.0048">
<reference target="https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml">
<front>
<title>End-to-end Performance Implications of Slow Links</title>
<author fullname="S. Dawkins" surname="Dawkins" initials="S"/>
<author fullname="G. Montenegro" surname="Montenegro" initials="G"/>
<author fullname="M. Kojo" surname="Kojo" initials="M"/>
<author fullname="V. Magret" surname="Magret" initials="V"/>
<date year="2001" month="July"/>
<abstract>
<t>
This document makes performance-related recommendations for users of network paths that traverse "very low bit-rate" links. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="DOI" value="10.17487/RFC3150"/>
<seriesInfo name="RFC" value="3150"/>
<seriesInfo name="BCP" value="48"/>
</reference>
</referencegroup>
```

@strogonoff can we close this now?

**Comment by ronaldtse** [comment]
@strogonoff actually the line:
```
<reference target="https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml">
```

Is problematic. We need to refer to the https://dev.bibxml.org/ API version of this file.

**Comment by strogonoff** [comment]
> @strogonoff actually the line:
> 
> ```
> <reference target="https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml">
> ```
> 
> Is problematic. We need to refer to the https://dev.bibxml.org/ API version of this file.

The service uses Relaton’s `link` property for that. Per xml2rfc/RFC7991, It’s supposed to link to the _external_ document.

**Comment by ronaldtse** [comment]
@strogonoff so are you saying that this is a Relaton issue?

> Per xml2rfc/RFC7991, It’s supposed to link to the external document

This actually means this link needs to point to the **original information resource**, which should be `https://www.rfc-editor.org/info/bcp48`.

**Comment by strogonoff** [comment]
`bibxml9` paths all resolve now, the report is linked from https://github.com/ietf-ribose/bibxml-service/issues/218#issuecomment-1165241079. Many paths resolve to newer items in `relaton-data-rfcsubseries`, other paths result in a fallback (which can be eliminated later by [taking some measures](https://dev.bibxml.org/static/docs/howto/adjust-xml2rfc-paths.html#how-to-adjust-xml2rfc-style-path-parsing)).
