### ISSUE TITLE
Running tests locally requires online connection

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#14]
### Describe the issue

It seems like accessing Codecov is required for tests to work.

We don’t want two different commands for running tests locally vs. CI, but we also don’t want to require a connection if a developer runs tests locally. Perhaps there’s an easy way to make tests run locally without talking to Codecov?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stefanomunarini** [comment]
Locally, if the containers are up and running, we can use the following command to run the tests:

```
docker-compose exec web python manage.py test
```

Is this enough @strogonoff ? Otherwise we could have a separate docker-compose file for local testing

**Comment by strogonoff** [comment]
Ah, the docs don’t use this command, we should  list both and clarify the difference between them probably: https://bib.ietf.org/static/docs/howto/run-tests.html

**Comment by stefanomunarini** [comment]
I haven't found anything about overriding the test CMD via CLI flag. 

However, I found out that, when specifying multiple docker-compose files (using the -f flag), "Compose combines them into a single configuration"[1] and we can "override and add to their predecessors"[1].

An option, therefore, is to have an additional docker-compose.test-local.yml file that overrides the _command_.

```
version: "3.9"

  test:
    command: sh -c "/wait && python manage.py test"
```

Tests can be then run with the following commands:

- in production

```
docker compose -f docker-compose.test.yml up --exit-code-from test
```

- locally

```
docker compose -f docker-compose.test.yml -f docker-compose.test-local.yml up --exit-code-from test
```
___
[1] https://docs.docker.com/compose/reference/#specifying-multiple-compose-files
