### ISSUE TITLE
Clarification needed: BibXML for Internet-Drafts and RFCs specify location at `reference:target` and `format` elements respectively

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#142]
For Internet-Drafts, the location of the cited information resource is located at `<format>`:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.I-D.sparks-sipcore-multiple-reasons.xml

```xml
<reference anchor="I-D.sparks-sipcore-multiple-reasons">
...
<format type="TXT" target="https://www.ietf.org/archive/id/draft-sparks-sipcore-multiple-reasons-00.txt"/>
```

For RFCs, the location is specified in the `<reference target="...">` attribute:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

```xml
<reference anchor="RFC8126" target="https://www.rfc-editor.org/info/rfc8126">
<!--- `format` does not exist --->
```

@rjsparks @TonyLHansen which is the canonical format?

**Comment by ronaldtse** [comment]
Thanks @rjsparks . 

As a contribution to your discussion in the CMT team, my colleague @andrew2net points out that
> `format` element is deprecated https://datatracker.ietf.org/doc/html/rfc7991#section-3.3

And 1.3.3 says:
>  ```
>    o Deprecate `<format>` because it is not useful and has caused
>      surprise for authors in the past.  If the goal is to provide a
>      single URI (Uniform Resource Identifier) for a reference, use the
>      "target" attribute in `<reference>` instead.
>  ```

In an ideal world, an information resource will have a metadata page and also its various content formats (content and metadata), all available as independent URLs.

**Comment by rjsparks** [comment]
@andrew2net, @ronaldtse: yes, we are quite aware of what the 799x documents say, and are arguing about what the documents that will replace them _should_ say (we refer to this as a `bis` effort), and there's a lot going on at https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues?page=2&q=is%3Aissue+is%3Aopen

The other side of the argument starts here:
https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes-13#section-3.1.27

> [3.1.27](https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes-13#section-3.1.27).  In [Section 3.3](https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes-13#section-3.3), <format>

> The [[RFC7991](https://datatracker.ietf.org/doc/html/rfc7991)] text seems to be based on a misunderstanding of the
   purpose of the <format> element in pointing to alternative
   representations of a reference.  There seems to be no reason in
   removing this ability.  The current implementation does not remove
   alternative <format> entries when converting v2 to v3.  The [RFC 7991](https://datatracker.ietf.org/doc/html/rfc7991)
   text should be adjusted accordingly, and in [RFC 7992](https://datatracker.ietf.org/doc/html/rfc7992) it should be
   specified how to render links to alternative formats for a reference.

Your final sentence argues for both the `target` attribute in the `<reference>` tag *and* the `<format>` tag withing the `<reference>` tag.

But as I note, this will take time to finish working out.

**Comment by rjsparks** [comment]
In the meantime, the best we can do for now for Internet Drafts is to follow the form that the datatracker produces.
