### ISSUE TITLE
docs howto run in production has an incomplete sentence

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#146]
At
>Do not increase the number of Hypercorn workers per instance. Prometheus Python client metric export, as implemented, will not work in multiprocessing scenarios. The supported method of scaling is via increasing

the rest of the sentence is missing,

**Comment by rjsparks** [comment]
If there's a better place to point to for instructions on launching a production instance, please let me know.

**Comment by strogonoff** [comment]
> If there's a better place to point to for instructions on launching a production instance, please let me know.

That section is intended to be the reference for that.  Will update it in today’s release.

There is also configuration that uses AWS EKS/K8s/possibly Terraform (?), it is located in another repository (https://github.com/ietf-ribose/bibxml-infrastructure/). It is maintained by a colleague, but I did not do a close audit. For my part as BibXML core developer I try to guarantee the approaches covered in this repository only (i.e., via Docker/Docker Compose, no EKS/K8s).

**Comment by strogonoff** [comment]
That sentence is supposed to say:

> The supported method of scaling is via increasing the number of running containers.

In other words, for the “web” service, there should be one Hypercorn worker within a container, but there can be any number of containers.

That said, it is important that Prometheus instance is aware of all containers, if you use Prometheus. Every running container must be scraped for metrics to ensure metrics are accurate. (Otherwise, if e.g. an RFC request is load-balanced to web container B, but Prometheus only gets metrics from web container A, then Prometheus will not learn about that request.)

Meanwhile, for the “celery” service, neither workers nor containers should be scaled.

**Comment by strogonoff** [comment]
(https://github.com/ietf-ribose/bibxml-service/commit/9e523cc916bfe3f48f5e95db55c4e88553621cdd)

**Comment by rjsparks** [comment]
A lot of what is in that last comment should actually be in the documentation. Yes, we will use prometheus. 
There are links at the top of the document that do not resolve.

Overall, as currently written, this page feels more as notes to someone who already understands the deployment rather than instructions to an operator unfamiliar with the project for how to deploy. Please adjust it (or build another page) focusing on that audience.

**Comment by strogonoff** [comment]
> Overall, as currently written, this page feels more as notes to someone who already understands the deployment rather than instructions to an operator unfamiliar with the project for how to deploy.

Originally, it was not given what the exact preferred way of operating the service will be, the requirement I was going off of is that it must be delivered as a set of Docker containers. Thus, the goal of the documentation was to keep it open as to how these containers can be run but provide advice useful for any environment (not tying to any particular provider or deployment method).

As a side note, the container reference part of documentation may be helpful. It breaks down the individual sub-services that comprise BibXML service. Each service is a Docker container specified in the Compose file, and these containers can be run in whichever preferable way of running containers (as long as the containers can talk to each other, which Docker Compose ensures they can).

I’ll to add a section that clarifies this and describes in a bit more detail one possible way of deploying the service.

> A lot of what is in that last comment should actually be in the documentation. Yes, we will use prometheus.

That part is already [in documentation](https://dev.bibxml.org/static/docs/howto/run-in-production.html#scaling) in a highlighted admonition block, I sort of paraphrased it in my comment.

**Comment by strogonoff** [comment]
I have updated production documentation as follows:

- https://dev.bibxml.org/static/docs/howto/run-in-production.html is now a proper how-to describing a minimal production setup guide, as it should’ve been.
- https://dev.bibxml.org/static/docs/topics/production-setup.html covers various aspects of production setup.
