### ISSUE TITLE
Switch to `mozilla-django-oidc`

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#147]
If it is well-maintained and works out of the box with Datatracker, it should be a less-code option.

**Comment by strogonoff** [comment]
@rjsparks I understand that switching to an OIDC library would be preferable in long term.

1. Would you say `mozilla-django-oidc` is a sound option?
2. If yes, would you say switching to it is a pre-requisite to delivery and delay will be justified? I expect it shouldn’t take more than 2 days to refactor `datatracker.oauth` module to use Mozilla’s OIDC library.

**Comment by rjsparks** [comment]
yes, this is a good change to make and taking an extra couple of days is fine.

**Comment by strogonoff** [comment]
I start to believe that switching to Mozilla’s OIDC library unnecessarily increases complexity. The library requires using Django’s authentication system, which brings no real benefit while increasing complexity (and I believe somewhat violates our design goal of keeping PostgreSQL data ephemeral, as it would start keeping user data in a PostgreSQL table).

In theory, the library allows avoiding Django’s user mechanism by providing a custom backend implementation, but its documentation is very sparse. I’m looking into that.

**Comment by rjsparks** [comment]
That moves this into "more than a couple of days" territory I think? Since you appear to have solved the issue with the code you have, we should let this rest. We'll address it later.

**Comment by strogonoff** [comment]
Yes, it would be a bit longer… And I think it would save complexity if future uses for authentication are better understood before continuing. The existing issues were addressed, but I’ll leave this issue open since the case for switching to third-party implementation of OIDC layer still exists.

**Comment by ronaldtse** [comment]
Thanks @rjsparks for understanding. I'd just like to clarify a bit of what @strogonoff meant: the BibXML service today does not need Django's authentication system because "authentication" is fully delegated to datatracker. In order to enable Django's authentication system, it would require the BibXML service to maintain a persistent database -- which we do not have a need for right now.

**Comment by rjsparks** [comment]
yes, I followed, and I think we should stay with what is currently coded for now. This issue can be closed.

**Comment by ronaldtse** [comment]
Thank you @rjsparks !

**Comment by strogonoff** [comment]
@rjsparks Thus it is no longer necessary to allow redirecting to localhost for these OAuth credentials… That setup ended up for nothing, sorry.

**Comment by rjsparks** [comment]
no big deal - thanks for letting me know it can be taken out.
