### ISSUE TITLE
Implement legacy path pattern: Misc collection (`bibxml2`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#15]
Misc collection (W3C, ISO, ITU, ANSI, FIPS, CCITT [previous name of ITU], IEEE, OASIS, PKCS) (`bibxml2`)
* (previous location) http://xml2rfc.tools.ietf.org/public/rfc/bibxml2/

Legacy pattern(s) to implement:
* We probably have to do this with a static map. This collection is not going to change moving forward.

We need to parse the pattern to return the appropriate BibXML content.

**Comment by ronaldtse** [comment]
@strogonoff the misc dataset is now indexed and available.

**Comment by strogonoff** [comment]
Report for all xml2rfc paths under `bibxml2`/misc: [bibxml2-report.zip](https://github.com/ietf-ribose/bibxml-service/files/8984544/bibxml2-report.zip)

Paths work, but see also #222 for some diff anomalies.
