### ISSUE TITLE
As-built description or diagram of what the service relies on an how it is maintained

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#156]
(With thanks for the recent changes at #146)

Please add a short 'as-built' description to the docs about what the service relies on for data, where that is (e.g. github repos) and what updates that information.

If that's present already, provide a link please (and make it easier to find).

**Comment by strogonoff** [comment]
@rjsparks At documentation root (e.g., https://dev.bibxml.org/static/docs/index.html) there is a link “Bibliographic data sourcing”, which leads to https://dev.bibxml.org/static/docs/topics/sourcing.html. Does that provide the information required?

The documentation may be a bit verbose as it tries to cover multiple audiences (developers, operators, management to a degree).

**Comment by rjsparks** [comment]
One item that's not easily found (let me know if I'm just not seeing it) is the answer to
'What are these "tools outside of BibXML service" and where are they running?' when reading this paragraph.
>Internal sources are under IETF control, and are maintained as Git repositories with Relaton and BibXML bibliographic data serialized into YAML/XML files under data/ within repository root. They are periodically updated by tools outside of BibXML service

**Comment by strogonoff** [comment]
> 'What are these "tools outside of BibXML service" and where are they running?' when reading this paragraph.

I see. I didn’t want BibXML service’s own docs to go into data source implementation, they are a separate component and BibXML service’s docs shouldn’t be outdated by a change in how data is sourced (I think there may be a line drawn somewhere between some overall deliverable handoff document describing the whole infrastructure, and BibXML service’s own dev/ops Sphinx-based docs which I’d rather keep focused on the service itself), but it’s fair enough that service docs should at least point the reader in the right direction. Will update them.

From what I know off the top of my head, those tools are defined as GitHub Action workflows within those same data source repositories (and thus they run on GHA CI); and the authoritative source parsing logic used by those workflows is in turn defined in some Ruby gems.

**Comment by strogonoff** [comment]
Added a documentation section with dependency overview (source: https://github.com/ietf-ribose/bibxml-service/blob/main/docs/topics/architecture.rst), pending deployment.

**Comment by strogonoff** [comment]
Now available at https://dev.bibxml.org/static/docs/topics/architecture.html.
