### ISSUE TITLE
Return 404 for versioned I-D xml2rfc-style paths

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#157]
Based on https://github.com/ietf-ribose/relaton-data-ids/issues/6#issuecomment-1047774208

**Comment by ronaldtse** [comment]
Specification:

Correct and should continue working:
* Unversioned I-D has path pattern: `reference.I-D.xxx.xml`
* Versioned I-D has path pattern: `reference.I-D.draft-xxx-nn.xml`

In the following cases, the path should return 404:
* Unversioned I-D has path pattern: `reference.I-D.draft-xxx.xml`
* Versioned I-D has path pattern: `reference.I-D.xxx-nn.xml`

This change ONLY applies to I-Ds.

**Comment by strogonoff** [comment]
Yes, that’s the understanding

**Comment by strogonoff** [comment]
For the sake of posterity, the existing logic was based on [this requirement](https://github.com/ietf-ribose/bibxml-service/issues/13):

> Pattern 2: http://xml2rfc.ietf.org/public/rfc/bibxml-ids/reference.I-D.draft-example-name-99.xml

and was intentionally designed to handle both versioned and unversioned variants as follows:

https://github.com/ietf-ribose/bibxml-service/blob/a99c2d7db091e17cbdc7903f80ce417bb14c57dd/xml2rfc_compat/fetchers.py#L58-L123

**Comment by strogonoff** [comment]
New behavior described below.

No change:

- `/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML
- `/public/rfc/bibxml-ids/reference.draft-weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML
- `/public/rfc/bibxml-ids/reference.I-D.draft-weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML 
 
Changed:

- `/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9-00.xml` returns

  > {"error": {"message": "Error resolving bibliographic item. Tried methods: auto (internet_drafts): not found (Versioned I-D references are not supported), fallback (): not indexed"}} 

Conflict:

- `/public/rfc/bibxml-ids/reference.I-D.draft-weis-gdoi-iec62351-9-00.xml` *returns fallback XML* because this path exists: https://github.com/ietf-ribose/bibxml-data-archive/blob/main/bibxml3/reference.I-D.draft-weis-gdoi-iec62351-9-00.xml

To make the last instance return 404, bibxml-data-archive should not contain a versioned reference.

**Comment by ronaldtse** [comment]
> New behavior (in effect after next version is deployed) described below.
> 
> No change:
> 
> * `/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML

This is correct.

> * `/public/rfc/bibxml-ids/reference.draft-weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML

* `/public/rfc/bibxml-ids/reference.draft-weis-gdoi-iec62351-9.xml` leads to an unversioned I-D, and should return 404, as per "Unversioned I-D has path `pattern: reference.I-D.draft-xxx.xml`"

> * `/public/rfc/bibxml-ids/reference.I-D.draft-weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML

* `/public/rfc/bibxml-ids/reference.I-D.draft-weis-gdoi-iec62351-9.xml` leads to an unversioned I-D,  and should return 404, as per "Unversioned I-D has path `pattern: reference.I-D.draft-xxx.xml`"

> Changed:
> 
> * `/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9-00.xml` returns
>   > {"error": {"message": "Error resolving bibliographic item. Tried methods: auto (internet_drafts): not found (Versioned I-D references are not supported), fallback (): not indexed"}}

Correct.

> Conflict:
> 
> * `/public/rfc/bibxml-ids/reference.I-D.draft-weis-gdoi-iec62351-9-00.xml` _returns fallback XML_ because this path exists: https://github.com/ietf-ribose/bibxml-data-archive/blob/main/bibxml3/reference.I-D.draft-weis-gdoi-iec62351-9-00.xml

This should not be marked as a conflict, and should be marked as correct.

As described earlier, the versioned I-D has path pattern `reference.I-D.draft-xxx-nn.xml`.

**Comment by ronaldtse** [comment]
> For the sake of posterity, the existing logic was based on [this requirement](https://github.com/ietf-ribose/bibxml-service/issues/13):
> 
> > Pattern 2: http://xml2rfc.ietf.org/public/rfc/bibxml-ids/reference.I-D.draft-example-name-99.xml
> 
> and was intentionally designed to handle any combination of identifier with/without `draft-` prefix and with/without trailing version:

Fully understand. It's just that @TonyLHansen has clarified, after the resolver was completed, that the implementation should now only accept the two described patterns and treat the others as unacceptable. So we have to adjust the resolving mechanism. Thanks!

**Comment by strogonoff** [comment]
@ronaldtse I see, apparently I have failed to read the spec carefully. Updated behavior is this:

- `/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9.xml` returns Relaton-sourced XML

- `/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9-00.xml` returns this:

  > {"error": {"message": "Error resolving bibliographic item. Tried methods: auto (internet_drafts): not found (unsupported xml2rfc-style I-D reference: possibly missing I-D prefix or unexpected draft- prefix and trailing version combination), fallback (): not indexed"}}

- `/public/rfc/bibxml-ids/reference.draft-weis-gdoi-iec62351-9.xml` returns the same error message as above.

- `/public/rfc/bibxml-ids/reference.I-D.draft-weis-gdoi-iec62351-9-00.xml` returns Relaton-sourced XML.

**Comment by strogonoff** [comment]
There is an additional fix to be implemented, let me update this issue before closing.

**Comment by strogonoff** [comment]
Nope, all good.

Logic for validating given path: https://github.com/ietf-ribose/bibxml-service/blob/5a069257321652b8acd810e8ff28a89d1a4829d1/xml2rfc_compat/fetchers.py#L82-L94

If path contains a trailing version, our docid lookup will only match the document with given version, otherwise we will get all documents reverse-sorted by draft version number, of which we’ll use the first one (largest version number):

https://github.com/ietf-ribose/bibxml-service/blob/5a069257321652b8acd810e8ff28a89d1a4829d1/xml2rfc_compat/fetchers.py#L102-L118

**Comment by strogonoff** [comment]
Looks like it’s working as expected now, closing.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Comment by TonyLHansen** [comment]
I have a problem with one of the examples above that doesn't match the agreed-to patterns:

/public/rfc/bibxml-ids/reference.draft-weis-gdoi-iec62351-9.xml

This doesn't have the "I-D" in it. It also has "draft-" without the "-nn" at the end.

Is this example being accepted erroneously?

**Comment by ronaldtse** [comment]
@TonyLHansen sorry for the confusion in general with this issue.

I believe as @strogonoff stated:
> /public/rfc/bibxml-ids/reference.draft-weis-gdoi-iec62351-9.xml returns the same error message as above.

This path is not accepted.

**Comment by ronaldtse** [comment]
Thank you @TonyLHansen for the patience!
