### ISSUE TITLE
Document Relaton source compilation process

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#158]
Currently, BibXML service’s Python/Django project documentation [explains](https://dev.bibxml.org/static/docs/topics/sourcing.html#internal-sources) how it is associated with indexed Relaton bibliographic data source repositories. However, it does not go in detail as to how those sources are obtained.

Per Robert’s [request](https://github.com/ietf-ribose/bibxml-service/issues/156#issuecomment-1079018626), I want to make it easier to discover that information, but currently `relaton-data-*` datasets do not have in-depth docs or READMEs of their own.

Questions:

- Should we add documentation to Relaton data repositories? Perhaps we can update repository data generation code in a generalized way to avoid duplicating common descriptions.
- Alternatively, is there a link somewhere else which explains how sources are compiled and which I can use in documentation to direct the reader for more specific information on the topic?

cc @ronaldtse

**Comment by ronaldtse** [comment]
> Should we add documentation to Relaton data repositories? Perhaps we can update repository data generation code in a generalized way to avoid duplicating common descriptions.
> Alternatively, is there a link somewhere else which explains how sources are compiled and which I can use in documentation to direct the reader for more specific information on the topic?

I prefer us not to keep instructions in the data repositories because they are meant for just data. How about we create a few new document pages that describes how the process works? It will have to be jointly done by you and @andrew2net .

**Comment by strogonoff** [comment]
1. I am fine if docs are hosted elsewhere, as long as it will be reliably available and I can provide a clear link in the docs
2. I have zero knowledge of how data sources are put together, so I won’t be able to substantially contribute to authoring or review except for proofreading and structuring Andrew’s work

**Comment by strogonoff** [comment]
Sources are documented in Wiki (https://github.com/ietf-ribose/bibxml-service/wiki/Relaton-sources), and a diagram is provided in documentation under Architecture topic (pending deployment).
