### ISSUE TITLE
GHA workflow fails, it’s unclear if deployment works

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#160]
https://github.com/ietf-ribose/bibxml-service/runs/5735494979?check_suite_focus=true

Not sure if a problem with GHA or our logic…

**Comment by ronaldtse** [comment]
@kwkwan can you please help check why deployment failed? Thanks!

**Comment by kwkwan** [comment]
I think it is due to the deletion of the db-migration job when I test the setup of new environment variables before.  I have re-created the job and the workflow action can be re-run successfully.

https://github.com/ietf-ribose/bibxml-service/actions/runs/2057961430

**Comment by strogonoff** [comment]
GHA succeeded, thanks!
