### ISSUE TITLE
Support custom anchor specification "?anchor=EXAMPLE" in BibXML Service APIs

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#163]
From @strogonoff :

Next version uses the following logic:

* Take either given `anchor` GET parameter or docid with `scope=anchor` (if any) as anchor
* Return `reference.<anchor>.<serialization format>` as filename in the Content-Disposition header, so that it’s suggested to the user as default filename

From @TonyLHansen :

Both the current bibxml-doi and bibxml-iana support "?anchor=EXAMPLE" to override the anchor value that is returned.

This should eventually be extended to all of the bibxml-xyz.

See the web page [https://xml2rfc.tools.ietf.org/](https://xml2rfc.tools.ietf.org/) for more info.

_Originally posted in https://github.com/ietf-ribose/bibxml-service/issues/150#issuecomment-1086645561_

**Comment by strogonoff** [comment]
@ronaldtse I have stated multiple times over past weeks that this is exactly how it works :) See OpenAPI specification for details:  https://dev.bibxml.org/api/v1/#operation/getBibItemByDocId

**Comment by strogonoff** [comment]
Unless you mean this is about the xml2rfc compatibility API. Which I don’t think is the case (why would we spend time getting “anchor” attribute right if we could simply let requester set it, like with the main API).

**Comment by ronaldtse** [comment]
Not about compatibility. Just wanted to be sure we have this documented that a request can request for an anchor of choice. Thanks.

**Comment by strogonoff** [comment]
Okay. Yes, it’s documented and mentioned a few times in this repository in my responses to issue threads regarding `anchor` attribute behavior.

**Comment by TonyLHansen** [comment]
If the compatibility API (the drop-in replacement for the current URLs) supports anchor=EXAMPLE across the board, that's great!
However, I don't see mention of anchor=EXAMPLE on <[openapi_spec_legacy](https://dev.bibxml.org/api-spec/openapi_spec_legacy/)>. Am I looking in the wrong place? If not, I think this needs to be re-opened.

**Comment by strogonoff** [comment]
No, compat API doesn’t recognize any GET parameters actually. Not a big change to extend anchor support to that.

Does this mean we can assume all xml2rfc-style XML API consumers will specify anchor, or we need to maintain logic for providing suitable anchors if none is given?

**Comment by TonyLHansen** [comment]
Here are excerpts of the code used for the current bibxml-doi & bibxml-iana:

```
	cgi_anchor = cgi_arguments["anchor"].value

        self.replacement_anchor = self.munge_anchor(cgi_anchor)

	""" If there is a replacement anchor, use that for the embedded anchor within the text. """
        f"anchor='{self.replacement_anchor}"

    def munge_anchor(self, anchor):
        """ Make sure that an anchor is "safe" by changing to uppercase and remove non-[A-Z0-9_-]. """
        if anchor:
            anchor = re.sub(r"[^-A-Z0-9_]]", "", anchor.upper())
        return anchor

```

**Comment by TonyLHansen** [comment]
no, the code shows is an excerpt, as stated. There's an if I didn't show -- if the anchor parameter isn't given, it uses the one normally generated.

**Comment by strogonoff** [comment]
xml2rfc paths now handle `anchor` parameter, example:

- https://dev.bibxml.org/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9.xml
- https://dev.bibxml.org/public/rfc/bibxml-ids/reference.I-D.weis-gdoi-iec62351-9.xml?anchor=foobar

@TonyLHansen, regarding munging the anchor, I see that in reference data it isn’t always uppercase, e.g.: http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.agl-tls-chacha20poly1305.xml. Is it needed? Should it happen on per-dataset basis or across any xml2rfc path, meaning it would be different at least for documents under `bibxml3`?

**Comment by strogonoff** [comment]
Also, note that the `anchor` specified in GET query will not have effect on `<reference>` elements nested within a `<referencegroup>` (relevant for `rfcsubseries` and possibly more datasets later).

**Comment by ronaldtse** [comment]
Thank you @strogonoff ! Quick question -- does this new behavior also apply to non-IETF bibliographic items, e.g. NIST? (I hope it does 😉 )
