### ISSUE TITLE
source repositories organization is hardcoded

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#166]
The ietf-ribose organization is hardcoded at
https://github.com/ietf-ribose/bibxml-service/blob/efff45a5043ba895d44e8eb6d74a7ce5ee712362/main/sources.py#L89

Is there an expectation that these repositories will live in that organization in the long-term, or will it be reasonable to move them into an ietf managed organization as the project completes? If the latter, this string should probably move to configuration.

**Comment by strogonoff** [comment]
Sources are fully configurable, both repository URL and branch name. `ietf-ribose/relaton-data-<dataset ID>` is fallback/default used when repository URL is not specified for a Relaton dataset. But it’s not a problem to make the fallback configurable as well.

**Comment by strogonoff** [comment]
Update is being deployed with new settings that define fallback repository information: https://github.com/ietf-ribose/bibxml-service/blob/c373a410ca353b26b487cf5c28f50deb3d1c2658/bibxml/settings.py#L401-L418
