### ISSUE TITLE
Implement legacy path pattern: 3GPP (`bibxml5`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#17]
3GPP (bibxml5)
* (previous location) http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/
* Pattern 1: http://xml2rfc.ietf.org/public/rfc/bibxml5/reference.SDO-3GPP.55.205.xml
* Pattern 2: http://xml2rfc.ietf.org/public/rfc/bibxml-3gpp/reference.SDO-3GPP.55.205.xml
* Pattern 3: http://xml2rfc.ietf.org/public/rfc/bibxml-3gpp/reference.3GPP.55.205.xml

Legacy pattern(s) to implement:
* Pattern 1: https://{hostname}/public/rfc/bibxml5/reference.SDO-3GPP.{docid}.xml
* Pattern 2: https://{hostname}/public/rfc/bibxml-3gpp/reference.SDO-3GPP.{docid}.xml
* Pattern 3: https://{hostname}/public/rfc/bibxml-3gpp/reference.3GPP.{docid}.xml

3GPP documents are of the pattern like:
* 00.02U
* 55.205
* 02.06dcs
* 29.998-04-1

We need to parse the pattern to return the appropriate BibXML content.

**Comment by ronaldtse** [comment]
@strogonoff the dataset is now ready at https://github.com/ietf-ribose/relaton-data-3gpp

**Comment by ronaldtse** [comment]
This task when complete will close #35 also.

**Comment by strogonoff** [comment]
Attaching a report for xml2rfc-style paths for `bibxml5` (based on entries in bibxml-data-archive):
[bibxml5-report.zip](https://github.com/ietf-ribose/bibxml-service/files/8984252/bibxml5-report.zip)
