### ISSUE TITLE
xml2rfc paths do not resolve for rfcsubseries

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#170]
This change 18 days ago:

https://github.com/ietf-ribose/relaton-data-rfcsubseries/blame/main/data/BCP0048.yaml#L11

broke the fetcher function that relied on identifier’s number part to be exactly `0048` and _not_ `48`. This causes any xml2rfc path for rfcsubseries to fall back to xml2rfc original data.

Changing Relaton source generation without confirmation ahead of time tends to cause these issues.

**Comment by strogonoff** [comment]
I am fixing this by updating resolver function, but any further change can break it again.

**Comment by ronaldtse** [comment]
@strogonoff if this is done can we close it? Thanks.

**Comment by strogonoff** [comment]
@ronaldtse I updated the codebase for now, but the deeper issue is that these changes happen in Relaton sources and they break BibXML service without warning

**Comment by ronaldtse** [comment]
There needs to be a mechanism in dealing with those changes, i.e., better change management in the data schema and the values provided by Relaton. There is still some uncertainty in the `docid`s in Relaton but I think we will resolve it with the unified `docid` approach.

Then let's close this and use a new issue for tracking that. Thanks.
