### ISSUE TITLE
xml2rfc path resolution checker tool is slow

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#174]
The tool is slow, especially for large datasets.

The HTTP request to load enough to start executing JS takes **more than 8 minutes** (https://dev.bibxml.org/management/xml2rfc-compat/bibxml-nist/reference.NIST.AMS.100-32.xml/):

<img width="986" alt="Screenshot 2022-04-13 at 9 23 12 PM" src="https://user-images.githubusercontent.com/292959/163204619-700f5035-b02a-464c-a47d-d6b6782c32f0.png">

However, on this page it takes **about 3 seconds** (https://bibxml-dev.strogonoff.name/management/xml2rfc-compat/bibxml-nist/reference.NIST.AMS.100-12.xml/, password `test2`):

<img width="840" alt="Screenshot 2022-04-13 at 9 22 24 PM" src="https://user-images.githubusercontent.com/292959/163202453-7d807554-daa1-4782-a767-5a12094391ed.png">

It’s the same dataset. Selected item doesn’t have effect on performance. Site displays wrong version on second link, but it runs the latest codebase (before rebuilding the image, I pulled Git repo but forgot to pull the tags).

@ronaldtse, @kwkwan do you observe similar disparity, or is it just my machine?

If you see it too, maybe we could try identify what’s causing it. Page size is about 6–7 MB, so it shouldn’t be a problem to transfer. Could it be that dev.bibxml.org is being hit by external traffic enough to slow it down so much? Or is there another networking limitation in our k8s setup that slows the service down?

The tool can be rearchitected to work offline, but if its slowness is only a result of our k8s setup, then it may be better we fix our setup instead🤔

(NOTE: Search/filter functionality is tracked separately in #173. I want to clarify this question about basic architecture before fully implementing search.)

**Comment by kwkwan** [comment]
Hi @strogonoff, I have tested the link (https://dev.bibxml.org/management/xml2rfc-compat/bibxml-nist/reference.NIST.AMS.100-32.xml/) on my computer.  It takes 2-3 seconds to load the xml.

<img width="1495" alt="Screenshot 2022-04-14 at 8 43 58 AM" src="https://user-images.githubusercontent.com/29566367/163292403-91c9be85-f6c3-414b-affd-e5f431c0dbcd.png">

Not sure why it takes 8 minutes to load.  I will spend some time to investigate the problem.

**Comment by strogonoff** [comment]
> Hi @strogonoff, I have tested the link (https://dev.bibxml.org/management/xml2rfc-compat/bibxml-nist/reference.NIST.AMS.100-32.xml/) on my computer. It takes 2-3 seconds to load the xml.
> 
> <img alt="Screenshot 2022-04-14 at 8 43 58 AM" width="1495" src="https://user-images.githubusercontent.com/29566367/163292403-91c9be85-f6c3-414b-affd-e5f431c0dbcd.png">
> 
> Not sure why it takes 8 minutes to load. I will spend some time to investigate the problem.

Really? Let me check more times. Could it be caused by geographic location of servers, so it works fast for you but not for me?

**Comment by strogonoff** [comment]
It’s still very slow for me. Different every time, now it’s not 8 minutes but probably around 15 seconds, still much slower than my deployment. (My server is in Germany, and I am in SE Asia, so it’s clearly not because of geography.)

**Comment by strogonoff** [comment]
Actually, it starts working faster after browsing around a bit. I wonder if our K8s setup is influenced by cold start-ups, like Lambda.
