### ISSUE TITLE
Incorrect references from bibxml5 referring to 3GPP TSes instead of TRs

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#176]
In #135 we have discovered that several 3GPP references currently provided in bibxml5 refer to the wrong document type from the 3GPP. They refer to "TS" (3GPP Technical Specification) instead of "TR" (3GPP Technical Report).

I wasn't able to locate the exact semantic differences from the 3GPP website, but this website says:
https://www.3glteinfo.com/how-3gpp-specifications-numbering-works/

> ## TR and TS – Differences
> 3gpp specifications are broadly divided into two main categories:
> 
> TR – Technical Report
> TS – Technical Specification
>
> Technical Reports are again of two classes:
> 
> Those intended to be transposed and issued by the Organizational Partners as their own publications. These usually have specification numbers of the form XX.9XX.
> Those documents which are not intended for publication but are just 3GPP internal working documents. For example, feasibility study documents. These have specifation numbers of the form XX.8XX ( e.g. fesebility study reports) or sometime they carry a number 30.xxx of 50.xxx (planning and scheduling).
> Apart from these all other specifications are Technical Specifications.

On verification, according to [3GPP TR 21.900](https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=555) "Technical Specification Group working methods", 

> 4.0	Numbering scheme

> The specifications shall be numbered according to the following scheme:
> 3GPP TS aa.bbb	(for Technical Specifications); or
> 3GPP TR aa.bbb	(for Technical Reports).
> ...
> 
> Range | Use | Remarks
> --|--|--
> aa.8bb | Technical Reports not intended for publication. | Working documents of 3GPP Groups not intended to be transposed into publications by the Partner Organizations.
> aa.9bb | Technical Reports intended for publication. | As distinct from those of the aa.8bb series.
> 

It looks like TRs are only issued for the cases of 6.4.4 "Early implementation" and "Study Items (SI)", which are "type of Work Item which will conduct feasibility studies and will result in a Technical Report".

The following list of items are TRs, not TSes, as claimed by the original bibxml5 dataset:

* TS 23.884 0.1.0 => 3GPP TR 23.884:Rel-9/0.1.0 (http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.23.884.xml)
* TS 29.839 11.0.0 => 3GPP TR 29.839:Rel-11/11.0.0 (http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.29.839.xml)
* TS 26.905 11.0.0 => 3GPP TR 26.905:Rel-11/11.0.0 (http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.26.905.xml)
* TS 26.906 0.2.0 => 3GPP TR 26.906:Rel-12/0.2.0 (http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.26.906.xml)
* TS 29.949 0.1.0 => 3GPP TR 29.949:Rel-12/0.1.0 (http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.29.949.xml)

```yaml
data/TR_23.884_REL-9_0.1.0.yaml:id: 3GPPTR23.884-Rel-9/0.1.0
data/TR_23.884_REL-9_0.1.0.yaml:- content: http://www.3gpp.org/ftp/Specs/archive/23_series/23.884/23884-010.zip
data/TR_23.884_REL-9_0.1.0.yaml:- id: 3GPP TR 23.884:Rel-9/0.1.0
data/TR_23.884_REL-9_0.1.0.yaml:docnumber: TR 23.884:Rel-9/0.1.0
data/TR_29.839_REL-11_11.0.0.yaml:id: 3GPPTR29.839-Rel-11/11.0.0
data/TR_29.839_REL-11_11.0.0.yaml:- content: http://www.3gpp.org/ftp/Specs/archive/29_series/29.839/29839-b00.zip
data/TR_29.839_REL-11_11.0.0.yaml:- id: 3GPP TR 29.839:Rel-11/11.0.0
data/TR_29.839_REL-11_11.0.0.yaml:docnumber: TR 29.839:Rel-11/11.0.0
data/TR_26.905_REL-11_11.0.0.yaml:id: 3GPPTR26.905-Rel-11/11.0.0
data/TR_26.905_REL-11_11.0.0.yaml:- content: http://www.3gpp.org/ftp/Specs/archive/26_series/26.905/26905-b00.zip
data/TR_26.905_REL-11_11.0.0.yaml:- id: 3GPP TR 26.905:Rel-11/11.0.0
data/TR_26.905_REL-11_11.0.0.yaml:docnumber: TR 26.905:Rel-11/11.0.0
data/TR_26.906_REL-12_0.2.0.yaml:id: 3GPPTR26.906-Rel-12/0.2.0
data/TR_26.906_REL-12_0.2.0.yaml:- content: http://www.3gpp.org/ftp/Specs/archive/26_series/26.906/26906-020.zip
data/TR_26.906_REL-12_0.2.0.yaml:- id: 3GPP TR 26.906:Rel-12/0.2.0
data/TR_26.906_REL-12_0.2.0.yaml:docnumber: TR 26.906:Rel-12/0.2.0
data/TR_29.949_REL-12_0.1.0.yaml:id: 3GPPTR29.949-Rel-12/0.1.0
data/TR_29.949_REL-12_0.1.0.yaml:- content: http://www.3gpp.org/ftp/Specs/archive/29_series/29.949/29949-010.zip
data/TR_29.949_REL-12_0.1.0.yaml:- id: 3GPP TR 29.949:Rel-12/0.1.0
data/TR_29.949_REL-12_0.1.0.yaml:docnumber: TR 29.949:Rel-12/0.1.0
```

@TonyLHansen @rjsparks can we confirm that we can change the mapping of these TSes to the correct TRs?

**Comment by zaheduzzaman** [comment]
I have checked in 3GPP 23 (https://www.3gpp.org/DynaReport/23-series.htm), 26 ( https://www.3gpp.org/DynaReport/26-series.htm) and 29 (https://www.3gpp.org/dynareport/29-series.htm) series specification list and can confirm that those are actually TR not TS.

**Comment by ronaldtse** [comment]
Thanks @zaheduzzaman @rjsparks !

**Comment by ronaldtse** [comment]
Closing as it has been done in https://github.com/ietf-ribose/bibxml-service/issues/135#issuecomment-1102637245.
