### ISSUE TITLE
Link to source repository

### ISSUE THREAD

**Issue by martinthomson** [ietf-ribose/bibxml-service#190]
The main page shows a version number.  Could this link to the source?  (Assuming this is the right place to ask this question, it was hard to find; a link would make it easier.)

**Comment by strogonoff** [comment]
It’s possible.

Although if we’re speaking about encouraging issue reports it could make more sense to add a more prominent call to action that links directly to this issues section instead.

For the record,

- [Developer’s documentation](https://dev.bibxml.org/static/docs/index.html) links to the repository
- For issues regarding bibliographic data, bibliographic item’s detail page links to its respective data repository’s issue section
