### ISSUE TITLE
Updated `relaton-data-ids` source breaks assumptions about data; causes weird GUI

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#192]
(I’m filing this here rather than in `relaton-data-ids`, but there’re multiple ways to resolve this some of which require changing data source and others require changes to BibXML service.)

1. This is how I-D pages look now. This is caused by the new I-D “series containers” (e.g., https://github.com/ietf-ribose/relaton-data-ids/blob/main/data/draft-ietf-sigtran-iua.yaml):

   * Listing page: <img width="1264" alt="Screenshot 2022-04-30 at 9 55 01 PM" src="https://user-images.githubusercontent.com/292959/166110634-00ff09b2-f9db-49c0-99a0-25956fea0e50.png">
   * Detail page: <img width="1264" alt="Screenshot 2022-04-30 at 9 55 06 PM" src="https://user-images.githubusercontent.com/292959/166110621-2f79a411-387d-4087-908b-2ad8d926deb8.png">

2. In addition, these I-D series containers are not well-searchable, because they don’t really contain any data such as titles.

3. For an example of existing series containers that seem to work well with BibXML service so far, see RFC subseries (e.g., https://github.com/ietf-ribose/relaton-data-rfcsubseries/blob/main/data/BCP0004.yaml, note how each relation provides bibliographic item data, not just formatted ref, and some of that data like titles is used when rendering the series container):  <img width="1264" alt="Screenshot 2022-04-30 at 10 06 11 PM" src="https://user-images.githubusercontent.com/292959/166111036-4b3e265e-62a7-4b63-8bb1-6e428625c7ed.png">

Ways to address that I have in mind:

- `relaton-data-ids` can be updated to include full relations, following the RFC subseries example. This would make it “just work” without changes to BibXML service codebase. I’m not sure about any associated downsides[0].
- The GUI can be updated to show `formattedref` document ID and relation IDs. This is low effort but means no titles will be visible, unlike RFC subseries. This might hurt legibility a bit (but not so much, since I-D IDs are fairly readable).
- The GUI can be updated to fetch relation data. This should not be too difficult, and with some effort it should be possible to fetch all related document titles in one PostgreSQL query (although the size of it will vary depending on the number of relations). However, it’s *new* functionality—the service until now didn’t have to resolve relations in order to display bibliographic item details—so it might cause a bit of a delay.

(Note to @ronaldtse @andrew2net)

[0] Well, if we reuse the same logic for rendering I-D series containers as for RFC subseries, it’d look weird—since in case of RFC subseries we use contained document titles as part of series title (because the series doesn’t have its own title), but I-D versions have the same titles—however, simple removal of repeating titles from the list should address that.

**Comment by andrew2net** [comment]
> Ways to address that I have in mind:
> 
> * `relaton-data-ids` can be updated to include full relations, following the RFC subseries example. This would make it “just work” without changes to BibXML service codebase. I’m not sure about any associated downsides[0].

@strogonoff I just discovered that the RFC subseries fetches relations metadata from the GitHub mirror of the xml2rfc.tools.ietf.org. So, it seems we should replace the full relations in RFC subseries with formatted refs.

**Comment by strogonoff** [comment]
> I just discovered that the RFC subseries fetches relations metadata from the GitHub mirror of the xml2rfc.tools.ietf.org

I will file a separate issue for that.

**Comment by ronaldtse** [comment]
> So, it seems we should replace the full relations in RFC subseries with formatted refs.

Then can you help do it ASAP? @strogonoff needs that done as IETF is looking to switch the service ASAP.

**Comment by ronaldtse** [comment]
I discussed with @strogonoff and realised that `formattedref` is being used as a "locator" in relations. That is an abuse.

The following must be adhered to:
- `formattedref` is ONLY intended for display
- inside `relations`, we want to locate a resource. The thing that is provided there MUST be an identifier (e.g. docid), not a formattedref. We "may" use a formatted ref if that is the only information we have. However, in this case we have a docid, we must use the docid.

**Comment by strogonoff** [comment]
Thanks for clarification @ronaldtse!

**Comment by andrew2net** [comment]
> > So, it seems we should replace the full relations in RFC subseries with formatted refs.
> 
> Then can you help do it ASAP? @strogonoff needs that done as IETF is looking to switch the service ASAP.

@ronaldtse if we do it then metadata of relations could be fetched only from `relaton-data-rfcs`. We don't have the related documents in `realton-data-rfcsubseries`. Is it ok?

**Comment by strogonoff** [comment]
I think this had been addressed.
