### ISSUE TITLE
Infer metadata by resolving `formattedref` links where possible

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#193]
In Relaton data model, any bibliographic item instance can technically omit all useful metadata fields and be just a `formattedref`, which is a primary document identifier string that can be used to retrieve actual bibliographic data from elsewhere.

In our source data, this is currently the case with at least these:

- `relaton-data-ids` (I-D series containers provide no metadata)
- `relaton-data-rfcsubseries` (each RFC subseries provides full metadata for its relations—for the time being—but not for RFC subseries item itself)

This presents some design issues:

- In API output, I believe the service would be expected to always return expanded descriptions instead of `formattedref` links in relations.
- In GUI, the service could format relations as hyperlinks. However, if item _itself_ is a `formattedref` and lacks other metadata, it could not be displayed to the user in an acceptable way. (See #192.)

Proposing two changes in business logic to address that:

1. Service could dynamically resolve all `formattedref` occurrences in item’s _relations_ by locating relevant documents. This would incur DB hits, but it should be possible to compress into a single query (which admittedly could be large for search results pages with items containing many relations; we could use another caching layer for that if needed).
2. If _item itself_ is a `formattedref` (e.g., a series container with no metadata of its own, [like with `relaton-data-ids` versionless I-D series containers](https://github.com/ietf-ribose/relaton-data-ids/blob/ebeb935f7b67468a8808093cf3e311288a2f48ab/data/draft-3k1n-6tisch-alice0.yaml#L2-L4)), service could “make up” relevant metadata (such as title, authors, etc.) by aggregating bibliographic data of documents linked via “includes” relations.

   Currently, the service does so with RFC subseries—however, `relaton-data-rfcsubseries` contains pre-resolved relations (for now—https://github.com/ietf-ribose/bibxml-service/issues/192#issuecomment-1114204504). The same approach doesn’t work as is for `relaton-data-ids`, since relations also don’t have metadata and must be resolved per previous point.

Cautionary note: `relaton-py`’s BibXML serializer actually uses _absence_ of useful metadata on “series container” items to determine whether to output `<referencegroup>`. This could break that behavior. Presumably, the presence of “includes” relations should be enough to tell serializer that it should be a `<referencegroup>`.

**Comment by ronaldtse** [comment]
Please see https://github.com/ietf-ribose/bibxml-service/issues/192#issuecomment-1119952433 for why formattedref should NOT be used as a locator. formattedref is ONLY suitable for rendering, not locating a resource.

**Comment by strogonoff** [comment]
Thanks @ronaldtse, I see that due to a misunderstanding of Relaton model the problem (and the solution) may be misguided, since `formattedref` is not actually intended as a locator/reference.

It looks like first thing the data sources should be updated to address the breakage in the GUI.

I might close this issue soon, but somewhat related idea may come up (in that there may be incomplete bibitems in some source, and the service could resolve them by docid from another source).

**Comment by andrew2net** [comment]
> In Relaton data model, any bibliographic item instance can technically omit all useful metadata fields and be just a `formattedref`, which is a primary document identifier string that can be used to retrieve actual bibliographic data from elsewhere.

Relaton model requires `title` or `formattedref` to be presented.

> In our source data, this is currently the case with at least these:
> 
> * `relaton-data-ids` (I-D series containers provide no metadata)

The related documents are in the same repository and could be easily found by `formattedref`. I don't think we need to duplicate them in the relation element.

> * `relaton-data-rfcsubseries` (each RFC subseries provides full metadata for its relations—for the time being—but not for RFC subseries item itself)

The rfcsubseries repository doesn't contain the related documents, so I decided to provide relation with full metadata.

> This presents some design issues:
> 
> * In API output, I believe the service would be expected to always return expanded descriptions instead of `formattedref` links in relations.
> * In GUI, the service could format relations as hyperlinks. However, if item _itself_ is a `formattedref` and lacks other metadata, it could not be displayed to the user in an acceptable way. (See [Updated `relaton-data-ids` source breaks assumptions about data; causes weird GUI #192](https://github.com/ietf-ribose/bibxml-service/issues/192).)
> 
> Proposing two changes in business logic to address that:
> 
> 1. Service could dynamically resolve all `formattedref` occurrences in item’s _relations_ by locating relevant documents. This would incur DB hits, but it should be possible to compress into a single query (which admittedly could be large for search results pages with items containing many relations; we could use another caching layer for that if needed).
> 2. If _item itself_ is a `formattedref` (e.g., a series container with no metadata of its own, [like with `relaton-data-ids` versionless I-D series containers](https://github.com/ietf-ribose/relaton-data-ids/blob/ebeb935f7b67468a8808093cf3e311288a2f48ab/data/draft-3k1n-6tisch-alice0.yaml#L2-L4)), service could “make up” relevant metadata (such as title, authors, etc.) by aggregating bibliographic data of documents linked via “includes” relations.

I looked through some contained series and it looks like they have identical titles and abstracts but the authors are different. I think we can provide metadata in I-D series containers if the metadata is identical for all included documents.

>    Currently, the service does so with RFC subseries—however, `relaton-data-rfcsubseries` contains pre-resolved relations (for now—[Updated `relaton-data-ids` source breaks assumptions about data; causes weird GUI #192 (comment)](https://github.com/ietf-ribose/bibxml-service/issues/192#issuecomment-1114204504)). The same approach doesn’t work as is for `relaton-data-ids`, since relations also don’t have metadata and must be resolved per previous point.

As I said the relaton-data-ids contains related documents (I hope so). In other side relaton-data-rfcsubseries contain only bundles of documents so we need to provide metadata inside relation items.

**Comment by strogonoff** [comment]
@andrew2net 

 > Relaton model requires title or formattedref to be presented.

This is changing. They are no longer considered exclusive. `formattedref` is just optional, it does not remove the requirement of `docid` for example.

> The related documents could be easily found by formattedref.  

From Nick’s and Ronald’s words, `formattedref` is not a reliable “link”. Even though I relied on it as a link in BibXML service, it’s not a link. It’s a visual human-readable “cached” representation of bibliographic item.


> The related documents are in the same repository

This should not matter.


So either full docs should be included, or we need a better linking mechanism. (cc @ronaldtse and @opoudjis)

> I looked through some contained series and it looks like they have identical titles and abstracts but the authors are different. <…>

We don’t need to provide all metadata in unversioned I-D containers, just titles and abstracts is enough, or even just titles.

> As I said the relaton-data-ids contains related documents (I hope so). In other side relaton-data-rfcsubseries contain only bundles of documents so we need to provide metadata inside relation items.

Whether the same source contains the items or not shouldn’t be important. The bibitem can be passed through many layers and many components, and the information about which relaton-data repository it was contained originally will be lost, it should not be important.
