### ISSUE TITLE
Update relaton-ietf to stop obtaining information from xml2rfc.ietf.org

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#198]
From @rjsparks :

> At https://github.com/relaton/relaton-data-ietf/blob/master/crawler.rb#L40
> 
> This is scraping the legacy service - is the result still in use anywhere?
> 
> Sometime soon (next two weeks) I plan to cause the 
[xml2rfc.tools.ietf.org/public/rfc](http://xml2rfc.tools.ietf.org/public/rfc) URLs to redirect to the bibxml 
service, and I suspect you don't want to be scraping _that_?
> 
> Do we need to coordinate before we install that redirection?

@andrew2net has been working on this. This was previously being used to fill in the metadata for the `relaton-data-rfcsubseries` dataset, as rfcsubseries themselves do not provide sufficient metadata. The new way is to construct `relaton-data-rfcsubseries` inner RFC data using `relaton-data-rfcs` information.

We have some final steps to take to ensure that the bibliographic data we generate can be properly cross-referenced across datasets, and this is one of the last steps.

This should be done this week, I will post an issue and ping you when done.

**Comment by ronaldtse** [comment]
@andrew2net please help link to the relevant ticket in relaton-ietf. Thanks!

**Comment by strogonoff** [comment]
I believe @andrew2net mentioned that rfcsubseries no longer fetches data from xml2rfc tools, and uses rfc-editor. I think we can close this when Andrew confirms.
