### ISSUE TITLE
Implement legacy path pattern: DOI references (`bibxml7`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#20]
DOI references (bibxml7)
* Pattern 1: http://xml2rfc.tools.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.SP.800-53r5.xml
* Pattern 2: http://xml2rfc.tools.ietf.org/public/rfc/bibxml-doi/reference.DOI.10.6028/NIST.SP.800-53r5.xml

Legacy pattern(s) to implement:
* Pattern 1: http://xml2rfc.tools.ietf.org/public/rfc/bibxml7/reference.DOI.{DOI ID}.xml or .kramdown
* Pattern 2: http://xml2rfc.tools.ietf.org/public/rfc/bibxml-doi/reference.DOI.{DOI ID}.xml or .kramdown

**Comment by strogonoff** [comment]
@ronaldtse

Path of the following format is supported (note: forward slash is quoted for HTTP compatibility):

http://34.229.41.119:8000/doi/DOI.10.6028%252FNIST.SP.800-53r5/

However, `doi2ietf` library fails with an error if XML format is requested. It does succeed in DICT format, which is used by our API endpint—however, data structure is very unRelaton-like so we have not much to show:

http://34.229.41.119:8000/doi/DOI.10.6028%252FNIST.SP.800-53r5/

**Comment by strogonoff** [comment]
Now implemented, integrated with Crossref and works with any DOI: https://dev.bibxml.org/public/rfc/bibxml-doi/reference.DOI.10.6028/NIST.SP.800-53r5.xml (note that slashes are no longer escaped in path).
