### ISSUE TITLE
Add validators to search fieds

### ISSUE THREAD

**Issue by raaaskol** [ietf-ribose/bibxml-service#20]
Add validators to search fields (Quick, Advanced, DOI).

1. Highlight the field if there is no request
2. Show info message  about error.*
3. Search button should be read only if the field is empty **(optional)**

*Text can be found [here](https://github.com/ietf-ribose/bibxml-service/issues/19)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by strogonoff** [comment]
@stefanomunarini I think this is a quick and small task. All search forms technically have one text field and it is always required. Specifying HTML validator would help avoid unnecessary requests and subpar UX with “no query provided” messages

**Comment by strogonoff** [comment]
> @raaaskol @strogonoff added validators (#21) to text fields in the search form. Not sure if I should proceed with adding "info message about error"(2) too, @strogonoff ? Your last comment only specify validators HTML validators to text input fields.

I _believe_ the server-rendered error messages should be that separate issue, and client-side in HTML just having a required validator may be enough? I’ll need to check.
