### ISSUE TITLE
Apply correct mime type for abstracts in DOI responses

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#210]
The text of Work abstracts received from Crossref API may be marked up with JATS XML. We need to detect that and apply appropriate type.

At this moment, when we convert Crossref DOI Work to Relaton bibliographic item, we only fill in the `content` property of the abstract: https://github.com/ietf-ribose/bibxml-service/blob/c9e86a881df6680f9025fd621a4c3a96a2350cd3/doi/crossref.py#L116-L118

However, each abstract also supports `format` property (see [`BibliographicItem.abstract`](https://relaton-py.readthedocs.io/en/latest/ref/models.html#relaton.models.bibdata.BibliographicItem.abstract) and its class inheritance, which aims to comply with [Relaton model](https://github.com/relaton/relaton-models/blob/f3363d495c7da9987fd2eb91a5c958284cfb43c3/models/BibliographicItem.lutaml#L78-L82)).

- [x] Confirm what’s the appropriate MIME type string. (Could be `application/x-jats+xml`, research whether this is correct.)
- [x] Write a function that takes any string and attempts to detect MIME type based on its contents. It must be capable of detecting at least `text/plain`, `text/html`, and whatever is the right MIME type for JATS XML.
- [x] Update handling of abstracts in Crossref DOI Work -> Relaton bibliographic item conversion code (`doi.crossref` module), use the above new function to provide correct `format` value on the abstract.

Once we do this, `relaton-py` can then handle paragraph extraction according to string format (https://github.com/relaton/relaton-py/issues/12).

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/bibxml-service/issues/208#issuecomment-1136917042_

**Comment by strogonoff** [comment]
Upstream https://github.com/relaton/relaton-py/issues/12

**Comment by strogonoff** [comment]
Regarding MIME type:

- https://documentation.cochrane.org/display/API/Review+Document+API#ReviewDocumentAPI-Encodingofresponse uses `application/x-jats+xml`, but it’s very difficult to find any other supporting examples for JATS (it doesn’t seem to be that popular)

@ronaldtse @opoudjis Any objections to assigning the above string as `format` (MIME type) for DOI abstracts that contain JATS XML?

**Comment by strogonoff** [comment]
Regarding detection:

* According to Crossref uploader’s docs, they support JATS and MathML (https://www.crossref.org/documentation/schema-library/metadata-deposit-schema-5-3-1/).

So I suggest we rule out HTML in abstract contents, and just force apply JATS XML type to all abstracts obtained from DOI.

**Comment by ronaldtse** [comment]
I am confused by the comment -- I don't think all DOI abstracts are only either JATS or MathML. At least plain text is supported. 

The MIME type for JATS XML is accurate and fine (no one can read it anyway).

**Comment by ronaldtse** [comment]
Have you checked https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html ?

No one in the right mind uses JATS, especially for abstracts...

**Comment by strogonoff** [comment]
@ronaldtse 

> I am confused by the comment -- I don't think all DOI abstracts are only either JATS or MathML. At least plain text is supported.
> 
> The MIME type for JATS XML is accurate and fine (no one can read it anyway).

A JATS XML string that happens to not contain any tags is indistinguishable from plain text🤔

Frankly, it’s hard to test what they have because most entries don’t have any abstract at all. The only abstract I have seen yet is JATS🤷‍♂️

> Have you checked https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html ?

Following your link I found `abstract` field only defined using JATS. All references to `abstract` point here: https://data.crossref.org/reports/help/schema_doc/5.3.1/JATS-journalpublishing1-3d2-mathml3-elements_xsd.html#abstract

**Comment by strogonoff** [comment]
For now it’s been changed to JATS for all abstracts from Crossref.

**Comment by strogonoff** [comment]
`bibxml` serializer in relaton-py now extracts text from `jats:p` tags as a list of paragraphs converted into `<t>` (https://github.com/relaton/relaton-py/issues/12#issuecomment-1140347166).

**Comment by strogonoff** [comment]
Example: https://dev.bibxml.org/public/rfc/bibxml7/reference.DOI.10.3390/fi11030055.xml
