### ISSUE TITLE
anchor returned for versionless queries should not include version

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#213]
https://bib.ietf.org/public/rfc/bibxml-ids/reference.I-D.iab-xml2rfc.xml returns `anchor="I-D.draft-iab-xml2rfc-04"`. It _should_ return `anchor="I-D.draft-iab-xml2rfc"`. (edit: whoops, not quite right - see below)

The full return follows:
```
<reference target="https://datatracker.ietf.org/api/v1/doc/document/draft-iab-xml2rfc/" anchor="I-D.draft-iab-xml2rfc-04">
<front>
<title>The "xml2rfc" Version 3 Vocabulary</title>
<author fullname="Paul Hoffman"/>
<date year="2016" month="June" day="22"/>
<abstract>
<t>
This document defines the "xml2rfc" version 3 vocabulary: an XML-based language used for writing RFCs and Internet-Drafts. It is heavily derived from the version 2 vocabulary that is also under discussion. This document obsoletes the v2 grammar described in RFC 7749.
</t>
</abstract>
</front>
<seriesInfo name="Internet-Draft" value="draft-iab-xml2rfc-04"/>
</reference>
```

**Comment by rjsparks** [comment]
Actually @reschke points out that the legacy service returns `anchor="I-D.iab-xml2rfc"` (note the elision of draft).

I think this requires a touch at the same place this commit worked on: https://github.com/relaton/relaton-py/commit/96d4de1738203bc373fbef2db37a99c823aa878f

**Comment by rjsparks** [comment]
The anchor needs to match what came in on the legacy URI. The use-case here is in documents - the text in the document will refer to the anchor `I-D.iab-xml2rfc`.

**Comment by strogonoff** [comment]
@rjsparks, I believe this was addressed with the previous release earlier this week, so that unversioned I-D XML response now contains unversioned `anchor` property (returned data *does* represent a particular version of the I-D, just that anchor now doesn’t reflect that): https://dev.bibxml.org/public/rfc/bibxml-ids/reference.I-D.iab-xml2rfc.xml
