### ISSUE TITLE
UI can't export bibxml when the legacy paths can serve it

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#217]
See https://bib.ietf.org/public/rfc/bibxml-w3c/reference.W3C.REC-xmlschema-1-20041028.xml
Then try exporting bibxml from https://bib.ietf.org/get-one/by-docid/?docid=W3C+REC-xmlschema-1-20041028&doctype=W3C&query=REC-xmlschema-1-20041028&query_format=docid_regex&page=1, and note the error:
```Could not export this item, the error was: Source data for item W3C REC-xmlschema-1-20041028 (W3C) didn’t validate (err: 3 validation errors for CompositeSourcedBibliographicItem relation -> 0 -> bibitem -> formattedref instance of GenericStringValue, tuple or dict expected (type=type_error.dataclass; class_name=GenericStringValue) relation -> 1 -> bibitem -> formattedref instance of GenericStringValue, tuple or dict expected (type=type_error.dataclass; class_name=GenericStringValue) relation -> 2 -> bibitem -> formattedref instance of GenericStringValue, tuple or dict expected (type=type_error.dataclass; class_name=GenericStringValue))```

**Comment by rjsparks** [comment]
similar at https://bib.ietf.org/get-one/by-docid/?docid=W3C+REC-xmldsig-filter2-20021108&doctype=W3C&query=REC-xmldsig-filter2-20021108&query_format=docid_regex&page=1

**Comment by strogonoff** [comment]
@rjsparks This has to do with the mismatch of bibliographic source data values and bibliographic model definition.

The mismatch has to do with occasionally insufficient coordination between engineers responsible for source data retrieval logic (that `relaton-data-*` repositories), and engineers responsible for designing Relaton spec and implementing bibliographic data classes in Python (as part of `relaton-py` package).

In BibXML service, retrieved data is parsed according to `relaton-py` model definition (using Pydantic under the hood)—which ensures that, for example, strings are parsed to dates where needed, required properties exist or are filled in with defaults, and so on.

1. In GUI, the parsing-validation is done in “relaxed” mode, meaning if instantiating a `BibliographicItem` fails we still pass the data we get to GUI and defensive/forgiving template rendering makes sense of it.
2. During export, however, we must pass the constructed `BibliographicItem` to XML exporter. In that scenario, a choice was made to not risk passing an item that didn’t validate for programmatic consumption.

We’ll try to address the mismatch and review whether we can relax the (2) choice above.

**Comment by strogonoff** [comment]
Monitoring these two issues, that cause this to happen with references in I-D and NIST datasets:

- https://github.com/relaton/relaton-data-nist/issues/4
- https://github.com/ietf-tools/relaton-data-ids/issues/17

**Comment by strogonoff** [comment]
Partially addressed in https://github.com/ietf-ribose/bibxml-service/commit/9c49dc063c3d3b4c4d57b033193608cd4d4fce92, which attempts to parse relaxed YAML

**Comment by strogonoff** [comment]
The items mentioned now work, as should others with similarly loose source data (this links to dev.bibxml.org but changes should be in effect on bib.ietf.org as soon as it’s updated without re-indexing):

- https://dev.bibxml.org/get-one/by-docid/?docid=W3C+REC-xmlschema-1-20041028&doctype=W3C&query=REC-xmlschema-1-20041028&query_format=docid_regex&page=1
- https://dev.bibxml.org/get-one/by-docid/?docid=W3C+REC-xmldsig-filter2-20021108&doctype=W3C&query=REC-xmldsig-filter2-20021108&query_format=docid_regex&page=1

**Comment by strogonoff** [comment]
(Fixed ~2 weeks ago)
