### ISSUE TITLE
Implement legacy path pattern: NIST references (bibxml-nist)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#22]
IANA references (bibxml-nist)
* http://xml2rfc.tools.ietf.org/public/rfc/bibxml-nist/
* Pattern 1: http://xml2rfc.tools.ietf.org/public/rfc/bibxml-nist/reference.NIST.FIPS.8-6.xml
* Pattern 2: http://xml2rfc.tools.ietf.org/public/rfc/bibxml-nist/reference.NIST.TN.1968.xml

Legacy pattern(s) to implement:
* Pattern 1: http://xml2rfc.tools.ietf.org/public/rfc/bibxml-nist/reference.NIST.{old-docid}.xml

We just have to do a {old-docid} mapping to the new IDs.

**Comment by strogonoff** [comment]
After e92fdb77ba04adb8ba3ecc77e08421ff96987adb, the following pattern works (demo instance pending deployment): `/public/rfc/bibxml-nist/reference.NIST_TN_2160.xml`.

**Comment by strogonoff** [comment]
NIST pattern definition was updated (see [settings](https://github.com/ietf-ribose/bibxml-service/blob/main/bibxml/settings.py#L134)), this pattern now works: http://34.229.41.119:8000/public/rfc/bibxml-nist/reference.NIST.TN.1968.xml

**Comment by strogonoff** [comment]
Pattern for references that don’t start with NIST is broken, e.g. NBS citations are accessible via http://34.229.41.119:8000/public/rfc/bibxml-nist/NBS.IR.74-389.xml

**Comment by strogonoff** [comment]
@ronaldtse As we’ve established, some NIST references have other prefixes (e.g., http://34.229.41.119:8000/nist/NBS_IR_74-389/).

For those, which legacy pattern do we need to support?

1. /public/rfc/bibxml-nist/reference.NBS.IR.74-389.xml
2. /public/rfc/bibxml-nist/reference.NIST.IR.74-389.xml

**Comment by ronaldtse** [comment]
Actually I was mistaken -- there should be no legacy path for NIST because the old BibXML service never provided it as bibxmlN. There's no need to implement this for NIST.

**Comment by strogonoff** [comment]
I see, well it will a matter of configuration to enable if needed.
