### ISSUE TITLE
bibxml files should have line breaks

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-ribose/bibxml-service#229]
Currently, bibxml files have their XML all on one line. For instance:

    <reference target="https://www.ietf.org/archive/id/draft-ietf-teas-yang-te-29.txt" anchor="I-D.draft-ietf-teas-yang-te-29"><front><title>A YANG Data Model for Traffic Engineering Tunnels, Label Switched Paths and Interfaces</title><author fullname="Tarek Saad"><organization>Juniper Networks</organization></author><author fullname="Rakesh Gandhi"><organization>Cisco Systems Inc</organization></author><author fullname="Xufeng Liu"><organization>Volta Networks</organization></author><author fullname="Vishnu Pavan Beeram"><organization>Juniper Networks</organization></author><author fullname="Igor Bryskin"><organization>Individual</organization></author><author fullname="Oscar Gonzalez de Dios"><organization>Telefonica</organization></author><date year="2022" month="February"/><abstract><t>This document defines a YANG data model for the provisioning and management of Traffic Engineering (TE) tunnels, Label Switched Paths (LSPs), and interfaces. The model is divided into YANG modules that classify data into generic, device-specific, technology agnostic, and technology-specific elements. This model covers data for configuration, operational state, remote procedural calls, and event notifications.</t></abstract></front><seriesInfo name="Internet-Draft" value="draft-ietf-teas-yang-te-29"/></reference> 

The RPC has a use case--the creation of a reference to an RFC-to-be--where an editor includes the XML code from an Internet-Draft bibxml file in the RFCXML file and then edits it with that I-D's new RFC information. It is easier to create these reference entries when the XML in the bibxml file has line breaks like the following:

    <?xml version="1.0" encoding="UTF-8"?>
    <reference anchor="I-D.ietf-teas-yang-te">
       <front>
          <title>A YANG Data Model for Traffic Engineering Tunnels, Label Switched Paths and Interfaces</title>
          <author initials="T." surname="Saad" fullname="Tarek Saad">
             <organization>Juniper Networks</organization>
          </author>
          <author initials="R." surname="Gandhi" fullname="Rakesh Gandhi">
             <organization>Cisco Systems Inc</organization>
          </author>
          <author initials="X." surname="Liu" fullname="Xufeng Liu">
             <organization>Volta Networks</organization>
          </author>
          <author initials="V. P." surname="Beeram" fullname="Vishnu Pavan Beeram">
             <organization>Juniper Networks</organization>
          </author>
          <author initials="I." surname="Bryskin" fullname="Igor Bryskin">
             <organization>Individual</organization>
          </author>
          <author initials="O. G." surname="de Dios" fullname="Oscar Gonzalez de Dios">
             <organization>Telefonica</organization>
          </author>
          <date month="February" day="7" year="2022" />
          <abstract>
	     <t>   This document defines a YANG data model for the provisioning and 
    management of Traffic Engineering (TE) tunnels, Label Switched Paths (LSPs), 
    and interfaces.  The model is divided into YANG modules that classify data into 
    generic, device-specific, technology agnostic, and technology-specific elements. 
    This model covers data for configuration, operational state, remote procedural calls, 
    and event notifications. </t>
          </abstract>
       </front>
       <seriesInfo name="Internet-Draft" value="draft-ietf-teas-yang-te-29" />
       <format type="TXT" target="https://www.ietf.org/archive/id/draft-ietf-teas-yang-te-29.txt" />
    </reference>

There is another use case--the correction of information in a bibxml file--where an editor copies the XML into the RFCXML file and makes corrections until the bibxml source can be corrected, so all bibxml files should have line breaks for easier inclusion in RFCXML files.

**Comment by strogonoff** [comment]
Fixed in https://github.com/ietf-ribose/bibxml-service/commit/4bc983918c61d9dc0c30b5a28d2a9dfd876f65bb & https://github.com/relaton/relaton-py/commit/5d7393fbb672164ce9399db7efbace882308e0df

```console
foo@bar % curl "https://dev.bibxml.org/public/rfc/bibxml6/reference.R.IEEE.P802-3de/D-3.1.2022-05.xml"
<reference target="https://ieeexplore.ieee.org/document/9804358" anchor="IEEE.P802-3de/D-3.1.2022-05">
  <front>
    <title>IEEE Draft Standard for Ethernet - Amendment 5: Enhancements to the MAC Merge and Time Synchronization Service Interface for Point-to-Point 10 Mb/s Single Pair Ethernet</title>
    <author>
      <organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>
      <address>
        <postal>
          <country>USA</country>
          <city>New York</city>
        </postal>
        <uri>http://www.ieee.org</uri>
      </address>
    </author>
    <date year="2022" month="June" day="22"/>
    <abstract>
      <t>This amendment to IEEE Std 802.3-202x specifies additions to and appropriate modifications of the IEEE Std 802.3 MAC Merge sublayer and the Time Synchronization Service Interface (TSSI) to support 10 Mb/s Single-Pair Ethernet point to point PHYs.</t>
    </abstract>
  </front>
  <seriesInfo name="IEEE" value="p802.3de/d.3-1"/>
</reference>

```

**Comment by ronaldtse** [comment]
Thanks @strogonoff !
