### ISSUE TITLE
Mapping diffs: diffs should be XML normalized

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#234]
## Problematic: diffs should be XML normalized

We're now seeing a lot of diffs that represent identical XML data.

e.g.
<img width="843" alt="Screenshot 2022-07-15 at 9 49 37 AM" src="https://user-images.githubusercontent.com/11865/179124826-d1588870-a5d7-484a-8e8b-e30462555f2f.png">

There are a few problems:
* [x] Mapping diffs: XML should be normalized before comparison: it will get rid of the attribute ordering
* [x] Mapping diffs: BibXML service needs to return the XML headings of: `<?xml version="1.0"?>` and `<!DOCTYPE reference SYSTEM "rfc2629.dtd">`
* IETF is not the publisher of misc items
    * [x] https://github.com/relaton/relaton-ietf/issues/93
    * [x] https://github.com/ietf-tools/relaton-data-misc/issues/15

From: https://github.com/ietf-ribose/bibxml-service/issues/222

**Comment by ronaldtse** [comment]
W3C defines a canonical XML format, which can be done via the `lxml` package:
https://www.decalage.info/en/python/lxml-c14n

**Comment by strogonoff** [comment]
There is a mix of issues belonging to different repositories:

> Mapping diffs: BibXML service needs to remove <author><organization abbrev="IETF">Internet Engineering Task Force</organization></author> because the bibliographic item does not technically originate from IETF.

I believe this should be filed for the `misc` source data generator🤔 Filed in https://github.com/ietf-tools/relaton-data-misc/issues/15.

> Mapping diffs: XML should be normalized before comparison: it will get rid of the attribute ordering

Diffing is part of `test_paths.py` script, which is not part of the service and intended for internal use when testing xml2rfc path resolution.

If you suggest to canonicalize the output from the service, so far I would disagree with that. Canonicalization should not matter for consumers, and canonicalization will cause issues such as inability to output `seriesInfo` in a custom order (which may be requested in #239).

(And in both of the above cases, note that `lxml`’s canonicalized XML writer does not support pretty-printing XML—it should be doable, but I cannot readily estimate the level of effort required.)

>  Mapping diffs: BibXML service needs to return the XML headings of: <?xml version="1.0"?> and <!DOCTYPE reference SYSTEM "rfc2629.dtd">

Declaration should be added starting with the next release of relaton-py; but I want to confirm about the doctype before acting as it’s not something legacy xml2rfc output seems to have. There are two separate questions:

1. Is adding DOCTYPE warranted per XML spec?
2. Would adding DOCTYPE break some BibXML service xml2rfc path consumers?

**Comment by strogonoff** [comment]
> Canonicalization should not matter for consumers, and canonicalization will cause issues such as inability to output `seriesInfo` in a custom order

I may have been wrong on this part, I think XML canonicalization might not change element order after all. (I stand by the rest though)

**Comment by ronaldtse** [comment]
@strogonoff yes you're correct here. I believe canonicalisation does not change element order.

**Comment by strogonoff** [comment]
The other issues still stand. I want to get to the bottom of the original request (https://github.com/ietf-ribose/bibxml-service/issues/241#issuecomment-1192250911) to make sure this needs to be done and if so is done the correct way, since the level of effort is unclear.

**Comment by strogonoff** [comment]
For the record, canonicalization is done in the test_paths script now, if that was the issue: https://github.com/ietf-ribose/xml2rfc-mapping-convertor/commit/6564383e0a6363f59a2e44fc7c22c641f5e70921.

**Comment by ronaldtse** [comment]
> canonicalization is done in the test_paths script now

I think it is the content offered by the service that needs canonicalisation.

> I wonder if we’re mixing up presentation with data. 

My view is that we should only deal with accurate data semantics. However, a canonicalised presentation can help provide a consistent view for users that facilitates usage. We should not continue sinking resources into prettifying semantic data that no longer benefits the semantic user.

**Comment by strogonoff** [comment]
I like the idea of canonicalization in that it rules out issues where a particular XML formatting is requested, but requesting canonicalization alone is already in a way requesting particular XML formatting, and as mentioned in another issue I can’t myself come up with a use case where relying on it is not a mistake.

**Comment by ronaldtse** [comment]
I think canonicalisation is just good practice because it provide a reference to the user on what format to expect. Yes it is presentation, but it gives provides consistency that the user can expect.

For example, as a user, which XML would you prefer receiving when you debug?

```xml
<author type="person"><name>Name</name></author>
```

vs

```xml
<author


        type=person             >


            <name>Name</name>
      </author>
```
?

For me it is certainly the former.

**Comment by strogonoff** [comment]
> I think canonicalisation is just good practice because it provide a reference to the user on what format to expect. Yes it is presentation, but it gives provides consistency that the user can expect.
> 
> For example, as a user, which XML would you prefer receiving when you debug?
> 
> ```
> <author type="person"><name>Name</name></author>
> ```
> 
> vs
> 
> ```
> <author
> 
> 
>         type=person             >
> 
> 
>             <name>Name</name>
>       </author>
> ```
> 
> ?
> 
> For me it is certainly the former.

1. I would be indifferent, because I would be a software library parsing XML. XML is not intended for presentation and human consumption.
2. The latter would indicate that XML is put together by a template, which means there’s a high chance it’s invalid XML. Our XML is put together by libxml2.

**Comment by strogonoff** [comment]
I’ll look into canonicalization, since it should be low effort. However, any consumer tool relying on it will be making a mistake. If it requires XML of certain formatting then it does not parse XML correctly, and if it needs to diff it against something else it must canonicalize _again_ using its internally consistent rules.

**Comment by strogonoff** [comment]
I believe all are addressed.

- Canonicalization is in effect
- XML preamble is now included as follows:
  ```
  <?xml version='1.0' encoding='utf-8'?>
  <!DOCTYPE reference SYSTEM "rfc2629.dtd">
  <reference anchor="DOI_10.6028_NIST.SP.800-185" target="http://dx.doi.org/10.6028/nist.sp.800-185">
    <front>
      <title>SHA-3 derived functions: cSHAKE, KMAC, TupleHash and ParallelHash</title>
      <author fullname="John Kelsey" surname="Kelsey"/>
      <author fullname="Shu-jen Change" surname="Change"/>
      <author fullname="Ray Perlner" surname="Perlner"/>
      <author>
        <organization>National Institute of Standards and Technology</organization>
      </author>
      <date month="December" year="2016"/>
    </front>
    <seriesInfo name="DOI" value="10.6028/nist.sp.800-185"/>
  </reference>
  ```
