### ISSUE TITLE
Reference returned by legacy url path has bogus content

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#240]
https://bib.ietf.org/public/rfc/bibxml/reference.IEEE.802.15.4P_2014.xml returns something that looks like it's claiming this is rfc 802 and has an anchor that makes no sense.

There is no analog at https://xml2rfc.tools.ietf.org/. Where is this coming from?

(It's preventing the resolution logic from finding the well constructed reference in the IEEE datatset).

**Comment by strogonoff** [comment]
Why this happened: the `RfcAdapter` (that handles `/public/rfc/bibxml/` paths) was fuzzy and without [this condition](https://github.com/ietf-ribose/bibxml-service/blob/f923d81fb8b128afa684c8ac2a28db1bdc7a63b5/bibxml/xml2rfc_adapters.py#L54) it matched any anchor where a number follows the first period. It would then substitute obtained number into a “RFC {num}” query, causing IEEE.802… to resolve to RFC 0802.

Cause: xml2rfc path adapters in the service were written without a requirement to _not match_ xml2rfc paths. However, I went through the other adapters and I don’t think there’s any as permissive as RFC to allow a wrong document type to go through. I added extra guards for NIST and IANA paths just in case.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Comment by rjsparks** [comment]
To answer where I got the URL - xml2rfc (part of the v2 parser) computed it given the input 
```
      <?rfc include="reference.IEEE.802.15.4P_2014.xml" ?> 
```
which is still a common kind of construct since it is produced by the kramdown rfcxml generator for people authoring in markdown. That path relies on the v2v3 converter, which runs the v2 logic to process PIs like that one.

That logic searches through the various datasets by making http requests, in a particular order, until it gets a response.
You can see this happening with xml2rfc --verbose when you run it over a document containing such PIs.

**Comment by strogonoff** [comment]
> searches through the various datasets by making http requests, in a particular order, until it gets a response

Interesting. This clarified how external consumers could be broken by a false positive.

**Comment by ronaldtse** [comment]
@rjsparks this is particular interesting because the path:
http://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.IEEE.802.15.4P_2014.xml

Does not exist.

I assume that the v2v3 converter tries out the `/bibxml{n}/` datasets to find a match. This is technically searching. This functionality for searching data is now implemented on the BibXML Service, and should be migrated to that. i.e. the v2v3 converter should now utilize the BibXML Service's search API to find a correct match instead.

**Comment by ronaldtse** [comment]
I guess this signifies a good problem to raise because it highlights to the client implementers that there are simpler ways to do what has been done before.

**Comment by strogonoff** [comment]
@ronaldtse I totally missed that indeed it’s doing an equivalent of a search, which this service is supposed to handle better through its primary API.

I think if we got a more complete landscape of bib data retrieval use cases by legacy consumers, it would allow us to make sure the primary API is as suited to straightforward migration as possible, though even as is it should address most common use cases…

**Comment by rjsparks** [comment]
"Use the new api" is not the answer to this particular issue though.

**Comment by strogonoff** [comment]
@rjsparks 

True, the fix applied per this ticket was critical to avoid breaking xml2rfc API consumers right now. However, eventually switching to a new API is on the roadmap, is it not?

Speaking of, it might be useful if we confirm IETF’s plan regarding the migration (perhaps on a call, for higher bandwidth?) to the degree it’s known… While it might be too late for some changes, we’ll at least ensure relevant documentation is using the correct angle.

**Comment by rjsparks** [comment]
While we expect some of the tools under our control to start using the new api, the RFP does not deprecate the older api, and we anticipate that community supported tools will use it for some time, perhaps years. Please stop thinking of the path approach to fetching content as something that will go away.

**Comment by rjsparks** [comment]
We have been working towards a call. This week's meeting, and several people being ill, is delaying it. It will be put together as soon as possible.

**Comment by ronaldtse** [comment]
Thanks @rjsparks , look forward to the call. In any case, if there is anything else you expect to happen relating to this ticket, please feel free to reopen it.
