### ISSUE TITLE
Issue with DOI anchors

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#245]
(apologies for brevity - ongoing IETF meeting)
compare the anchor at
https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.SP.800-185.xml
and
https://xml2rfc.tools.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.SP.800-185.xml

Both should return what xml2rfc.tools.ietf.org are returning.

**Comment by ronaldtse** [comment]
Both paths are identical: `bibxml7/reference.DOI.10.6028/NIST.SP.800-185.xml`.

The anchors are:
* In the new copy: `_10.6028_nist.sp.800_185`
* In the old copy: `DOI_10.6028_NIST.SP.800-185`

Difference:
* The old copy applies a conversion of `DOI.10.6028/NIST.SP.800-185` to `DOI_10.6028_NIST.SP.800-185` by replacing the first `.` with `_`, the `/` with `_`, and does not touch the `-`.

**Comment by rjsparks** [comment]
Keeping the old anchor is essential. A transformation is not ok.
Documents are in progress right now that _use_ the existing anchor in xrefs in their existing text. Asking authors to make a translation is not ok.

**Comment by ronaldtse** [comment]
@rjsparks in case this was a misunderstanding, I was merely detailing out the exact issue here in order to reverse engineer how the anchor came about.

**Comment by rjsparks** [comment]
sure- again, forgive my terse responses during the meeting week.

**Comment by strogonoff** [comment]
This should be addressed as of https://github.com/ietf-ribose/bibxml-service/pull/246, tag for version `2022.7.28_1` had been published.

**Comment by strogonoff** [comment]
> * The old copy applies a conversion of `DOI.10.6028/NIST.SP.800-185` to `DOI_10.6028_NIST.SP.800-185` by replacing the first `.` with `_`, the `/` with `_`, and does not touch the `-`.

Indeed… As a post-mortem:

- The service relies on relaton-py for anchor formatting by default.
- Relaton-py does not consider XML filename in the URL as one of inputs (it’s way outside of its scope), and builds the anchor purely from document identifiers [adjusted](https://github.com/relaton/relaton-py/blob/e44562f1b43268369ff973b197117e613f130a8e/relaton/serializers/bibxml/anchor.py#L39-L66) to fit the `anchor` schema if needed.
- Being aware that in BibXML service anchors may need to be compatible with xml2rfc XML, and be derived from requested URL as opposed to document identifier, we made it easy to override anchor formatting behavior by providing a `format_anchor()` method on particular xml2rfc path adapter.
- This was already used to provide correct anchors for Internet Drafts and RFCs, but DOI was overlooked. @stefanomunarini [corrected](https://github.com/ietf-ribose/bibxml-service/commit/5ef237da36a1526f9cfa6d2ca99480017b210904) that.
