### ISSUE TITLE
Development UI screenshots

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#25]
Courtesy of @strogonoff .

Search:
<img width="1117" alt="Screenshot 2021-11-19 at 11 35 27 PM" src="https://user-images.githubusercontent.com/292959/142699984-3941c544-349c-43b6-af9d-3d630eed1fce.png">

Single record view:
![image](https://user-images.githubusercontent.com/11865/142595366-151509fc-684a-4566-b3bc-59e15f8a59d8.png)

Collection view:
<img width="1348" alt="Screenshot 2021-11-19 at 11 36 22 PM" src="https://user-images.githubusercontent.com/292959/142700057-ce0c6b3b-bbf0-450b-82af-f6cef2f21fe7.png">

Internal:
<img width="1348" alt="Screenshot 2021-11-19 at 11 36 41 PM" src="https://user-images.githubusercontent.com/292959/142700087-00c529ec-2a7c-4c59-bc17-083724bd18d8.png">

**Comment by ronaldtse** [comment]
@strogonoff since `doi` is not a full dataset we probably don't want to have a "list" interface for it.

Perhaps some rearrangement is useful too, we should distinguish the IETF authoritative datasets vs the third-party ones.

**Comment by strogonoff** [comment]
Note: this is now viewable on the demo instance.

> since `doi` is not a full dataset we probably don't want to have a "list" interface for it.

Yes, currently it will just fail. DOI shouldn’t be among “knownn dataset” as far as indexer service is considered, will fix shortly.

> Perhaps some rearrangement is useful too, we should distinguish the IETF authoritative datasets vs the third-party ones.

If we’re speaking of “rearrangement” in the GUI, I’d like to check on use cases, what I’ll do for now is make sure authoritative datasets are shown first and are visually highlighted.

**Comment by strogonoff** [comment]
Some screenshots in issue description were not matching captions, replaced them with the correct ones.

**Comment by ronaldtse** [comment]
Closing.
