### ISSUE TITLE
Support data variables in legacy path patterns

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#28]
required for  #13

**Comment by strogonoff** [comment]
May or may not be required, but is mostly implemented anyway.

**Comment by strogonoff** [comment]
The mechanism will be this, example Django configuration:

      from django.db.models.query import Q

      def build_id_query(legacy_ref):
          parts = legacy_ref.split('-')
          if len(parts) > 1:
              rev = parts[-1]
              name = '-'.join(parts[0, len(parts) - 1])
              return Q(body__rev=rev) & Q(body__name=name)
          else:
              return Q(body__name=name)

      LEGACY_DATASETS = {
          'bibxml3': {
              'dataset_id': 'ids',
              'query_builder': build_id_query,
          },
      }

  Would mean that for a request to
  `/public/rfc/bibxml3/reference.SOME-NAME-123.xml`
  the service would try to return a citation in dataset `ids`
  where `body` contains key 'name' matching "SOME-NAME"
  _and_ key 'rev' matching "123".

**Comment by ronaldtse** [comment]
@strogonoff this makes sense.

**Comment by strogonoff** [comment]
The new approach uses a slightly different logic, allowing fetcher functions use any logic they want based on received filename/anchor: https://github.com/ietf-ribose/bibxml-service/blob/main/xml2rfc_compat/fetchers.py
