### ISSUE TITLE
Implement API to retrieve a document by reference and support DOI first

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#3]

**Comment by yablokov** [comment]
@strogonoff you can check URLs like this `/api/v1/ref/doi/10.1002/bult.2015.1720410411` (and also I think we need to approve API URL scheme in the early stages).

**Comment by ronaldtse** [comment]
This pattern works:

`/api/{version}/ref/{bibtype}/{bibid}`

* `{bibid}` potentially could take a non-normalised identifier, e.g. "RFC1234" vs "ietf-rfc-1234"

@yablokov can you write an openapi.yaml file to document this?

**Comment by yablokov** [comment]
@ronaldtse Yes, also it would be nice to get more examples of a non-normalised identifiers. Only spaces and '-' can be used as separators? Underscores? 

Or may be better to clean these identifiers from non-standard characters and then try to normalize it?

**Comment by strogonoff** [comment]
Retrieving documents works, but lookup by docid is the preferred method instead of dataset reference.
