### ISSUE TITLE
Properly report non-404 errors from DOI

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#34]
Currently, even if DOI returns 503, BibXML returns the “not found” response.

Discovered by cURLing a reference with 503 result, and trying it using BibXML service (running from the same IP) getting “not found” response.

**Comment by strogonoff** [comment]
Upstream: https://github.com/ietf-ribose/doi2ietf-py/issues/12

**Comment by TonyLHansen** [comment]
can you give me an example of a DOI reference that would return a 503?

**Comment by strogonoff** [comment]
@TonyLHansen Take for example 10.1109/IEEESTD.2005.98651 or 10.6028/NIST.IR.7057, though I don’t think this depends on a DOI and rather on where the request is made from.

As of a week+ ago the situation was that the same request reliably returned 200 on our previous demo instance on AWS, and at the same time returned 503 from my residential IP:

    curl  -i -X GET -H "Accept: application/citeproc+json" https://data.crossref.org/10.6028/NIST.IR.7057

As of now, however, I can’t get anything besides 503 from a number of different hosts, and I believe the same occurs on our new demo infrastructure using K8s (also AWS, but different IPs).

A fix in doi2ietf and in bibxml-service to report 503 properly should make it to demo instance shortly and then I hope to see whether this is the case.

**Comment by strogonoff** [comment]
In fact, it happens on GHA infrastructure as well, made evident by failing doi2ietf integration tests (which use DOIs `10.1109/5.771073` and `10.1109/MIC.2012.29`) if the fix to raise 503 errors is applied: https://github.com/ietf-ribose/doi2ietf-py/runs/4490309652?check_suite_focus=true#step:5:19

**Comment by ronaldtse** [comment]
FYI https://github.com/ietf-ribose/doi2ietf-py/pull/13#issuecomment-991417767 data.crossref.org is down.

**Comment by strogonoff** [comment]
Fixed while fixing #32. Connection errors are now reported in the GUI.
