### ISSUE TITLE
Removal of duplicate 3GPP references from this dataset, with a legacy path mapping

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#35]
In the latest bibxml4 dataset, there are two patterns of reference files:

* `reference.SDO-3GPP.*.xml`
* `reference.3GPP.*.xml`

We will need to build legacy file mappings for both, but I wanted to find out if the content really differs between them.

Since we already the anchors are different (because the anchors follow the filenames), we will omit the difference in anchors:
```sh
$ sed -i'.bak' 's#SDO-##g' reference.SDO-3GPP.*.xml
$ find . -name 'reference.SDO-3GPP.*.xml' -exec bash -c 'diff $0 ${0/SDO-/}' {} \;
```

The collection of files are different in cardinality:
```sh
$ ls -l reference.3GPP.*.xml | wc -l
    2217
$ ls -l reference.SDO-3GPP.*.xml | wc -l
    2110
```

So the pattern `reference.3GPP.*.xml` contains 117 files that `reference.SDO-3GPP.*.xml` does not have.

The speculation is that the `reference.SDO-3GPP.*.xml` pattern contains older data than `reference.3GPP.*.xml`.

The actual differences between the files are:

```xml
5c5
< <title>Voice Broadcast Service (VBS); Stage 2</title>
---
> <title>Voice Broadcast service (VBS); Stage 2</title>
5c5
< <title>Location Services (LCS); Serving Mobile Location Centre - Serving Mobile Location Centre (SMLC - SMLC); SMLCPP specification</title>
---
> <title>Location Services (LCS): Serving Mobile Location Centre - Serving Mobile Location Centre (SMLC - SMLC); SMLCPP specification</title>
5c5
< <title>Customised Applications for Mobile network Enhanced Logic (CAMEL) Phase X; CAMEL Application Part (CAP) specification</title>
---
> <title>Customized Applications for Mobile network Enhanced Logic (CAMEL) Phase X; CAMEL Application Part (CAP) specification</title>
5c5
< <title>3G Security; Specification of the MILENAGE algorithm set: An example algorithm set for the 3GPP authentication and key generation functions f1, f1*, f2, f3, f4, f5 and f5*; Document 3: Implementors' test data</title>
---
> <title>3G Security; Specification of the MILENAGE algorithm set: An example algorithm set for the 3GPP authentication and key generation functions f1, f1*, f2, f3, f4, f5 and f5*; Document 3: Implementors’ test data</title>
5c5
< <title>Customised Applications for Mobile network Enhanced Logic (CAMEL); Service description; Stage 1</title>
---
> <title>Customized Applications for Mobile network Enhanced Logic (CAMEL); Service description; Stage 1</title>
5c5
< <title>3G security; LawfulInterception; Stage 2</title>
---
> <title>3G security; Lawful Interception; Stage 2</title>
5c5
< <title>IP Multimedia Subsystem (IMS) Application Level Gateway (IMS-ALG) - IMS Access Gateway (IMS-AGW) interface: Procedures descriptions</title>
---
> <title>IP Multimedia Subsystem (IMS) Application Level Gateway (IMS-ALG) – IMS Access Gateway (IMS-AGW) interface: Procedures descriptions</title>
5c5
< <title>Customised Applications for Mobile network Enhanced Logic (CAMEL) Phase 4; Stage 2; IM CN Interworking</title>
---
> <title>Customized Applications for Mobile network Enhanced Logic (CAMEL) Phase 4; Stage 2; IM CN Interworking</title>
5c5
< <title>Customised Applications for Mobile network Enhanced Logic (CAMEL) Phase 4; Stage 2</title>
---
> <title>Customized Applications for Mobile network Enhanced Logic (CAMEL) Phase 4; Stage 2</title>
5c5
< <title>Mobile radio interface layer 3 specification; Radio Resource Control (RRC) protocol; Iu mode</title>
---
> <title>Mobile radio interface layer 3 specification, Radio Resource Control (RRC) protocol; Iu mode</title>
5c5
< <title>Telecommunication management; Self-configuration of network elements Integration Reference Point (IRP); Solution Set (SS) definitions</title>
---
> <title>Telecommunication management; Self-Configuration of Network Elements Integration Reference Point (IRP); Solution Set (SS) definitions</title>
5c5
< <title>TISPAN; PSTN/ISDN simulation services Terminating Identification Presentation (TIP) and Terminating Identification Restriction (TIR); Protocol specification</title>
---
> <title>PSTN/ISDN simulation services Terminating Identification Presentation (TIP) and Terminating Identification Restriction (TIR); Protocol specification</title>
5c5
< <title>Telecommunication management; Generic Integration Reference Point (IRP) management; Solution Set (SS) definitions</title>
---
> <title>Telecommunication management; Generic Integration Reference Point (IRP) management; Solution Set (SS) Definitions</title>
5c5
< <title>3G Security; Lawful Interception; Stage 2</title>
---
> <title>Lawful Interception; Stage 2</title>
```

Which aren't many.

We can immediately pick up those minor differences:
* British English vs American English spelling ("Customised" vs "Customized")
* Colon vs semi-colon ("Location Services (LCS):" vs "Location Services (LCS);")
* Capitalisation ("service" vs "Service")
* Unicode punctuation `-` vs `–`
* Typos ("Lawful Interception" vs "LawfulInterception")

In all cases, the pattern `reference.3GPP.*.xml` contains content that are more correct
* typos, semicolons fixed
* uses British English spelling for their titles, which from their official page is the correct spelling (e.g. [3GPP 29.078](https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=1597)

I propose that we make these assumptions:
1. The intention of `reference.3GPP.*.xml` and `reference.SDO-3GPP.*.xml` are identical, and hence the content of `reference.3GPP.*.xml` and `reference.SDO-3GPP.*.xml` are meant to be identical
2. Since there are `reference.3GPP.*.xml` files that do not have a corresponding `reference.SDO-3GPP.*.xml` file, when asked for that `reference.SDO-3GPP.*.xml` file, we can respond with the content of the `reference.3GPP.*.xml` file.

@rjsparks is that acceptable?

**Comment by rjsparks** [comment]
Proxying for @tonylhansen:

> I agree with the plan for reference.SDO-3GPP.*.xml to return the contents of what is in the corresponding reference.3GPP.*.xml, with one correction: the anchor must be modified to include the "SDO-" before returning the remaining contents.

**Comment by ronaldtse** [comment]
Thank you @rjsparks @TonyLHansen for the confirmation!

Yes the `anchor=` attribute should reflect the original filename (with the `anchor` being `SDO-3GPP...` for the `reference.SDO-3GPP...xml` retrievals).

**Comment by rjsparks** [comment]
Tony couldn't comment himself - would it make sense to invite him into the org?

**Comment by ronaldtse** [comment]
Of course, let me add him.

**Comment by ronaldtse** [comment]
@rjsparks technically I think anyone could comment in these public repos? Tony has previously commented on some other thread I believe.

**Comment by TonyLHansen** [comment]
checking if I can post a comment :)

**Comment by rjsparks** [comment]
problem solved...

**Comment by ronaldtse** [comment]
> > I agree with the plan for reference.SDO-3GPP._.xml to return the contents of what is in the corresponding reference.3GPP._.xml, with one correction: the anchor must be modified to include the "SDO-" before returning the remaining contents.

@strogonoff have we implemented this additional legacy mapping?

**Comment by strogonoff** [comment]
> > > I agree with the plan for reference.SDO-3GPP._.xml to return the contents of what is in the corresponding reference.3GPP._.xml, with one correction: the anchor must be modified to include the "SDO-" before returning the remaining contents.
> 
> @strogonoff have we implemented this additional legacy mapping?

I believe I have just now been told in https://github.com/ietf-ribose/bibxml-service/issues/126 that there is no other aliasing going on… Interesting, must have been misunderstanding.

**Comment by strogonoff** [comment]
But as it happens, automated path resolution should support both prefixes:

https://github.com/ietf-ribose/bibxml-service/blob/0fcc9d7b09d1f54872b7d623ac3300f1ed645c6a/xml2rfc_compat/fetchers.py#L140-L154

**Comment by ronaldtse** [comment]
@strogonoff you are correct with the pattern `SDO-3GPP` needing resolution.

**Comment by ronaldtse** [comment]
@strogonoff since this is implemented can we close this issue? Thanks.

**Comment by ronaldtse** [comment]
Ping @strogonoff

**Comment by strogonoff** [comment]
@ronaldtse I’m OK closing it, and mappings for 3GPP are discussed in https://github.com/ietf-ribose/bibxml-service/issues/135.
