### ISSUE TITLE
Show a message when there are no search results

### ISSUE THREAD

**Issue by kesara** [ietf-ribose/bibxml-service#38]
When search result from web UI has zero matches, show a message indicating that.
Example: https://demo.bibxml.org/search/?query=%2Bieee+foobar
<img width="2793" alt="Screen Shot 2021-12-14 at 5 37 14 AM" src="https://user-images.githubusercontent.com/1027692/145851921-6f54c3e4-0e32-430f-a61e-a039ba86b6cc.png">

Right now web UI gives an impression that it's still searching even though there are no matches.

**Comment by strogonoff** [comment]
Fair point. Currently all pages are (intentionally) fully server-side rendered with as little client-side complexity as possible, so once search result page is rendered that’s it. Search results page will make it clearer.

**Comment by strogonoff** [comment]
Fixed and should make it to demo instance (it’ll take longer just this time, since K8s configuration is being updated after codebase unification).
