### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#39]
This is a moderately far out idea for now, at least as far as I’m concerned, but GraphQL API is an option that might be very feasible given current architecture.

It has its downsides (e.g., consumers may start depending on citation attributes even if as data structure may change as citation sourcing evolves; inconsistencies between data sources will become more obvious and irritating—some sources contain more data compared to the others, so a finer-grained query may unintentionally exclude citations; higher complexity; etc.), but also some upsides which may outweigh now or in near future (although I don’t think GQL should be made the primary supported API).

**Comment by ronaldtse** [comment]
Fully agree with offering a GraphQL API in addition to the (a) legacy file path and (b) file path option!

**Comment by strogonoff** [comment]
I think this should be wontfixed for now due to lack of resources.
