### ISSUE TITLE
CI: deployment does not work

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#4]
### Describe the issue

https://github.com/ietf-ribose/bibxml-service/actions/runs/3100976322/jobs/5021840965#step:2:12

Perhaps since it’s a fork the repository is missing configuration?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by strogonoff** [comment]
@kwkwan Perhaps you could look into it?

**Comment by kwkwan** [comment]
I have added back the missing credentials in secrets.  The deploy task is successful after the changes.
