### ISSUE TITLE
Support non-normalised publication identifiers 

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#4]
From @yablokov:

In the API URL pattern, what identifiers do we support?

Right now, the bibxml patterns go like "rfcNNNN.xml".

Should we support:
* "RFCNNNN.xml"
* "IETF-RFC-NNNN.xml"
* or?

> would be nice to get more examples of a non-normalised identifiers.

* Spaces
* Hyphens '-'
* Underscores
?

> Or may be better to clean these identifiers from non-standard characters and then try to normalize it?

_Originally posted by @yablokov in https://github.com/ietf-ribose/bibxml-service/issues/3#issuecomment-909075658_

**Comment by strogonoff** [comment]
I think this is closed? Currently, identifiers used in APIs are obtained from filenames in `bibxml-data-` repositories.

**Comment by ronaldtse** [comment]
Agree. Closing.
