### ISSUE TITLE
rfcs, ids, rfcsubseries datasets are not indexing

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#41]
https://github.com/ietf-ribose/bibxml-service/blob/d64b54e511c46fb665e819d455c91866695a3bb4/bibxml/settings.py#L266-L268

**Comment by strogonoff** [comment]
It already uses ietf-ribose/bibxml-data-<dataset id> and ietf-ribose/relaton-data-by default, withmain` branches. Documentation will reflect that.

**Comment by ronaldtse** [comment]
But this? Is the configuration not yet updated?

<img width="821" alt="Screenshot 2021-12-21 at 8 28 33 AM" src="https://user-images.githubusercontent.com/11865/146850567-1b9348c3-c7a5-483f-b84e-6cce9909d24f.png">
<img width="805" alt="Screenshot 2021-12-21 at 8 28 42 AM" src="https://user-images.githubusercontent.com/11865/146850580-194a4c43-fb8f-4c41-ba8a-0c614a70a128.png">
<img width="796" alt="Screenshot 2021-12-21 at 8 28 49 AM" src="https://user-images.githubusercontent.com/11865/146850591-2352411d-9f83-4729-8799-695bacbdc50d.png">

**Comment by strogonoff** [comment]
I will investigate. It could be branch mismatch, in that case override will be added.

**Comment by strogonoff** [comment]
@ronaldtse it’s empty? https://github.com/ietf-ribose/bibxml-data-rfcsubseries

**Comment by ronaldtse** [comment]
There is some misunderstanding here. As mentioned, all IETF datasets are at `ietf-ribose/relaton-data-*`. e.g. https://github.com/ietf-ribose/relaton-data-rfcsubseries

**Comment by ronaldtse** [comment]
@strogonoff has clarified offline that we currently need two repositories per dataset. The relaton-data one for search indexing (as it provides more data) and the bibxml-data one for serving BibXML. The latter dataset will no longer be needed once the service integrates the relaton-py library which converts Relaton data to BibXML on the fly. This is also necessary for serving other bibliographic formats like bibtex. Will file that as a separate issue. 

And now the topic datasets are indexing properly. Closing.
