### ISSUE TITLE
Manager’s GUI incorrectly shows buttons to “reindex” external datasets

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#43]
https://demo.bibxml.org/management/doi/

Hmm...
<img width="869" alt="Screenshot 2021-12-20 at 6 46 10 PM" src="https://user-images.githubusercontent.com/11865/146755232-6a69a847-2ec3-48b0-80c9-2a11ad0ff664.png">

**Comment by ronaldtse** [comment]
And on front page:
<img width="864" alt="Screenshot 2021-12-20 at 6 47 32 PM" src="https://user-images.githubusercontent.com/11865/146755391-9fb7b292-2a7f-4808-a0f7-5b5ccdee41a0.png">

**Comment by strogonoff** [comment]
@ronaldtse 

- Manager’s GUI incorrectly shows a button to “reindex” DOI.
- I see no issues with the second screenshot.

**Comment by strogonoff** [comment]
It is considered "browsable" in the sense that the user can paste a DOI.

In any case, if things go as planned and we have time, I want to remove dataset browsing, and focus on browsing by docid.type. These “datasets” are irrelevant to users, they are really just service’s data sources; they just happen to roughly align with doctypes/orgs (and even then not all do, e.g. “misc”).

**Comment by ronaldtse** [comment]
Indeed, the datasets are not really browsable because it doesn't make sense to manually browse through thousands of pages. Making search accessible and relevant is the way to go.

**Comment by ronaldtse** [comment]
> It is considered "browsable" in the sense that the user can paste a DOI.

This is really stretching the definition of "browsable". Pasting a single DOI should be in no way considered "browsable":

From macOS dictionary:
```
browse | brouz |
verb [no object ]
1 survey goods for sale in a leisurely and casual way: he stopped to browse around a sporting goods store.
• scan through a text, website, or collection of data to gain an impression of the contents: 
  she browsed through the newspaper | 
  [with object ] : I decided to spend the night browsing the internet.
```

**Comment by strogonoff** [comment]
Agreed, right now the wording on the landing page is imprecise. After the switch from browsing by dataset to browsing by document type it will make more sense (the user will be able to browse pre-indexed DOI references, in addition to being able to request an external one).
