### ISSUE TITLE
Use relaton-py library to generate BibXML

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#46]
We currently need two repositories per dataset. The relaton-data one for search indexing (as it provides more data) and the bibxml-data one for serving BibXML. 

The latter dataset will no longer be needed once the service integrates the relaton-py library which converts Relaton data to BibXML on the fly. This is also necessary for serving other bibliographic formats like bibtex.

Once this is done we can also remove the unneeded dataset repos. 

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/bibxml-service/issues/41#issuecomment-1000746885_

**Comment by strogonoff** [comment]
@ronaldtse this relies on relaton-bib library, which is not ready yet.

@CAMOBAP  doesn't work on bibxml-service  codebase.

**Comment by ronaldtse** [comment]
@strogonoff the YAML parsing part is already filed here: https://github.com/relaton/relaton-bib-py/issues/6

**Comment by strogonoff** [comment]
IETF BibXML service currently generates XML using [its own serializer](https://github.com/ietf-ribose/bibxml-service/blob/main/xml2rfc_compat/serializer.py).
