### ISSUE TITLE
Adjusted `xml2rfc` compatibility path implementation

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#49]
Requirements (to reiterate):

- A valid XML response must be returned for any requested xml2rfc path
- If possible (plan A), returned XML response must reflect a citation indexed from one of the canonical data sources, not its original xml2rfc contents
- As a fallback (plan B), returned XML response must be the exact file under requested xml2rfc path

Adjusted legacy path implementation is as follows:

- When handling an xml2rfc path, BibXML service will transform the path to citation document type & ID (the `docid` pair in Relaton data)
- For example, a path like `/public/rfc/bibxml9/reference.BCP.0004.xml` should be converted to docid like `{ "type": "IETF", "id": "IETF BCP 4" }`
- Manual docid mapping will be used first, if defined for this path
- In absence of manual mapping, automatic transformation will be attempted (fallible)
- If either of the above fails, BibXML service will return pre-crawled XML file obtained from xml2rfc server

**Comment by ronaldtse** [comment]
Just to clarify that there are 2 types of mappings:
1. A path pattern mapping where a legacy filename path maps to a new citation document ID. This works for file paths that have a strong path pattern consistency, i.e. RFCs and I-Ds.
2. A manual file path mapping (which is technically the singular case for 1), where the legacy file path is not based on a consistent underlying path pattern, and that we need to make a one-to-one mapping from legacy file path to document ID. e.g. this will be the case for the `ieee`, `misc` datasets

**Comment by strogonoff** [comment]
> Just to clarify that there are 2 types of mappings:

To use precise terminology, there is a manual _mapping_, and there is an automated path=>docid transformation attempted in absence of the mapping.

If docid obtained as a result of that transformation does not yield an indexed citation, then we fall back to source contents.

> And the most important thing is that the "legacy path mappings" should be considered configuration and changeable without needing code changes.

This depends on how we provide legacy path mappings. Originally I intended to provide a web GUI for that, but you mentioned some data analysis was being performed and I thought we might get a pre-made map as a result of that effort, in which case it’s probably not going to change.

**Comment by strogonoff** [comment]
New implementation uses [fetcher functions](https://github.com/ietf-ribose/bibxml-service/blob/main/xml2rfc_compat/fetchers.py), mapped to relevant bibxml directories [in URL configuration](https://github.com/ietf-ribose/bibxml-service/blob/main/bibxml/urls.py#L105).
