### ISSUE TITLE
Relaton YAML format consistency

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#5]
From @strogonoff :

> @yablokov says the data in Relaton YAML is not consistent across standard data repos

**Comment by ronaldtse** [comment]
@yablokov can you provide some more information so @andrew2net can help address? Thanks.

**Comment by yablokov** [comment]
@andrew2net
At first, we need to use primary key. Some datasets has files without "id" key at root level:
f.e. [relaton-data-iho.](https://github.com/relaton/relaton-data-iho/tree/master/data) Is that "id" field is mandatory by standard and unique for dataset?
Is there any mandatory fields?

As temporary solution I used "docid" instead missing "id". Also can I use "doctype" instead "type" in same cases?

Or better to use filenames as primary keys?

**Comment by andrew2net** [comment]
@yablokov `id` filed is derived from `docid`. File names are also derived from `docid`. So the `docid` is the only identifier of a document.
The field `type` is always `standard`. The field `doctype` contains a value from a source.

**Comment by ronaldtse** [comment]
> The field type is always `standard`

Is this because of ISO 690?

----

@yablokov `doctype` is organization specific (e.g. some organizations allow `standard`, some allow `guide`, etc).

**Comment by andrew2net** [comment]
> Is this because of ISO 690?

@ronaldtse  I'm not sure. I've got this information from Nick.

**Comment by yablokov** [comment]
Ok, I updated indexer, now it use `docid` element.

**Comment by strogonoff** [comment]
I think it’s partly closed, partly superseded by https://github.com/ietf-ribose/bibxml-project/issues/9: for up-to-date reference, we are supposed to rely on grammar in https://github.com/relaton/relaton-models/blob/87b319a8872db45e8f2343a5f7ad4f806de041a9/grammars/biblio.rnc, and not on the model.

**Comment by strogonoff** [comment]
Specific consistency issues can be filed separately
