### ISSUE TITLE
Obtain original xml2rfc contents

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#50]
Per #49, we need a copy of xml2rfc dataset. We can either crawl it in BibXML service as an indexer task, crawl it externally (e.g., in a scheduled GHA committing to a repository), or request a complete dump from IETF.

The concerns are:

- xml2rfc server shouldn’t be overloaded (especially during times of extensive testing)
- xml2rfc server does not list contents of some datasets (not clear whether they are not public, or there is a server-side issue)
- if xml2rfc contents are not liable to change, we shouldn’t do this repeatedly and only obtain a single-time dump

**Comment by ronaldtse** [comment]
This is now implemented, with the data archive available in https://github.com/ietf-ribose/bibxml-data-archive and the sync code at https://github.com/ietf-ribose/bibxml-data-archive-sync.

**Comment by strogonoff** [comment]
Sweet!

**Comment by strogonoff** [comment]
Not closing yet, because `misc` seems absent

**Comment by ronaldtse** [comment]
Yes it is provided as bibxml2, which is its "original" name.
