### ISSUE TITLE
Account for automated commits

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#51]
Is there a Github bot account that can be used to make automated commits in ietf-ribose repositories? Perhaps `ietf-ribose-ci`? Can BibXML service get its authentication credentials?

**Comment by ronaldtse** [comment]
Yes that's the account. However what are we trying to commit to the repos? The legacy path mappings?

**Comment by strogonoff** [comment]
@ronaldtse Yes. Generally speaking, persisting public data outside the database to reduce maintenance burden/ Mapping xml2rfc tools paths to docids is the use case at the moment (though there may be others later).

**Comment by ronaldtse** [comment]
Got it. I prefer using a separate repository to store the mappings in YAML files. Any objections?

**Comment by strogonoff** [comment]
It’s not in scope for relaton-data repositories, and a new repository for persisting runtime data concerning xml2rfc compatibility will have to be created. Naming is to be confirmed.

I think the question raised in this issue is answered positively: BibXML service can read Git account username/secret from the environment, container orchestration definition will be updated accordingly.
