### ISSUE TITLE
Auto-index sources periodically

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#52]
Using Celery beat.

**Comment by ronaldtse** [comment]
In the K8s deployment we will need to translate this to a K8s cron job because resources are non-persistent.

**Comment by strogonoff** [comment]
I don't get the issue. If we use Celery, we can use celerybeat. If we can't use celery, we need to fix k8s configuration.

**Comment by ronaldtse** [comment]
@strogonoff @kwkwan has suggested that we can link the GHA workflow to trigger a reindex on updates. That seems more effective, right?

**Comment by strogonoff** [comment]
We could do that.

In this case, periodic update feature can be postponed, but it may be needed anyway if we have sources that aren‘t updated by GHA and can’t notify us.

**Comment by ronaldtse** [comment]
So far all of the datasets are updated at GHA, except for the Internet Drafts one which is the special case.

**Comment by strogonoff** [comment]
But your note that we can’t use celerybeat with k8s worries me. We run Celery in a container, and it runs periodic tasks using the same queue backend (Redis or Django/PostgreSQL), so there shouldn’t be an issue.

**Comment by strogonoff** [comment]
> So far all of the datasets are updated at GHA, except for the Internet Drafts one which is the special case.

For now.

**Comment by ronaldtse** [comment]
This is all done. Closing.

**Comment by strogonoff** [comment]
@ronaldtse This is not done, and we have not determined that it shouldn’t be done…

**Comment by ronaldtse** [comment]
@strogonoff oh, sorry about that. This task has to be done and we should do that.

**Comment by strogonoff** [comment]
Now there’s support to make indexing tasks auto requeue themselves (not using celerybeat or crontab), more in docs: https://dev.bibxml.org/static/docs/howto/auto-reindex-sources.html

**Comment by strogonoff** [comment]
By default the AUTO_REINDEX_INTERVAL is None, so no reindexing takes place—every indexing run must be triggered via GUI or API.
