### ISSUE TITLE
What is the 'rfc-anchor' document identifier?

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#53]
"rfc-anchor" is not a document identifier format though...

<img width="714" alt="Screenshot 2021-12-27 at 6 45 00 PM" src="https://user-images.githubusercontent.com/11865/147464255-48b2bef2-84c7-4e52-9aa3-c239744197df.png">

**Comment by strogonoff** [comment]
The behavior is as intended. The widget lists every available document type along with sample identifiers. I think the relevant issue was already filed against relaton-data-ids, when fixed this will go away.

By the way, where did you get this screenshot from? I don’t see the latest version deployed on the demo domain.

**Comment by ronaldtse** [comment]
This issue is now linked to https://github.com/relaton/relaton-ietf/issues/52

**Comment by strogonoff** [comment]
Also https://github.com/ietf-ribose/relaton-data-rfcsubseries/issues/3
