### ISSUE TITLE
Unable to locate exact bibliographic item according to index page examples

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#54]
<img width="667" alt="Screenshot 2021-12-27 at 6 46 59 PM" src="https://user-images.githubusercontent.com/11865/147464402-cf7d87e2-b581-4492-96fa-767669823b06.png">

The ID `3GPP TS 29.240:Rel-6/0.2.0` is supposed to be findable.

And on the first page of the 3GPP dataset, it is indeed the first one:
https://dev.bibxml.org/indexed-sources/3gpp/
<img width="976" alt="Screenshot 2021-12-27 at 6 47 25 PM" src="https://user-images.githubusercontent.com/11865/147464446-e0c4d055-8882-4088-9e94-610e8d986a50.png">

And it is accessible here:
https://dev.bibxml.org/indexed-sources/3gpp/TS_29.240_REL-6_0.2.0/

However, the service can't find it from the index page:
<img width="767" alt="Screenshot 2021-12-27 at 6 48 08 PM" src="https://user-images.githubusercontent.com/11865/147464499-57aaf880-0729-470e-9e51-e9b3fd934cc9.png">

I've tried a couple others to this effect. It used to work before.

Any idea?

**Comment by strogonoff** [comment]
This looks like a possible escaping issue, investigating

**Comment by strogonoff** [comment]
I see new demo URL…

**Comment by strogonoff** [comment]
Yes, colon was not OK for URLs, so now document IDs are fully escaped/quoted.

**Comment by ronaldtse** [comment]
Do we need to reindex? Because it's still not working.

**Comment by strogonoff** [comment]
Tested locally to work, can’t say for servers (no access). Maybe deployment has not completed.

**Comment by strogonoff** [comment]
I’m wrong. There is a case where `docid` is an object instead of a list, and the query is not equipped to handle that (the query presumes consistent data structure).

**Comment by ronaldtse** [comment]
@strogonoff when is `docid` not always an object? We need to know. Ping @andrew2net .

**Comment by strogonoff** [comment]
@ronaldtse  This is true for the entirety of the data, not just the docid field. If there’s a single value, it doesn’t appear in the list. I had to implement [a template helper](https://github.com/ietf-ribose/bibxml-service/blob/main/main/templatetags/relaton.py#L8) for this.

**Comment by ronaldtse** [comment]
I believe this came from a legacy support decision from @opoudjis and @andrew2net . Please confirm.

**Comment by andrew2net** [comment]
> @strogonoff when is `docid` not always an object? We need to know. Ping @andrew2net .

In relaton `docid` is always object.

**Comment by strogonoff** [comment]
@andrew2net could you answer @ronaldtse whether this is intentional for legacy support? Varying field type depending on the number of items complicates using Relaton data in YAML.

**Comment by andrew2net** [comment]
@strogonoff I can't answer the question, I just followed the requirements:
https://github.com/relaton/relaton-bib/issues/8#issuecomment-520807240
https://github.com/relaton/relaton-bib/blob/main/docs/hash.adoc#yaml

**Comment by ronaldtse** [comment]
@strogonoff see https://github.com/relaton/relaton-bib/issues/8#issuecomment-520807240 for the answer as it was pointed out.

@andrew2net I believe when Relaton generates YAML output, we can stick with a single value type (when multiple values are accepted, use an array instead of a string) and omit the shortcut. The exported YAML does not need to be "human-friendly". We only need to be friendly to that sort of input during parsing. Can you help make that update in relaton-bib?

**Comment by andrew2net** [comment]
> The exported YAML does not need to be "human-friendly". We only need to be friendly to that sort of input during parsing. Can you help make that update in relaton-bib?

Yes, sure.

**Comment by ronaldtse** [comment]
Thanks @andrew2net , that should make developer usage simpler (e.g. @strogonoff ) 👍

**Comment by andrew2net** [comment]
@ronaldtse YAML output is updated in relaton-bib v 1.9.17. Sorry for the delay, I'd been ill for 3 days.

**Comment by strogonoff** [comment]
I can confirm we have lists now. Still allowing for both lists and non-lists for the time being, while not all data have been regenerated.

**Comment by strogonoff** [comment]
This has been addressed and will be closed soon.
