### ISSUE TITLE
Manager’s GUI cannot show buttons to “reindex” in Firefox and Chrome

### ISSUE THREAD

**Issue by kwkwan** [ietf-ribose/bibxml-service#55]
"Queue reindex" is not a clickable button in some browsers such as Firefox and Chrome.

<img width="1329" alt="Screenshot 2021-12-28 at 2 30 26 PM" src="https://user-images.githubusercontent.com/29566367/147535855-623f6aac-4865-4045-86ec-32617eb05ba2.png">

Although "Queue reindex" is shown, this area is not clickable.

**Comment by ronaldtse** [comment]
Interesting. For the record my Safari shows a button:
<img width="872" alt="Screenshot 2021-12-28 at 3 24 24 PM" src="https://user-images.githubusercontent.com/11865/147539813-25401159-f433-4d08-8a47-a5d4770f8fbe.png">

In Firefox it is a box.
<img width="926" alt="Screenshot 2021-12-28 at 3 26 29 PM" src="https://user-images.githubusercontent.com/11865/147539974-453df27a-2403-4eab-8bec-313f97d7df9f.png">

The "(spec)" provides a link to the OpenAPI spec (this is not present in Safari).

**Comment by strogonoff** [comment]
Cross-browser compatibility issue with JS. Since JS is optional so far (management operations are API-first), it’s not critical, though it’s a bug.

**Comment by ronaldtse** [comment]
Thanks @strogonoff
