### ISSUE TITLE
Specification for standard retrieval API

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#6]
Here’s our API specification for BibXML service: [openapi.yaml](https://github.com/ietf-ribose/bibxml-service/blob/main/openapi.yaml). The API is evolving and can change in the coming week or so, but is it overall correct / on the right track?

The API describes two endpoints:

1. `/ref/` for retrieving a single standard’s metadata given dataset ID and standard reference. 
    * It returns JSON-encoded representation of citation, as it was indexed.
    * For DOI, it performs an additional trip to authoritative dataset.
    * For other datasets, it uses the index (much faster).
2. `/search/` for querying standards.
    * It accepts a JSON object as query. 
    * The most important part of it is `fields`, which for now simply matches provided values with whatever is in the index (e.g., `{ "fields": { "id": 1234, "doctype": "standard" } }`). 
    * The object also can contain a `dataset` field, without which search is performed across all datasets.
    * The object can also contain parameters `limit` and `offset` for windowing returned data.

**Comment by kesara** [comment]
@ronaldtse As per the [RFP](https://www.ietf.org/media/documents/BibXML_Service_RFP.pdf):

> The service must maintain the following backward compatibility with the existing
> service:
> a. URL structure and file naming of the current web service. For example
> /public/rfc/bibxml/reference.RFC.7991.xml. This will allow existing tools to
> quickly shift to using the new service.
> b. For certain datasets (detailed below) the service must support a ‘live’ file
> name, which always serves the latest version of an XML citation at the time of
> retrieval, while also supporting the serving of specific versions.  For example:
> reference.I-D.ietf-stir-passport-rcd.xml
> will return the XML citation for the current version of
> draft-ietf-stir-passport-rcd at the time of the request, while
> draft-ietf-stir-passport-rcd-09.xml
> will always return the XML citation for version -09 of the Internet-Draft.

Is that going to be part of this API?

**Comment by strogonoff** [comment]
Note: BibXML-service API spec had been updated, the new file in the repository is [`templates/openapi.yaml`](https://github.com/ietf-ribose/bibxml-service/blob/main/templates/openapi.yaml) and it’s now available on demo instance currently at http://34.229.41.119:8000/api/v1/.

**Comment by kesara** [comment]
Demo server's API document states that available legacy data sets are:
```
Enum: "bibxml" "bibxml2" "bibxml3" "bibxml-id" "bibxml4" "bibxml5" "bibxml6" "bibxml7" "bibxml8" "bibxml9" "bibxml-rfcsubseries" "bibxml-nist" 
```
This doesn't include some of the alias dataset names like: `bibxml-misc`, `bibxml-ieee`, `bibxml-3gpp`, `bibxml-w3c`, `bibxml-ids`.

**Comment by ronaldtse** [comment]
Thanks @kesara. @strogonoff could you please help update? thanks.

**Comment by strogonoff** [comment]
Regarding @kesara’s comment, this should have been comprehensively addressed in https://github.com/ietf-ribose/bibxml-service/issues/11#issuecomment-1024313089. Note that this ticket was intended to be about primary “new” retrieval API, and not legacy xml2rfc paths.

**Comment by strogonoff** [comment]
Please note that main API has changed substantially compared to what was described in this ticket description (I’m not sure I should update it or leave as is to reduce confusion). This has happened a few weeks back, and I think was not properly communicated.

Perhaps most impactful change is that the /ref/ endpoint (now called [Get citation by reference in source dataset](https://dev.bibxml.org/api/v1/#operation/getCitationByReferenceId)) is not intended for obtaining bibliographic item data anymore. Instead, there is [Get citation by document ID](https://dev.bibxml.org/api/v1/#operation/getCitationByDocId).

Which means, instead of e.g. https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml you’d use https://dev.bibxml.org/api/v1/by-docid/?docid=RFC8126&format=bibxml. The resulting XML would be the same (apart from the anchor property) as you’d get from https://dev.bibxml.org/public/rfc/bibxml/reference.RFC.8126.xml.

The old endpoint continues to exist, but it’ll likely be removed from the spec and left for internal use (if at all).

## Rationale

Our original implementation of interface (which includes API and GUI) meant that BibXML users needed to concern themselves which underlying source bibliographic data comes from. This had numerous issues:

1) Sources should essentially be irrelevant to the user, it’s implementation detail.
2) It would hinder future evolution of data sources, because changing sources would mean breaking behavior for the user.
3) Source implementation allows strictly one identifier for each item, which is their filename. However, users shouldn’t be affected by how sources choose to name files, and also in reality a single item can have multiple document identifiers.

The new implementation focuses on organizing data by subject-domain properties only, and the choice was made to rely on document identifiers.

**Comment by strogonoff** [comment]
API specification was updated in 23f81dbe45a11877637b1b93849b8ad7451289d9 to indicate required Datatracker API key for retrieval endpoints per #69.

**Comment by ronaldtse** [comment]
@strogonoff thank you for elaborating the rationale, it is clear and aligns with our discussions.

**Comment by ronaldtse** [comment]
@strogonoff if this is done can you close it? Thanks.

**Comment by strogonoff** [comment]
This issue was created to request feedback so I don’t know what the condition for closing it is.

**Comment by rjsparks** [comment]
We've been continuously evaluating the API and believe it is on the right track. I think this general feedback issue can be closed, and if we discover API considerations we can open specific issues for them.

**Comment by strogonoff** [comment]
Closing per Robert’s comment.
