### ISSUE TITLE
Search in the IETF category is unintuitive

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#60]
![image](https://user-images.githubusercontent.com/10996692/147954014-dd779902-c524-4d5a-95ec-a57a6b966f3c.png)

How am I supposed to find rfc 3261?

**Comment by rjsparks** [comment]
I tried variations on capitalization and space/no-space, and got the same results.

**Comment by ronaldtse** [comment]
Thanks @rjsparks . Related to #54 .

**Comment by strogonoff** [comment]
Yes, the document ID search is doing literal matches, but the freeform search form further down searches more extensively. Working on more search options and making freeform match faster.

**Comment by strogonoff** [comment]
Correction, exact match for RFC3261 *should* work, because the document exists: https://dev.bibxml.org/indexed-sources/rfcs/RFC3261/

The problem is that "RFC3261" identifier is specified with "scope=anchor". Looking into adjusting matching so that it is not thrown off by that structure.

This problem with duplicate identifiers (in this case, `RFC 3261` and `RFC3261` are both specified in Relaton data, which seems wrong) ctually this relates to https://github.com/ietf-ribose/relaton-data-rfcsubseries/issues/4. cc @ronaldtse, apparently this is to be discussed with Nick

**Comment by strogonoff** [comment]
Meanwhile, specifying `RFC 3261` (with the space) in search matches the other identifier and opens the correct document.

**Comment by ronaldtse** [comment]
> in this case, RFC 3261 and RFC3261 are both specified in Relaton data, which seems wrong

* "RFC 3261" is the canonical identifier for the document.
" "RFC3261" is the "anchor" used in the authoritative information. This "anchor" is commonly used as the citation reference in xml2rfc.

People will search using both patterns. Both should exist, and therefore what we have now is correct.

**Comment by strogonoff** [comment]
> Both should exist, and therefore what we have now is correct.

Citations shouldn’t have two canonical identifiers so similar but subtly different. Fuzzy search is a different matter.

**Comment by ronaldtse** [comment]
@strogonoff I need to clarify some terminology here.

* A **bibliographic item** is a representation of the metadata of an information resource.
* A **citation reference** is an entry in the bibliography that allows a reader to *locate* the cited information resource.
* A **citation** is the "instance" of referring to a **citation reference**.

And clarification of what Relaton is:

* Relaton is a **bibliographic item** data model.
* It can be used for **citations**.
* Citation styles **dictate** the format of the document identifier written in the document.

Relaton **cannot** tell you what a citation should look like.

**Comment by ronaldtse** [comment]
An example of different document identifier citation styles:
* In IETF, IETF documents are cited as "RFCXXXX"
* In ISO and OGC, IETF documents are cited as "IETF RFC XXXX".

**Comment by strogonoff** [comment]
> * In ISO and OGC, IETF documents are cited as "IETF RFC XXXX".

In this example, shouldn’t they use a different type then? E.g., “ISO” and “OGC”. Currently, we have two docids with the same type: `docid = [{'type': 'IETF', 'id': 'RFCXXXX'}, {'type': 'IETF', 'id': 'RFC XXXX', scope: 'anchor'}]`

**Comment by strogonoff** [comment]
> * A **citation reference** is an entry in the bibliography that allows a reader to _locate_ the cited information resource.
> * A **citation** is the "instance" of referring to a **citation reference**.

I’m not sure I have a complete picture of how citation reference and citation would look like.

It’s nice to have shared terminology, once I wrap my head around this I’ll add it to the glossary in bibxml-service docs. Currently it uses citation as an alias for bibliographic item.

**Comment by ronaldtse** [comment]
> In this example, shouldn’t they use a different type then? E.g., “ISO” and “OGC”. 

Here's the thing. IETF (the authoritative source) won't be able to specify the document identifier type used by other organizations, it can only give its own "canonical identifier". So "ISO" or "OGC" should not be in the bibliographic data. 

From my perspective, downstream users like "ISO" or "OGC" can only be facilitated with the additional pieces of data (as in structured data).

> `docid = [{'type': 'IETF', 'id': 'RFCXXXX'}, {'type': 'IETF', 'id': 'RFC XXXX', scope: 'anchor'}]`

I'm not sure what else I can say here. As mentioned above:
* `RFCXXXX` comes from the original source being the "anchor". This is used by the xml2rfc software which is the main consumer of the BibXML Service.
* `'RFC XXXX` also comes from the original source as identifier.

Technically, we can omit the "anchor", and have the BibXML Service generate that for the xml2rfc fetches (remember in legacy paths, the "anchor" attribute must match the filename of the request).

**Comment by ronaldtse** [comment]
Samples of terminology:

> * A **bibliographic item** is a representation of the metadata of an information resource.

A bibliographic item can be expressed in YAML or XML.

> * A **citation reference** is an entry in the bibliography that allows a reader to _locate_ the cited information resource.

These are references:
<img width="775" alt="Screenshot 2022-01-07 at 10 12 56 PM" src="https://user-images.githubusercontent.com/11865/148556070-0cf27d80-3941-45f0-bbc2-d530397eb9a7.png">

> * A **citation** is the "instance" of referring to a **citation reference**.

The `SOURCE` here is a citation. A citation allows also incorporation of a "locality".
<img width="777" alt="Screenshot 2022-01-07 at 10 13 30 PM" src="https://user-images.githubusercontent.com/11865/148556122-713421a1-406a-4bb3-b24b-28b840d3ea3f.png">

This is a citation:
![Uploading Screenshot 2022-01-07 at 10.14.39 PM.png…]()

**Comment by strogonoff** [comment]
Okay, so where I used “citation” in context of BibXML service I probably meant “bibliographic item”.

**Comment by strogonoff** [comment]
> IETF (the authoritative source) won't be able to specify the document identifier type used by other organizations, it can only give its own "canonical identifier". So "ISO" or "OGC" should not be in the bibliographic data.

Well, you previously said that ISO and OGC cite "RFCXXXX" as "IETF RFC XXXX". Immediately it looked to me that to accommodate this citation Relaton would provide `{ type: "ISO", id: "IETF RFC XXXX" }`. If not, then how would ISO and OGC obtain this "IETF RFC XXXX" string they use for citing?

This may be a Relaton question rather than BibXML service, but I want to understand what’s going on here if we’re using Relaton data model.

**Comment by ronaldtse** [comment]
>  If not, then how would ISO and OGC obtain this "IETF RFC XXXX" string they use for citing?

The author either writes it, or the authoring software "builds" this string given raw data (e.g. `{"series": "RFC", "number":"XXXX"}`), themselves.

**Comment by strogonoff** [comment]
> IETF (the authoritative source) won't be able to specify the document identifier type used by other organizations, it can only give its own "canonical identifier".

But DOI is used by Crossref, which is another organization, so how come IETF documents can have a DOI?

Relaton model seems to be confused as to `type` semantics. In some cases it’s used as a namespace for third-party publication identifier (DOI, ISBN). In other cases it’s used to specify the publishing organization (IETF, 3GPP).

**Comment by ronaldtse** [comment]
> But DOI is used by Crossref, which is another organization, so how come IETF documents can have a DOI?

As previously mentioned:
1. A document has an authoritative identifier.
2. A document can have **multiple** identifiers. The DOI is this.

> Relaton model seems to be confused as to type semantics.

I cannot claim that the semantics are perfect but I disagree.

> In some cases it’s used as a namespace (or schema) for some publication identifier (DOI, ISBN). 

DOI and ISBN identifiers are what they are.

* The former is a unique identifier that contains a "scope" and publication ID.
* ISBN Is a 9 or 13 digit unique number that identifies a publication.

> In other cases it’s used to specify the publishing organization (IETF, 3GPP).

No, they are used to indicate the "identifier". In this case, IETF and 3GPP are publishers, as well as the organization assigning the authoritative identifier.

> In yet other cases it’s used for something else entirely (e.g., in case where it appears more than once with different scope values).

Different identifiers of the same publisher need to be distinguishable.

Why is this a problem?

**Comment by strogonoff** [comment]
> No, they are used to indicate the "identifier". In this case, IETF and 3GPP are publishers, as well as the organization assigning the authoritative identifier.

So we seem to have different types that are not captured by the schema

It’d make more sense to indicate the actual _type_ of the identifier in the `type` field, and have it determine type-specific payload schema. For example, we can have `type=authoritative` and `type=external` with type-specific payloads, and for `type=authoritative` we can have `publisher=IETF` or `publisher=3GPP` while for `type=external` we can have `namespace=DOI` or `schema=DOI`, etc.

> Why is this a problem?

I am forced to add a hard-coded, manually maintained enum saying “these particular values of `docid.type` mean that `id` is authoritative identifier formatted for human readability, and those other values mean strict externally resolvable ID” as a crutch to address user confusion and work around a poorly normalized source data model.

**Comment by strogonoff** [comment]
My latest comments have been addressed per internal discussion about the meaning of docid and docid.type, and the original ticket description I believe no longer applies to current GUI.
