### ISSUE TITLE
UI should default to Internet-Draft searches, making RFC searches easy to navigate to

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#61]
Right now the UI at the dev service defaults to a 3gpp search (via a select control), and restores the control to 3gpp on a failed search. This is very painful.

This is the IETF bibxml service - it should have a strong focus on the RFC series and the Internet-Drafts. 

Since most identifiers have a set of patterns that identify the source of the document, why is this control needed at all?

**Comment by ronaldtse** [comment]
Agree. We should retool the search page to:

* focus on IETF publications
* not burden the user with selecting a dataset

**Comment by strogonoff** [comment]
BibXML removed support for separate `type` search parameter.
