### ISSUE TITLE
Legacy bibxml service for IDs is 500ing for one known name, and not recognizing the other.

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#62]
For reference, note: https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.I-D.draft-sparks-sipcore-multiple-reasons.xml

https://dev.bibxml.org/public/rfc/bibxml3/reference.I-D.sparks-sipcore-multiple-reasons.xml
is 500-ing.

https://dev.bibxml.org/public/rfc/bibxml-ids/reference.I-D.sparks-sipcore-multiple-reasons.xml
returns a json error:
```{"error": "Unable to find ref reference.I-D.sparks-sipcore-multiple-reasons: legacy dataset bibxml-ids is unknown"}```

**Comment by ronaldtse** [comment]
Thanks @rjsparks . 

There are two issues here:
* the BibXML service does not yet support the draft name without the sequential "draft number" (#64)
* the IDs dynamic dataset proxy/update functionality has not been implemented yet. Only the bulk load functionality is working at the moment. (#63)

This document does not yet exist in the bulk dataset:
<img width="911" alt="Screenshot 2022-01-04 at 3 18 40 PM" src="https://user-images.githubusercontent.com/11865/148023077-f59ed338-2fce-4bf6-84c8-fa934510dd67.png">

The bulk dataset last updated 16 hours ago:
https://github.com/ietf-ribose/relaton-data-ids/actions
<img width="913" alt="Screenshot 2022-01-04 at 3 18 59 PM" src="https://user-images.githubusercontent.com/11865/148023099-d69746cb-5bb5-4edc-a90b-bc9fae94c3b2.png">

Once #64 and #63 are implemented then this should work.

**Comment by strogonoff** [comment]
I believe the errors in ticket description have been addressed. [Both](https://dev.bibxml.org/public/rfc/bibxml3/reference.I-D.sparks-sipcore-multiple-reasons.xml) [paths](https://dev.bibxml.org/public/rfc/bibxml-ids/reference.I-D.sparks-sipcore-multiple-reasons.xml) return the correct document now, with minor formatting differences compared to the [reference](https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.I-D.draft-sparks-sipcore-multiple-reasons.xml).

Diff (xml2rfc in red, bibxml.org in green):

```diff
-<reference anchor="I-D.sparks-sipcore-multiple-reasons">
+<reference target="https://www.ietf.org/archive/id/draft-sparks-sipcore-multiple-reasons-00.txt" anchor="I-D.sparks-sipcore-multiple-reasons">
    <front>
       <title>Multiple SIP Reason Header Field Values</title>
-      <author fullname="Robert Sparks">
-        </author>
-      <date month="November" day="12" year="2021" />
+      <author fullname="Robert Sparks"/>
+      <date year="2021" month="November" day="12"/>
       <abstract>
-        <t>   The SIP Reason Header Field as defined in RFC 3326 allows only one
-   Reason value per protocol value.  Practice shows it is useful to
-   allow multiple values with the same protocol value.  This update to
-   RFC 3326 allows multiple values for an indicated registered protocol
-   when that protocol defines what the presence of multiple values
-   means.
-
-        </t>
+         <t>The SIP Reason Header Field as defined in RFC 3326 allows only one Reason value per protocol value. Practice shows it is useful to allow multiple values with the same protocol value. This update to RFC 3326 allows multiple values for an indicated registered protocol when that protocol defines what the presence of multiple values means.</t>
       </abstract>
    </front>
-   <seriesInfo name="Internet-Draft" value="draft-sparks-sipcore-multiple-reasons-00" />
-   <format type="TXT" target="https://www.ietf.org/archive/id/draft-sparks-sipcore-multiple-reasons-00.txt" />
+   <seriesInfo name="Internet-Draft" value="draft-sparks-sipcore-multiple-reasons-00"/>
 </reference>
```

The differences include using `target` attribute instead of `<format>` element (if needed for compatibility, can be serialized the other way around), using self-closing `<author>` element, different order of attributes on `<date>`, whitespace/indentation, and lacking `<?xml version="1.0" encoding="UTF-8"?>` preamble.

**Comment by rjsparks** [comment]
Stay your course on `target=` vs `<format>` for now, but be aware that this still a topic of discussion for how the RFCXML vocabulary may change. We may well, in the future, want to point to multiple rendered formats. Please help make sure that if that becomes true, it won't be too hard for us to change the code to get there.

**Comment by strogonoff** [comment]
> We may well, in the future, want to point to multiple rendered formats. Please help make sure that if that becomes true, it won't be too hard for us to change the code to get there.

Understood. Codebase now allows to register new output serializations (format keywords like “bibxml” now) at service startup. If the format element will be suitable for that, bibxml serialization can be adjusted to list other registered formats there.

One thing to note is that API currently requires a Datatracker token, so any link provided via format element would not work as is (token will have to be supplied in the appropriate header by the requester).

**Comment by rjsparks** [comment]
There's an assumption there that the links are back into the bibxml service? I think they would be pointing to other services that would not require an API token. It would be links like https://www.ietf.org/archive/id/draft-sparks-sipcore-multiple-reasons-00.txt, https://www.ietf.org/archive/id/draft-sparks-sipcore-multiple-reasons-00.xml, https://www.ietf.org/archive/id/draft-sparks-sipcore-multiple-reasons-00.html, etc.

**Comment by strogonoff** [comment]
@rjsparks yes, those links are shown on bibliographic item detail pages, it’ll be a small change to make them clickable.
