### ISSUE TITLE
Implement support for authenticating Datatracker API keys

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#69]
From @kesara :

The datatracker API endpoint to verify personal API tokens is `/api/appauth/bibxml`.

This endpoint will take `apikey` as a form parameter.

Example:
```console
$ curl -S -F "apikey=personal-apikey" https://datatracker.ietf.org/api/appauth/bibxml
```

If the personal API key is valid, datatracker will respond with HTTP status `200` and JSON output:
```json
{"success": true}
```

Otherwise, datatracker will respond with a non `200` HTTP status code.

This API endpoint is now available on datatracker.

For testing you can use similar endpoint: `/api/appauth/authortools`.

To obtain a personal API key for above endpoint:

* Go to https://datatracker.ietf.org/accounts/apikey/add (You need to login to datatracker)

* Select "/api/appauth/authortools" as the *Endpoint* and click *Create key* button.

More information about personal API keys, see https://datatracker.ietf.org/api/#personal-api-keys

We need to perform these tasks :

* [ ] Server side support for verify personal API tokens
* [ ] UI display of "logged-in" status on HTML

**Comment by strogonoff** [comment]
Could someone remind me which use case we have for this authentication?

**Comment by ronaldtse** [comment]
As per @rjsparks , future usage of the BibXML service may be linked with a Datatracker API key. For now, IETF will simply want to track usage per API key. The actual mechanics of when the API key is required is not yet decided by IETF.

**Comment by strogonoff** [comment]
Retrieval API now requires and validates a Datatracker API key. The mechanism is the same as for BibXML’s own tokens in management API but with the appropriate HTTP header name:

```
curl -sS -Hcontent-type:application/json -Hx-datatracker-token:<your-datatracker-bibxml-key> -X GET "https://dev.bibxml.org/api/v1/by-docid/?docid=978-0-7381-7420-4"
```

**Comment by strogonoff** [comment]
Regarding showing the logged-in flag in web GUI, the most appropriate way for that involves proper user authentication via Datatracker’s OAuth2/OIDC. (Otherwise users will need to paste their Datatracker token every time they switch machines or browsers, I don’t think anyone will bother to do that.)

I’d like to make sure whether that is required (and if so, which features we should require authentication for), or just the API integration is enough for now.

**Comment by ronaldtse** [comment]
As @strogonoff discovered, datatracker does support OpenID Connect: https://datatracker.ietf.org/api/

In order to display “logged in” status on HTML, requiring a user to enter the datatracker generated token as part of the initial URL is not practical, and a proper solution like OpenID Connect would work better (allowing people to login to datatracker and authenticate at the BibXML service). 

@rjsparks can we confirm that the BibXML service should support OpenID Connect authentication with Datatracker as part of the RFP deliverable?

**Comment by rjsparks** [comment]
@ronaldtse  - that's what the RFP says, but it also notes that we don't expect any difference in behavior from the web service when logged in or not - the requirement was in place to facilitate future growth.

We are at a point where we need to be done very soon and have this service deployed. I'm willing to skip having oidc integrated into the webservice. But please make sure you haven't done anything there that will make adding that integration later particularly difficult.

**Comment by strogonoff** [comment]
OAuth2/OIDC authentication is coming in today’s release, but since Datatracker doesn’t seem to provide a way to obtain a client ID and secret it’s a bit problematic to test. Maybe @kesara could help with procedures for registering an OIDC integration?

**Comment by rjsparks** [comment]
@strogonoff - I will have to provide those details.
To properly set this up, I'll need an initial set of valid redirect URIs to configure for the client. (Its ok to include any test location  URIs here as well as those for the demo service).
When you provide those, I'll send the details you need by email.

**Comment by strogonoff** [comment]
@rjsparks The service is configured to accept Datatracker OAuth2 provider redirect at https://.../datatracker-auth/callback/.

In case of public dev instance that would be https://dev.bibxml.org/datatracker-auth/callback/, client ID/secret for that environment should be directed to @kwkwan or @ronaldtse who could provision via repository secrets.

If it is not difficult, it would help to have a distinct ID/secret that would redirect to http://localhost:8000/datatracker-auth/callback for debugging purposes, but that is less important.

**Comment by ronaldtse** [comment]
@strogonoff this is done, right? If so please help close it. Thanks.

**Comment by strogonoff** [comment]
Yes, this is done.

**Comment by strogonoff** [comment]
Logged-in status is part of Datatracker OAuth2 integration, not dev API key support, and the remaining issue with it is filed separately under #116
