### ISSUE TITLE
Update BibXML service API and OpenAPI definition to support legacy paths

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#7]
From @kesara:

> The service must maintain the following backward compatibility with the existing service:
> a. URL structure and file naming of the current web service. For example `/public/rfc/bibxml/reference.RFC.7991.xml`. This will allow existing tools to quickly shift to using the new service.
> b. For certain datasets (detailed below) the service must support a ‘live’ file name, which always serves the latest version of an XML citation at the time of retrieval, while also supporting the serving of specific versions.  For example: `reference.I-D.ietf-stir-passport-rcd.xml` will return the XML citation for the current version of `draft-ietf-stir-passport-rcd` at the time of the request, while `draft-ietf-stir-passport-rcd-09.xml`
will always return the XML citation for version `-09` of the Internet-Draft.

_Originally posted by @kesara in https://github.com/ietf-ribose/bibxml-service/issues/6#issuecomment-938308596_

**Comment by strogonoff** [comment]
A question about legacy paths:

- The example lists /public/rfc/ path as an example. Is that the only path we should support, or are there other legacy paths? E.g., /public/i-ds/, etc.
- The data repo contains more than just RFCs (for example, 3GPP standards: https://github.com/relaton/relaton-data-ietf/blob/master/data/reference.3GPP.25.870.xml). Are they there in error, or should we handle them somehow (make available under some legacy path, or skip conditionally)?

cc @ronaldtse

**Comment by ronaldtse** [comment]
@strogonoff we should not be looking at relaton-data-ietf -- that repo is not to be used here.

We only need to provide the legacy paths for the following.

Datasets

* (bibxml) IETF RFCs: http://xml2rfc.tools.ietf.org/public/rfc/bibxml/
* (bibxml2) Misc collection (W3C, ISO, ITU, ANSI, FIPS, CCITT [previous name of ITU], IEEE) : http://xml2rfc.tools.ietf.org/public/rfc/bibxml2/
* (bibxml3) IETF Internet-Drafts: http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/
* (bibxml4) W3C: http://xml2rfc.tools.ietf.org/public/rfc/bibxml4/
* (bibxml5) 3GPP: http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/
* (bibxml6) IEEE: http://xml2rfc.tools.ietf.org/public/rfc/bibxml6/
* (bibxml9) IETF BCP, FYI, STD: http://xml2rfc.tools.ietf.org/public/rfc/bibxml9/

Services
* (bibxml7) DOI references
* (bibxml8) IANA references

**Comment by strogonoff** [comment]
@ronaldtse

1. Question on dynamic datasets: am I correct that

    A) IANA should be handled same way as DOI (i.e., we need to make a network trip for it), and
    B) IANA and DOI should provide legacy output (if so, under which paths)?

    I think this was missed by some architecture diagrams (e.g., https://github.com/ietf-ribose/bibxml-project/issues/2).

2. Question on static IETF datasets: we discussed having raw _and_ Relaton repositories, such as `relaton-data-raw-ietf`. Won’t raw repositories cover these datasets? If they will, shouldn’t we just use raw repositories to provide legacy data?

    If not, we cam provide custom logic for the indexer to fetch the data, but I worry it will be duplicated by the GHA that fetches static datasets from IETF sources.

**Comment by ronaldtse** [comment]
@strogonoff let's forget about the `relaton-data-*` repositories in the `relaton` GitHub organization. Those repositories are for the Relaton service and are separate from the IETF service. We're only going to work with the repos in the `ietf-ribose` GitHub organization.

The `relaton-data-ietf` repository is the Relaton copy of the IETF data, i.e. it is a downstream user of the IETF data. It is only intended for Relaton internal use.

Right now we are working on the "authoritative copy" of the IETF data as in the BibXML service. i.e. in the future, we will restructure relaton-data-ietf to pull from the BibXML service.

---------

> Question on all static datasets: we discussed keeping raw (e.g., relaton-data-raw-ietf) in addition to Relaton YAML repositories. Won’t the raw repositories cover this legacy data? If they will, shouldn’t we just use raw repositories to provide legacy data?
>
> A) If all those static datasets are covered by ietf and other raw data repos, we could rely on that and where needed implement a function that determines under which legacy path a given standard should be exposed by matching the patterns you provided to XML filenames under /data/.

We do not have `relaton-data-*` for the BibXML service. 

The BibXML service will rely on the `bibxml-data-*` repos (in the `ietf-ribose` GitHub org) as dataset data sources for authoritative data.

I think your question is whether the "legacy paths" will be serviced through:
* the BibXML service; or
* static data repositories via a redirect from the BibXML service
 
I believe the answer is the former.

**Comment by ronaldtse** [comment]
Thanks for the helpful thoughts. Agree with most if not all statements. This all boils down to a synchronisation implementation between the BibXML and datatracker services for bibxml3.

To simplify, the requirements we have here are:

1. Versioned BibXML served by the BibXML service must be accurate and timely. The delay from a draft being made available at datatracker to it being available from the BibXML service should be minimal. The update mechanism is that the datatracker will inform the BibXML service via API if a new draft is made available.

2. Un-versioned, or "latest version" BibXML should always refer to the latest draft. This delay must be minimal. The update of the latest version can be done with the API in 1.

If these were the only requirements, the simplest option is to have the BibXML service redirect all bibxml3 queries (versioned or unversioned) directly to the datatracker -- that way the data is always accurate, there is no overhead, and we save on the need to implement caching and proxying.

That said, the BibXML service is also supposed to provide searching functionality -- a simple redirect, or even a proxy request, won't fulfil this. In order to provide searching functionality for the bibxml3 collection, the BibXML service will need the full database of Internet-Drafts.

Am I missing anything here?

**Comment by ronaldtse** [comment]
> E.g., bibxml9 and bibxml-rfcsubseries — is one “alias” and another one “proper”?

Both are official names. I would prefer to use the latter as the "proper" name and the former an "alias" to it.

**Comment by ronaldtse** [comment]
Due to the amount of content and confusion in this ticket I'm going to migrate the task to a new issue.

**Comment by ronaldtse** [comment]
Superseded by https://github.com/ietf-ribose/bibxml-service/issues/11

**Comment by TonyLHansen** [comment]
No, I'll stand by my previous statement. The exhaustive table that Ronald Tse put into #7  summarizing all of the datasets is not replicated in #11.

(Just spotted a typo in the table, where it says bibxml8-iana instead of bibxml-iana.)
