### ISSUE TITLE
Static is not properly generated in production

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#70]
This is where static is generated: 
https://github.com/ietf-ribose/bibxml-service/blob/9258b7e4d8fea856e68e084658aba27b1dd17dd9/docker-compose.yml#L65

This may not be happening in prod, because JS references a nonexistent file, causing broken GUI (e.g., [no button on this management page](https://dev.bibxml.org/management/rfcs/).

Currently this only affects JS, but once we use the same mechanism for CSS it will also break CSS.

**Comment by ronaldtse** [comment]
@strogonoff this is happening here:
https://github.com/ietf-ribose/bibxml-service/blob/9258b7e4d8fea856e68e084658aba27b1dd17dd9/k8s/ws/ws-deployment.yaml#L24

Is there a command to verify that those generated assets are created?

**Comment by ronaldtse** [comment]
@strogonoff there's also a difference now with the command in k8s, which uses runserver instead of daphne.

https://github.com/ietf-ribose/bibxml-service/blob/9258b7e4d8fea856e68e084658aba27b1dd17dd9/docker-compose.yml#L66-L70

@kwkwan can you help update that?

**Comment by strogonoff** [comment]
> @strogonoff this is happening here:
> 
> https://github.com/ietf-ribose/bibxml-service/blob/9258b7e4d8fea856e68e084658aba27b1dd17dd9/k8s/ws/ws-deployment.yaml#L24
> 
> 
> 
> Is there a command to verify that those generated assets are created?

Not really, it is an idempotent command and it can be run at each deployment/instance startup.

**Comment by strogonoff** [comment]
The file you referenced also sets DEBUG to True and host to `localhost`.

I don’t think we actually use this setup in production, because Django would reject requests from non-localhost (unless we have some kind of proxy setup that overrides HTTP Host header, turning off Django’s checks against attacks that rely on header faking, which would be bad).

Additionally, I am not seeing tracebacks on 500 errors, which would happen if we had DEBUG set to True.

**Comment by kwkwan** [comment]
In production environment, PRIMARY_HOSTNAME is set to `*`, DEBUG is set to `0` and the command to start the frontend web application is `python manage.py collectstatic --noinput && daphne bibxml.asgi:application -p 8000 -b 0.0.0.0`.

**Comment by strogonoff** [comment]
Good. Hostname must match dev.bibxml.org though (infosec matter).

**Comment by strogonoff** [comment]
I confirmed that static is generated with current Docker Compose setup when DEBUG=0 and Daphne is used, so missing static looks to be production environment specific.

**Comment by strogonoff** [comment]
Correction, there’s something going on with static and clean-slate Docker setup, investigating…

**Comment by strogonoff** [comment]
The static problem I encountered was related to different behavior of mounted volumes using Docker & Compose on Linux vs. macOS. It’s probably unrelated to modules not being built in production.

**Comment by strogonoff** [comment]
I’ve pushed a fix. Note that there’s another management command that needs to be run before `collectstatic`: https://github.com/ietf-ribose/bibxml-service/blob/main/docker-compose.yml#L70
