### ISSUE TITLE
Open :5555 port for async worker monitoring

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#71]
It’s still useful for troubleshooting task activity in production environment.

If needed we can assess and put it behind a basic auth (like the management GUI) if needed.

**Comment by strogonoff** [comment]
This is needed, because right now the https://dev.bibxml.org/management/indexable-sources/ids/ indexing task seems to be stuck and there’s no visibility into why.

**Comment by ronaldtse** [comment]
This is done in https://github.com/ietf-ribose/bibxml-infrastructure/issues/6, and the task stalling issue is fixed in https://github.com/ietf-ribose/bibxml-infrastructure/issues/17 . Closing.
