### ISSUE TITLE
Search working very slowly on Fargate deployment

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#72]
Ever since we migrated to Fargate the search functionality works very slowly, leading to container timeouts.

In previous benchmarking, this has been shown to be a network performance problem between Fargate containers and other AWS services, in this case, the communication between the Fargate container and RDS (Postgres). Similar reports are available on the Internet.

We either need to fall back to a EKS dedicated node container, or move to Lambda. This performance limitation seems quite insane. Moving to Lambda would probably be good since they now accept containers up to 20GB. We can just take our container and replace the entrypoint with the necessary AWS Lambda code.

When we do the migration, we should also tie the BibXML service code to the container version so that we pre-compile all static assets at the container build instead of having to "build assets while we launch the container" (which is an anti-pattern).

**Comment by strogonoff** [comment]
Aren’t we investing too much resources into one particular deployment configuration (which means the overhead of always maintaining K8s configuration in accordance with changes to Compose configuration, etc.) without knowing whether it’ll still be used after production service operations are taken over?

**Comment by ronaldtse** [comment]
@strogonoff true, but it's an experiment we want to get an answer for due to various reasons. It would be eventually benefit IETF if they ever wish to use a cloud native setup such as Lambda. If we go Lambda the k8s setup would no longer be necessary.

**Comment by strogonoff** [comment]
Taken some measures to improve search performance (caching, search result cap). The next big measure on app level will be storing data adapted for search (e.g., search vectors, etc.) at indexation stage.

Also, this is where we are running into PostgreSQL limitations, but I’m not sure if we want to run ES yet.

@ronaldtse @kwkwan If we add ES, will our demo setup be able to cope? Previously I’d have just added a new Docker Compose service, but now I have to worry about that (and associated costs).

**Comment by strogonoff** [comment]
As of now:

- This takes 30 seconds: https://dev.bibxml.org/search/?bypass_cache=1&query=weather&query_format=websearch

- This takes less than 1 second: https://bibxml-dev.strogonoff.name/search/?bypass_cache=1&query=weather&query_format=websearch

This is the same query, same codebase commit, roughly same number of indexed items. And I am running all containers on a single $10/month instance with one vCPU and 2GB RAM.

I don’t think this can be explained by networking lag from web to db. Maybe migrations are not applied correctly and PostgreSQL indices did not get created?

**Comment by kwkwan** [comment]
The db migration have updated and re-run.  Please test it again.

**Comment by strogonoff** [comment]
Not sure what you mean. Migration should happen _on every deploy_, as is done in docker-compose on web-precheck stage. If not then we are running different database schemas in development and production.

**Comment by strogonoff** [comment]
Search is faster now but we need to make sure migrations are run or let me know if I need to ping whenever schema changes?

**Comment by kwkwan** [comment]
An issue has been created to handle migration. https://github.com/ietf-ribose/bibxml-service/issues/101

**Comment by strogonoff** [comment]
I think search works fast enough now, and if migrations are auto-applied this could be fixed.
