### ISSUE TITLE
Move static asset generation inside the Docker container

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#76]
Needs to be run during the Docker build process, not at Docker container start.

https://github.com/ietf-ribose/bibxml-service/blob/4610c0a2606a9fb8b86f5c9cc99486359bcd0a91/Dockerfile#L21-L23

**Comment by strogonoff** [comment]
Waiting for rebuild just to see updated static is a non-starter in development, but I’ll look into some compromise that will allow us to support hot reload while baking in static into the image.

Also, built static assets (and already now files added by `npm install`) are completely unnecessary for `celery` service. We might build two containers at some point, not sure.
