### ISSUE TITLE
Implementing Crossref etiquette

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#77]
Crossref’s API docs on etiquette and `crossrefapi` library that apparently follows that spec suggest supplying caller’s information with API requests, including service URL and contact email. It is said that complying helps not getting throttled as much.

For the record, the information is supplied here: https://github.com/ietf-ribose/bibxml-service/blob/main/sources/doi/__init__.py#L16

It can be amended if needed and likely moved into configuration option at some point.

**Comment by ronaldtse** [comment]
@strogonoff can we use dev.bibxml.org for now? Thanks!

**Comment by ronaldtse** [comment]
> moved into configuration option at some point 

Closing this and moving the remaining configuration option to a new ticket.
