### ISSUE TITLE
How to access logs in web/celery instances in our demo infrastructure setup?

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#79]
Currently, /management/ returns HTTP 500, but I’m unable to access error logs. The error is not reproducible on my instance brought up using docker-compose from latest snapshot.

**Comment by ronaldtse** [comment]
@kwkwan can you help @strogonoff find a way to access the logs?

**Comment by kwkwan** [comment]
I can setup a manual github workflow action to get logs of the web and celery pods.

**Comment by ronaldtse** [comment]
@kwkwan that's clever! Thanks!
