### ISSUE TITLE
Move Crossref etiquette details to configuration

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#81]
Crossref etiquette details should be accessible via configuration options instead of needing to modify code.

https://github.com/ietf-ribose/bibxml-service/blob/0d1158f506d2153744a4176f95e3e37559da9a41/sources/doi/__init__.py#L16-L22

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/bibxml-service/issues/77#issuecomment-1013906999_

**Comment by strogonoff** [comment]
I believe almost all of the requisite details are in fact already available from the environment, and those that aren’t (email and site name) will have to be anyway (email for error reporting notifications, site title just to reduce duplication).
