### ISSUE TITLE
Abstract is invalid

### ISSUE THREAD

**Issue by kesara** [ietf-ribose/bibxml-service#87]
Example: https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml

`abstract` element can not contain `text`. See https://xml2rfc.tools.ietf.org/xml2rfc-doc-3.11.1.html#name-abstract-2

Current bibxml files uses `t` elements for this. See https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

**Comment by ronaldtse** [comment]
Thank you @kesara , this is a bug and we will get this fixed.

**Comment by strogonoff** [comment]
Can we transfer these tickets to appropriate source data repositories?

**Comment by andrew2net** [comment]
@strogonoff this issue is fixed in the source data repo. Can we close it?

**Comment by strogonoff** [comment]
Not up to me to decide, right now the service treats XML files  as opaque blobs passed as is from the sources and I don't know how valid BibXML is supposed to look. Maybe @ronaldtse  could take a look…

**Comment by ronaldtse** [comment]
@andrew2net next time can you post the data link? It takes an extra step to go and find an example and then verify... Thanks.

**Comment by ronaldtse** [comment]
Here's the link:
https://github.com/ietf-ribose/bibxml-data-rfcs/blob/3ebd26ca7796ab15e9ded5b3b0eb2b825e607e69/data/RFC8126.xml#L15-L19

```xml
    <abstract>
      <t>Many protocols make use of points of extensibility that use constants to identify various protocol parameters. To ensure that the values in these fields do not have conflicting uses and to promote interoperability, their allocations are often coordinated by a central record keeper. For IETF protocols, that role is filled by the Internet Assigned Numbers Authority (IANA).</t>
      <t>To make assignments in a given registry prudently, guidance describing the conditions under which new values should be assigned, as well as when and how modifications to existing values can be made, is needed. This document defines a framework for the documentation of these guidelines by specification authors, in order to assure that the provided guidance for the IANA Considerations is clear and addresses the various issues that are likely in the operation of a registry.</t>
      <t>This is the third edition of this document; it obsoletes RFC 5226.</t>
    </abstract>
```

Yes I believe this is fixed.
