### ISSUE TITLE
Provide instructions on how to test service

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#9]
From @yablokov :

> Now available (bibxml-indexer):
> 
> http://127.0.0.1:8001/api/v1/indexer/<dataset_name>/run
> http://127.0.0.1:8001/api/v1/indexer/<dataset_name>/stop
> http://127.0.0.1:8001/api/v1/indexer/<dataset_name>/reset
> http://127.0.0.1:8001/api/v1/indexer/<dataset_name>/status
> 
> (as it described: https://github.com/ietf-ribose/bibxml-indexer/blob/master/openapi.yaml )
> 
> At indexer settings.py I have configured datasets:
> - ecma
> - nist
> - ietf
> - itu-r
> - calconnect
> - cie
> - iso
> - bipm
> - iho
> 
> (get it from https://github.com/relaton?q=relaton-data-&type=&language=&sort= )
> 
> 
> You can start indexation at bibxml-indexer instance:
> http://127.0.0.1:8001/api/v1/indexer/ecma/run
> 
> And read result from bibxml-service after indexation finish:
> http://127.0.0.1:8000/api/v1/ref/ecma/ECMA-154
> 
> 
> You can start indexation at bibxml-indexer instance:
> http://127.0.0.1:8001/api/v1/indexer/nist/run
> 
> And read result from bibxml-service after indexation finish:
> http://127.0.0.1:8000/api/v1/ref/nist/LCIRC288
> 
> Repo/datasets at  bibxml-indexer reads from configuration: https://github.com/ietf-ribose/bibxml-indexer/blob/master/indexer/settings.py

**Comment by strogonoff** [comment]
Documentation has a [page](https://dev.bibxml.org/static/docs/howto/run-tests.html) on running tests, and Stefano will likely help expand relevant sections.

**Comment by ronaldtse** [comment]
Thanks, closing.
