### ISSUE TITLE
Downtime during deployment

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#93]
While this is probably not important for demo infrastructure, we could probably avoid it. Web container _can_ run in multiple instances, just have to make sure celery and db never do.

**Comment by kwkwan** [comment]
Currently, web container is run a single pod, which can be scaled to multiple pods on request.  The celery container is run a single pod.  DB is run by AWS RDS, which is a single instance.

**Comment by strogonoff** [comment]
Yes, so we can arrange zero-downtime by having more than one web container during deployment.

**Comment by strogonoff** [comment]
I don’t think K8s guarantees pods will run as a single instance without a StatefulSet or some special measure like that, by the way. This may be a theoretical issue for db and celery.

**Comment by ronaldtse** [comment]
Closing, this is irrelevant to the bibxml-service itself.
