### ISSUE TITLE
Investigate why version is not showing up in production

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#96]
It looks like Wa added requisite variable in https://github.com/ietf-ribose/bibxml-service/issues/95, not sure why it’s not being read by Django settings at runtime (works for me locally).

Maybe it’s a Docker image build issue? I’m not sure about ARG/ENV https://github.com/ietf-ribose/bibxml-service/blob/f728a99f990c937c60938931a9e8b1c23fda407d/Dockerfile#L6-L7

**Comment by kwkwan** [comment]
The github action is currently triggered by setting a tag.  Should I manually run the action to build docker image on `main` branch?

**Comment by strogonoff** [comment]
No need, I’ve just pushed a different fix so will wait and see…

**Comment by strogonoff** [comment]
Hmm, still not showing up. We read it from environment variables in settings ([here](https://github.com/ietf-ribose/bibxml-service/blob/main/bibxml/settings.py#L241)), which should work as intended, so my concern is that this part in Dockerfile: https://github.com/ietf-ribose/bibxml-service/blob/38e1ccd4f422a98b27aaeb9ac2c785dbe59395a6/Dockerfile#L5-L8

is wrong and makes the variable not being communicated to running container.

**Comment by strogonoff** [comment]
Maybe I should remove ARG/ENV🧐 My Dockerfile kung fu is bad…

**Comment by strogonoff** [comment]
Trying in https://github.com/ietf-ribose/bibxml-service/commit/a0e54866ce66493f004f81619a817675fde482da

**Comment by strogonoff** [comment]
OK, so the problem is that `SNAPSHOT` is expected to be given at runtime (where we run `hypercorn`). I don’t know yet how we can capture it at container build time.

**Comment by strogonoff** [comment]
Or it could be due to shallow clone.
