### ISSUE TITLE
Cloned repositories do not persist between deployments

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#98]
This means after each deploy indexing takes longer (repository must be cloned again instead of just pulling what changed). The task now logs a warning when this happens.

**Comment by ronaldtse** [comment]
This is normal though. We don't really want persistence because it means resources are persistent.

**Comment by strogonoff** [comment]
Not sure what's inherently bad about persistence

**Comment by ronaldtse** [comment]
Because every job is run independently by an independent container. Feature not a bug. Closing.
