### ISSUE TITLE
The most complete BibXML specification

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#99]
Would someone provide pointers to:

- Latest BibXML specification
- Subset/peculiarities of it that apply to IETF BibXML service

Googling reveals surprisingly little.

**Comment by JayDaley** [comment]
https://datatracker.ietf.org/doc/html/rfc7991#section-2.40

**Comment by JayDaley** [comment]
The [RFP](https://www.ietf.org/media/documents/BibXML_Service_RFP.pdf) goes into detail for each dataset.  Let us know if more info is required.

**Comment by strogonoff** [comment]
@JayDaley Thank you. Tried [searching](https://dev.bibxml.org/search/?query=bibxml&query_format=websearch) available bibliographic data by “bibxml” but the literal term does not appear, I should’ve looked in RFP…

**Comment by ronaldtse** [comment]
FYI the XML grammar in RFC 7991 is not the most recent. It's in some xml2rfc internet-draft.

From @opoudjis:

> There is a 7991bis and another couple of documents floating around, but this is your most authoritative source.
https://xml2rfc.tools.ietf.org/xml2rfc-doc.html
